package httpadapter

import (
	"context"
	"encoding/json"
	"time"

	"github.com/pcaokhai/stayguard/api/internal/adapter/http/gen"
	"github.com/pcaokhai/stayguard/api/internal/app"
)

// OwnerService is what the owner overview handler needs from the application layer.
type OwnerService interface {
	Overview(ctx context.Context, c app.Caller, date *time.Time) (app.OwnerOverview, error)
}

func (s Server) GetOwnerOverview(ctx context.Context, req gen.GetOwnerOverviewRequestObject) (gen.GetOwnerOverviewResponseObject, error) {
	c, err := s.featureCaller(ctx, true)
	if err != nil {
		return nil, err
	}
	var date *time.Time
	if req.Params.Date != nil {
		d := req.Params.Date.Time
		date = &d
	}
	v, err := s.owner.Overview(ctx, c, date)
	if err != nil {
		return nil, err
	}
	out, err := toOverview(v)
	if err != nil {
		return nil, err
	}
	return gen.GetOwnerOverview200JSONResponse(out), nil
}

// toOverview goes through JSON because the generated byBuilding element is an anonymous struct.
func toOverview(v app.OwnerOverview) (gen.OwnerOverview, error) {
	type building struct {
		BuildingID string `json:"buildingId"`
		Name       string `json:"name"`
		Revenue    int64  `json:"revenue"`
	}
	type payment struct {
		PaymentID string    `json:"paymentId"`
		RoomCode  string    `json:"roomCode"`
		Method    string    `json:"method"`
		Amount    int64     `json:"amount"`
		At        time.Time `json:"at"`
	}
	buildings, payments := []building{}, []payment{}
	for _, b := range v.ByBuilding {
		buildings = append(buildings, building{b.BuildingID, b.Name, b.Cash + b.Transfer})
	}
	for _, p := range v.LatestPayments {
		payments = append(payments, payment{p.PaymentID, p.RoomCode, p.Method, p.Amount, p.At})
	}
	raw, err := json.Marshal(map[string]any{
		"date": v.Date, "revenueTotal": v.RevenueTotal, "transfersReceived": v.TransfersReceived, "cashExpected": v.CashTotal,
		"byBuilding": buildings, "alerts": []any{}, "unreadAlerts": v.UnreadAlerts, "latestPayments": payments,
		"occupancy": map[string]int{"occupiedRooms": v.OccupiedRooms, "totalRooms": v.TotalRooms, "overdueRooms": v.OverdueRooms},
	})
	var out gen.OwnerOverview
	if err != nil {
		return out, err
	}
	if err := json.Unmarshal(raw, &out); err != nil {
		return out, err
	}
	out.Alerts = make([]gen.Alert, len(v.Alerts))
	for i, a := range v.Alerts {
		out.Alerts[i] = toAlert(a)
	}
	status := make([]gen.BuildingStatus, len(v.Buildings))
	for i, b := range v.Buildings {
		status[i] = gen.BuildingStatus{BuildingId: b.ID, Code: b.Code, TotalRooms: b.Total, Occupied: b.Occupied, Vacant: b.Vacant,
			ToClean: b.ToClean, Overdue: b.Overdue, Maintenance: b.Maintenance, OccupancyPct: float32(b.OccupancyPct), RevenueToday: b.RevenueToday}
	}
	attention := make([]gen.AttentionItem, len(v.Attention))
	for i, a := range v.Attention {
		attention[i] = gen.AttentionItem{Kind: gen.AttentionItemKind(a.Kind), Ref: a.Ref, RoomCode: nilIfEmpty(a.RoomCode), Minutes: a.Minutes, Amount: a.Amount}
	}
	out.Buildings, out.Attention = &status, &attention
	return out, nil
}
