// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alerts.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAlert = `-- name: InsertAlert :exec
INSERT INTO app.alerts (id, tenant_id, kind, room_code, shift_id, stay_id, actor_id, amount, details)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9)
`

type InsertAlertParams struct {
	ID       string
	TenantID string
	Kind     string
	RoomCode pgtype.Text
	ShiftID  pgtype.Text
	StayID   pgtype.Text
	ActorID  pgtype.Text
	Amount   pgtype.Int8
	Details  []byte
}

func (q *Queries) InsertAlert(ctx context.Context, arg InsertAlertParams) error {
	_, err := q.db.Exec(ctx, insertAlert,
		arg.ID,
		arg.TenantID,
		arg.Kind,
		arg.RoomCode,
		arg.ShiftID,
		arg.StayID,
		arg.ActorID,
		arg.Amount,
		arg.Details,
	)
	return err
}
