// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bank.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearDefaultBankAccount = `-- name: ClearDefaultBankAccount :exec
UPDATE app.bank_accounts SET is_default = false WHERE tenant_id = $1 AND is_default
`

func (q *Queries) ClearDefaultBankAccount(ctx context.Context, tenantID string) error {
	_, err := q.db.Exec(ctx, clearDefaultBankAccount, tenantID)
	return err
}

const connectBankAccount = `-- name: ConnectBankAccount :exec
UPDATE app.bank_accounts SET sepay_status = 'CONNECTED' WHERE tenant_id = $1 AND id = $2
`

type ConnectBankAccountParams struct {
	TenantID string
	ID       string
}

func (q *Queries) ConnectBankAccount(ctx context.Context, arg ConnectBankAccountParams) error {
	_, err := q.db.Exec(ctx, connectBankAccount, arg.TenantID, arg.ID)
	return err
}

const deleteBankAccount = `-- name: DeleteBankAccount :execrows
DELETE FROM app.bank_accounts WHERE tenant_id = $1 AND id = $2 AND NOT is_default
`

type DeleteBankAccountParams struct {
	TenantID string
	ID       string
}

func (q *Queries) DeleteBankAccount(ctx context.Context, arg DeleteBankAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBankAccount, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBankAccount = `-- name: GetBankAccount :one
SELECT id, bank_bin, bank_name, account_no_masked, account_name, is_default, sepay_status, make_default_when_connected, last_webhook_at
FROM app.bank_accounts WHERE tenant_id = $1 AND id = $2 FOR UPDATE
`

type GetBankAccountParams struct {
	TenantID string
	ID       string
}

type GetBankAccountRow struct {
	ID                       string
	BankBin                  string
	BankName                 string
	AccountNoMasked          string
	AccountName              string
	IsDefault                bool
	SepayStatus              string
	MakeDefaultWhenConnected bool
	LastWebhookAt            pgtype.Timestamptz
}

func (q *Queries) GetBankAccount(ctx context.Context, arg GetBankAccountParams) (GetBankAccountRow, error) {
	row := q.db.QueryRow(ctx, getBankAccount, arg.TenantID, arg.ID)
	var i GetBankAccountRow
	err := row.Scan(
		&i.ID,
		&i.BankBin,
		&i.BankName,
		&i.AccountNoMasked,
		&i.AccountName,
		&i.IsDefault,
		&i.SepayStatus,
		&i.MakeDefaultWhenConnected,
		&i.LastWebhookAt,
	)
	return i, err
}

const getProperty = `-- name: GetProperty :one
SELECT t.guesthouse_code, p.id, p.name, p.address, p.phone, p.qr_expiry_minutes, p.id_retention_days, p.front_desk_history_days
FROM app.properties p JOIN app.tenants t ON t.id = p.tenant_id
WHERE p.tenant_id = $1
ORDER BY p.created_at, p.id LIMIT 1
`

type GetPropertyRow struct {
	GuesthouseCode       pgtype.Text
	ID                   string
	Name                 string
	Address              pgtype.Text
	Phone                pgtype.Text
	QrExpiryMinutes      int32
	IDRetentionDays      int32
	FrontDeskHistoryDays int32
}

func (q *Queries) GetProperty(ctx context.Context, tenantID string) (GetPropertyRow, error) {
	row := q.db.QueryRow(ctx, getProperty, tenantID)
	var i GetPropertyRow
	err := row.Scan(
		&i.GuesthouseCode,
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.QrExpiryMinutes,
		&i.IDRetentionDays,
		&i.FrontDeskHistoryDays,
	)
	return i, err
}

const getSepayState = `-- name: GetSepayState :one
SELECT t.sepay_signature_ok, (t.sepay_secret_enc IS NOT NULL)::boolean AS has_secret, t.hook_id,
       EXISTS (SELECT 1 FROM app.bank_accounts b WHERE b.tenant_id = t.id AND b.is_default AND b.sepay_status = 'CONNECTED') AS default_connected,
       (SELECT max(b.last_webhook_at) FROM app.bank_accounts b WHERE b.tenant_id = t.id)::timestamptz AS last_webhook_at
FROM app.tenants t WHERE t.id = $1
`

type GetSepayStateRow struct {
	SepaySignatureOk pgtype.Bool
	HasSecret        bool
	HookID           pgtype.Text
	DefaultConnected bool
	LastWebhookAt    pgtype.Timestamptz
}

func (q *Queries) GetSepayState(ctx context.Context, tenantID string) (GetSepayStateRow, error) {
	row := q.db.QueryRow(ctx, getSepayState, tenantID)
	var i GetSepayStateRow
	err := row.Scan(
		&i.SepaySignatureOk,
		&i.HasSecret,
		&i.HookID,
		&i.DefaultConnected,
		&i.LastWebhookAt,
	)
	return i, err
}

const insertBankAccount = `-- name: InsertBankAccount :exec
INSERT INTO app.bank_accounts (id, tenant_id, bank_bin, bank_name, account_enc, account_no_masked, account_name, account_fp,
                               is_default, sepay_status, make_default_when_connected)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
        $9, $10, $11)
`

type InsertBankAccountParams struct {
	ID                       string
	TenantID                 string
	BankBin                  string
	BankName                 string
	AccountEnc               []byte
	AccountNoMasked          string
	AccountName              string
	AccountFp                string
	IsDefault                bool
	SepayStatus              string
	MakeDefaultWhenConnected bool
}

func (q *Queries) InsertBankAccount(ctx context.Context, arg InsertBankAccountParams) error {
	_, err := q.db.Exec(ctx, insertBankAccount,
		arg.ID,
		arg.TenantID,
		arg.BankBin,
		arg.BankName,
		arg.AccountEnc,
		arg.AccountNoMasked,
		arg.AccountName,
		arg.AccountFp,
		arg.IsDefault,
		arg.SepayStatus,
		arg.MakeDefaultWhenConnected,
	)
	return err
}

const insertTenant = `-- name: InsertTenant :exec
INSERT INTO app.tenants (id, name, guesthouse_code, hook_id, default_locale, time_zone)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertTenantParams struct {
	ID             string
	Name           string
	GuesthouseCode pgtype.Text
	HookID         pgtype.Text
	DefaultLocale  string
	TimeZone       string
}

func (q *Queries) InsertTenant(ctx context.Context, arg InsertTenantParams) error {
	_, err := q.db.Exec(ctx, insertTenant,
		arg.ID,
		arg.Name,
		arg.GuesthouseCode,
		arg.HookID,
		arg.DefaultLocale,
		arg.TimeZone,
	)
	return err
}

const listBankAccounts = `-- name: ListBankAccounts :many
SELECT id, bank_bin, bank_name, account_no_masked, account_name, is_default, sepay_status, make_default_when_connected, last_webhook_at
FROM app.bank_accounts WHERE tenant_id = $1 ORDER BY is_default DESC, created_at, id
`

type ListBankAccountsRow struct {
	ID                       string
	BankBin                  string
	BankName                 string
	AccountNoMasked          string
	AccountName              string
	IsDefault                bool
	SepayStatus              string
	MakeDefaultWhenConnected bool
	LastWebhookAt            pgtype.Timestamptz
}

func (q *Queries) ListBankAccounts(ctx context.Context, tenantID string) ([]ListBankAccountsRow, error) {
	rows, err := q.db.Query(ctx, listBankAccounts, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBankAccountsRow
	for rows.Next() {
		var i ListBankAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.BankBin,
			&i.BankName,
			&i.AccountNoMasked,
			&i.AccountName,
			&i.IsDefault,
			&i.SepayStatus,
			&i.MakeDefaultWhenConnected,
			&i.LastWebhookAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultBankAccount = `-- name: SetDefaultBankAccount :execrows
UPDATE app.bank_accounts SET is_default = true, make_default_when_connected = false
WHERE tenant_id = $1 AND id = $2 AND sepay_status = 'CONNECTED'
`

type SetDefaultBankAccountParams struct {
	TenantID string
	ID       string
}

func (q *Queries) SetDefaultBankAccount(ctx context.Context, arg SetDefaultBankAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, setDefaultBankAccount, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setSepaySecret = `-- name: SetSepaySecret :exec
UPDATE app.tenants SET sepay_secret_enc = $1, sepay_signature_ok = NULL WHERE id = $2
`

type SetSepaySecretParams struct {
	SepaySecretEnc []byte
	TenantID       string
}

func (q *Queries) SetSepaySecret(ctx context.Context, arg SetSepaySecretParams) error {
	_, err := q.db.Exec(ctx, setSepaySecret, arg.SepaySecretEnc, arg.TenantID)
	return err
}

const setTenantHook = `-- name: SetTenantHook :exec
UPDATE app.tenants SET hook_id = $1 WHERE id = $2 AND hook_id IS NULL
`

type SetTenantHookParams struct {
	HookID   pgtype.Text
	TenantID string
}

func (q *Queries) SetTenantHook(ctx context.Context, arg SetTenantHookParams) error {
	_, err := q.db.Exec(ctx, setTenantHook, arg.HookID, arg.TenantID)
	return err
}

const updateProperty = `-- name: UpdateProperty :exec
UPDATE app.properties
SET name = COALESCE($1, name), address = COALESCE($2, address), phone = COALESCE($3, phone),
    qr_expiry_minutes = COALESCE($4, qr_expiry_minutes),
    id_retention_days = COALESCE($5, id_retention_days),
    front_desk_history_days = COALESCE($6, front_desk_history_days)
WHERE tenant_id = $7 AND id = $8
`

type UpdatePropertyParams struct {
	Name                 pgtype.Text
	Address              pgtype.Text
	Phone                pgtype.Text
	QrExpiryMinutes      pgtype.Int4
	IDRetentionDays      pgtype.Int4
	FrontDeskHistoryDays pgtype.Int4
	TenantID             string
	ID                   string
}

func (q *Queries) UpdateProperty(ctx context.Context, arg UpdatePropertyParams) error {
	_, err := q.db.Exec(ctx, updateProperty,
		arg.Name,
		arg.Address,
		arg.Phone,
		arg.QrExpiryMinutes,
		arg.IDRetentionDays,
		arg.FrontDeskHistoryDays,
		arg.TenantID,
		arg.ID,
	)
	return err
}
