// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const billCodeTaken = `-- name: BillCodeTaken :one
SELECT EXISTS (SELECT 1 FROM app.invoices WHERE tenant_id = $1 AND bill_code = $2)
`

type BillCodeTakenParams struct {
	TenantID string
	BillCode string
}

func (q *Queries) BillCodeTaken(ctx context.Context, arg BillCodeTakenParams) (bool, error) {
	row := q.db.QueryRow(ctx, billCodeTaken, arg.TenantID, arg.BillCode)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getInvoiceByStay = `-- name: GetInvoiceByStay :one
SELECT i.id, i.stay_id, i.bill_code, i.status, app.reconciled_quote(i.quote, i.total, i.status, s.deposit)::jsonb AS quote, i.total, i.created_at, i.paid_at
FROM app.invoices i JOIN app.stays s ON s.tenant_id = i.tenant_id AND s.id = i.stay_id
WHERE i.tenant_id = $1 AND i.stay_id = $2
`

type GetInvoiceByStayParams struct {
	TenantID string
	StayID   string
}

type GetInvoiceByStayRow struct {
	ID        string
	StayID    string
	BillCode  string
	Status    string
	Quote     []byte
	Total     int64
	CreatedAt pgtype.Timestamptz
	PaidAt    pgtype.Timestamptz
}

func (q *Queries) GetInvoiceByStay(ctx context.Context, arg GetInvoiceByStayParams) (GetInvoiceByStayRow, error) {
	row := q.db.QueryRow(ctx, getInvoiceByStay, arg.TenantID, arg.StayID)
	var i GetInvoiceByStayRow
	err := row.Scan(
		&i.ID,
		&i.StayID,
		&i.BillCode,
		&i.Status,
		&i.Quote,
		&i.Total,
		&i.CreatedAt,
		&i.PaidAt,
	)
	return i, err
}

const getStayPendingPayment = `-- name: GetStayPendingPayment :one
SELECT iv.id AS invoice_id, iv.total, iv.created_at,
       st.deposit::bigint AS deposit,
       greatest(st.deposit - iv.total, 0)::bigint AS refund_due,
       coalesce((SELECT sum(pe.amount) FROM app.payment_events pe WHERE pe.tenant_id = iv.tenant_id AND pe.invoice_id = iv.id AND pe.result = 'PARTIAL'), 0)::bigint AS received,
       coalesce((SELECT p.id FROM app.payments p WHERE p.tenant_id = iv.tenant_id AND p.invoice_id = iv.id AND p.method = 'TRANSFER' AND p.status = 'PENDING'
                 ORDER BY p.created_at DESC LIMIT 1), '')::text AS payment_id
FROM app.invoices iv JOIN app.stays st ON st.tenant_id = iv.tenant_id AND st.id = iv.stay_id
WHERE iv.tenant_id = $1 AND iv.stay_id = $2 AND iv.status = 'OPEN'
`

type GetStayPendingPaymentParams struct {
	TenantID string
	StayID   string
}

type GetStayPendingPaymentRow struct {
	InvoiceID string
	Total     int64
	CreatedAt pgtype.Timestamptz
	Deposit   int64
	RefundDue int64
	Received  int64
	PaymentID string
}

// The open invoice of a stay with the money so far: paid is the deposit plus bank money that did not settle it yet.
func (q *Queries) GetStayPendingPayment(ctx context.Context, arg GetStayPendingPaymentParams) (GetStayPendingPaymentRow, error) {
	row := q.db.QueryRow(ctx, getStayPendingPayment, arg.TenantID, arg.StayID)
	var i GetStayPendingPaymentRow
	err := row.Scan(
		&i.InvoiceID,
		&i.Total,
		&i.CreatedAt,
		&i.Deposit,
		&i.RefundDue,
		&i.Received,
		&i.PaymentID,
	)
	return i, err
}

const insertInvoice = `-- name: InsertInvoice :exec
INSERT INTO app.invoices (id, tenant_id, stay_id, bill_code, quote, total, status, created_at)
VALUES ($1, $2, $3, $4, $5, $6, 'OPEN', $7)
`

type InsertInvoiceParams struct {
	ID        string
	TenantID  string
	StayID    string
	BillCode  string
	Quote     []byte
	Total     int64
	CreatedAt pgtype.Timestamptz
}

// status is OPEN and created_at comes from the argument, never from now().
func (q *Queries) InsertInvoice(ctx context.Context, arg InsertInvoiceParams) error {
	_, err := q.db.Exec(ctx, insertInvoice,
		arg.ID,
		arg.TenantID,
		arg.StayID,
		arg.BillCode,
		arg.Quote,
		arg.Total,
		arg.CreatedAt,
	)
	return err
}

const insertStayExtra = `-- name: InsertStayExtra :exec
INSERT INTO app.stay_extras (id, tenant_id, stay_id, service_id, quantity, unit_amount, amount, created_at, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertStayExtraParams struct {
	ID         string
	TenantID   string
	StayID     string
	ServiceID  string
	Quantity   int32
	UnitAmount int64
	Amount     int64
	CreatedAt  pgtype.Timestamptz
	CreatedBy  pgtype.Text
}

// created_at comes from the argument (the server clock of the use case), never from now().
func (q *Queries) InsertStayExtra(ctx context.Context, arg InsertStayExtraParams) error {
	_, err := q.db.Exec(ctx, insertStayExtra,
		arg.ID,
		arg.TenantID,
		arg.StayID,
		arg.ServiceID,
		arg.Quantity,
		arg.UnitAmount,
		arg.Amount,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	return err
}

const lockStayByID = `-- name: LockStayByID :one

SELECT s.id, s.unit_id, u.code AS room_code, u.building_id, s.rental_type, s.status, s.guest_name, s.guest_phone,
       EXISTS (SELECT 1 FROM app.guest_ids g WHERE g.tenant_id = s.tenant_id AND g.stay_id = s.id AND g.number_enc IS NOT NULL) AS has_id_number,
       EXISTS (SELECT 1 FROM app.guest_id_photos gp WHERE gp.tenant_id = s.tenant_id AND gp.stay_id = s.id AND gp.side = 'FRONT') AS has_front_photo,
       EXISTS (SELECT 1 FROM app.guest_id_photos gb WHERE gb.tenant_id = s.tenant_id AND gb.stay_id = s.id AND gb.side = 'BACK') AS has_back_photo,
       s.deposit, s.check_in_at, s.check_out_at, s.rate_plan_snapshot
FROM app.stays s
JOIN app.units u ON u.tenant_id = s.tenant_id AND u.id = s.unit_id
WHERE s.tenant_id = $1 AND s.id = $2
FOR UPDATE OF s
`

type LockStayByIDParams struct {
	TenantID string
	StayID   string
}

type LockStayByIDRow struct {
	ID               string
	UnitID           string
	RoomCode         string
	BuildingID       string
	RentalType       string
	Status           string
	GuestName        string
	GuestPhone       string
	HasIDNumber      bool
	HasFrontPhoto    bool
	HasBackPhoto     bool
	Deposit          int64
	CheckInAt        pgtype.Timestamptz
	CheckOutAt       pgtype.Timestamptz
	RatePlanSnapshot []byte
}

// Every query filters by tenant explicitly; RLS is the second guard (ADR-005).
// Same projection as GetStayByID. FOR UPDATE OF s serializes extras and check-out on one stay.
func (q *Queries) LockStayByID(ctx context.Context, arg LockStayByIDParams) (LockStayByIDRow, error) {
	row := q.db.QueryRow(ctx, lockStayByID, arg.TenantID, arg.StayID)
	var i LockStayByIDRow
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.RoomCode,
		&i.BuildingID,
		&i.RentalType,
		&i.Status,
		&i.GuestName,
		&i.GuestPhone,
		&i.HasIDNumber,
		&i.HasFrontPhoto,
		&i.HasBackPhoto,
		&i.Deposit,
		&i.CheckInAt,
		&i.CheckOutAt,
		&i.RatePlanSnapshot,
	)
	return i, err
}

const markStayCheckedOut = `-- name: MarkStayCheckedOut :execrows
UPDATE app.stays SET status = 'CHECKED_OUT', check_out_at = $1
WHERE tenant_id = $2 AND id = $3 AND status = 'ACTIVE'
`

type MarkStayCheckedOutParams struct {
	At       pgtype.Timestamptz
	TenantID string
	StayID   string
}

func (q *Queries) MarkStayCheckedOut(ctx context.Context, arg MarkStayCheckedOutParams) (int64, error) {
	result, err := q.db.Exec(ctx, markStayCheckedOut, arg.At, arg.TenantID, arg.StayID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
