// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const billCodeTaken = `-- name: BillCodeTaken :one
SELECT EXISTS (SELECT 1 FROM app.invoices WHERE tenant_id = $1 AND bill_code = $2)
`

type BillCodeTakenParams struct {
	TenantID string
	BillCode string
}

func (q *Queries) BillCodeTaken(ctx context.Context, arg BillCodeTakenParams) (bool, error) {
	row := q.db.QueryRow(ctx, billCodeTaken, arg.TenantID, arg.BillCode)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getInvoiceByStay = `-- name: GetInvoiceByStay :one
SELECT id, stay_id, bill_code, status, quote, total, created_at
FROM app.invoices
WHERE tenant_id = $1 AND stay_id = $2
`

type GetInvoiceByStayParams struct {
	TenantID string
	StayID   string
}

type GetInvoiceByStayRow struct {
	ID        string
	StayID    string
	BillCode  string
	Status    string
	Quote     []byte
	Total     int64
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) GetInvoiceByStay(ctx context.Context, arg GetInvoiceByStayParams) (GetInvoiceByStayRow, error) {
	row := q.db.QueryRow(ctx, getInvoiceByStay, arg.TenantID, arg.StayID)
	var i GetInvoiceByStayRow
	err := row.Scan(
		&i.ID,
		&i.StayID,
		&i.BillCode,
		&i.Status,
		&i.Quote,
		&i.Total,
		&i.CreatedAt,
	)
	return i, err
}

const insertInvoice = `-- name: InsertInvoice :exec
INSERT INTO app.invoices (id, tenant_id, stay_id, bill_code, quote, total, status, created_at)
VALUES ($1, $2, $3, $4, $5, $6, 'OPEN', $7)
`

type InsertInvoiceParams struct {
	ID        string
	TenantID  string
	StayID    string
	BillCode  string
	Quote     []byte
	Total     int64
	CreatedAt pgtype.Timestamptz
}

// status is OPEN and created_at comes from the argument, never from now().
func (q *Queries) InsertInvoice(ctx context.Context, arg InsertInvoiceParams) error {
	_, err := q.db.Exec(ctx, insertInvoice,
		arg.ID,
		arg.TenantID,
		arg.StayID,
		arg.BillCode,
		arg.Quote,
		arg.Total,
		arg.CreatedAt,
	)
	return err
}

const insertStayExtra = `-- name: InsertStayExtra :exec
INSERT INTO app.stay_extras (id, tenant_id, stay_id, service_id, quantity, unit_amount, amount, created_at, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertStayExtraParams struct {
	ID         string
	TenantID   string
	StayID     string
	ServiceID  string
	Quantity   int32
	UnitAmount int64
	Amount     int64
	CreatedAt  pgtype.Timestamptz
	CreatedBy  pgtype.Text
}

// created_at comes from the argument (the server clock of the use case), never from now().
func (q *Queries) InsertStayExtra(ctx context.Context, arg InsertStayExtraParams) error {
	_, err := q.db.Exec(ctx, insertStayExtra,
		arg.ID,
		arg.TenantID,
		arg.StayID,
		arg.ServiceID,
		arg.Quantity,
		arg.UnitAmount,
		arg.Amount,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	return err
}

const lockStayByID = `-- name: LockStayByID :one

SELECT s.id, s.unit_id, u.code AS room_code, u.building_id, s.rental_type, s.status, s.guest_name, s.guest_phone,
       EXISTS (SELECT 1 FROM app.guest_ids g WHERE g.tenant_id = s.tenant_id AND g.stay_id = s.id AND g.number_enc IS NOT NULL) AS has_id_number,
       EXISTS (SELECT 1 FROM app.guest_id_photos gp WHERE gp.tenant_id = s.tenant_id AND gp.stay_id = s.id AND gp.side = 'FRONT') AS has_front_photo,
       EXISTS (SELECT 1 FROM app.guest_id_photos gb WHERE gb.tenant_id = s.tenant_id AND gb.stay_id = s.id AND gb.side = 'BACK') AS has_back_photo,
       s.deposit, s.check_in_at, s.check_out_at, s.rate_plan_snapshot
FROM app.stays s
JOIN app.units u ON u.tenant_id = s.tenant_id AND u.id = s.unit_id
WHERE s.tenant_id = $1 AND s.id = $2
FOR UPDATE OF s
`

type LockStayByIDParams struct {
	TenantID string
	StayID   string
}

type LockStayByIDRow struct {
	ID               string
	UnitID           string
	RoomCode         string
	BuildingID       string
	RentalType       string
	Status           string
	GuestName        string
	GuestPhone       string
	HasIDNumber      bool
	HasFrontPhoto    bool
	HasBackPhoto     bool
	Deposit          int64
	CheckInAt        pgtype.Timestamptz
	CheckOutAt       pgtype.Timestamptz
	RatePlanSnapshot []byte
}

// Every query filters by tenant explicitly; RLS is the second guard (ADR-005).
// Same projection as GetStayByID. FOR UPDATE OF s serializes extras and check-out on one stay.
func (q *Queries) LockStayByID(ctx context.Context, arg LockStayByIDParams) (LockStayByIDRow, error) {
	row := q.db.QueryRow(ctx, lockStayByID, arg.TenantID, arg.StayID)
	var i LockStayByIDRow
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.RoomCode,
		&i.BuildingID,
		&i.RentalType,
		&i.Status,
		&i.GuestName,
		&i.GuestPhone,
		&i.HasIDNumber,
		&i.HasFrontPhoto,
		&i.HasBackPhoto,
		&i.Deposit,
		&i.CheckInAt,
		&i.CheckOutAt,
		&i.RatePlanSnapshot,
	)
	return i, err
}

const markStayCheckedOut = `-- name: MarkStayCheckedOut :execrows
UPDATE app.stays SET status = 'CHECKED_OUT', check_out_at = $1
WHERE tenant_id = $2 AND id = $3 AND status = 'ACTIVE'
`

type MarkStayCheckedOutParams struct {
	At       pgtype.Timestamptz
	TenantID string
	StayID   string
}

func (q *Queries) MarkStayCheckedOut(ctx context.Context, arg MarkStayCheckedOutParams) (int64, error) {
	result, err := q.db.Exec(ctx, markStayCheckedOut, arg.At, arg.TenantID, arg.StayID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
