// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: demo_seed.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertBuilding = `-- name: InsertBuilding :exec
INSERT INTO app.buildings (id, tenant_id, property_id, code, name)
VALUES ($1, $2, $3, $4, $5)
`

type InsertBuildingParams struct {
	ID         string
	TenantID   string
	PropertyID string
	Code       string
	Name       string
}

func (q *Queries) InsertBuilding(ctx context.Context, arg InsertBuildingParams) error {
	_, err := q.db.Exec(ctx, insertBuilding,
		arg.ID,
		arg.TenantID,
		arg.PropertyID,
		arg.Code,
		arg.Name,
	)
	return err
}

const insertFloor = `-- name: InsertFloor :exec
INSERT INTO app.floors (id, tenant_id, building_id, level, name) VALUES ($1, $2, $3, $4, $5)
`

type InsertFloorParams struct {
	ID         string
	TenantID   string
	BuildingID string
	Level      int32
	Name       pgtype.Text
}

func (q *Queries) InsertFloor(ctx context.Context, arg InsertFloorParams) error {
	_, err := q.db.Exec(ctx, insertFloor,
		arg.ID,
		arg.TenantID,
		arg.BuildingID,
		arg.Level,
		arg.Name,
	)
	return err
}

const insertProperty = `-- name: InsertProperty :exec

INSERT INTO app.properties (id, tenant_id, name, address, phone) VALUES ($1, $2, $3, $4, $5)
`

type InsertPropertyParams struct {
	ID       string
	TenantID string
	Name     string
	Address  pgtype.Text
	Phone    pgtype.Text
}

// Every query filters by tenant explicitly; RLS is the second guard (ADR-005).
func (q *Queries) InsertProperty(ctx context.Context, arg InsertPropertyParams) error {
	_, err := q.db.Exec(ctx, insertProperty,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Address,
		arg.Phone,
	)
	return err
}

const insertService = `-- name: InsertService :exec
INSERT INTO app.services (id, tenant_id, code, name, price, stock)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertServiceParams struct {
	ID       string
	TenantID string
	Code     string
	Name     []byte
	Price    int64
	Stock    int64
}

func (q *Queries) InsertService(ctx context.Context, arg InsertServiceParams) error {
	_, err := q.db.Exec(ctx, insertService,
		arg.ID,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.Price,
		arg.Stock,
	)
	return err
}

const insertUnit = `-- name: InsertUnit :exec
INSERT INTO app.units (id, tenant_id, building_id, floor_id, unit_type_id, code, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertUnitParams struct {
	ID         string
	TenantID   string
	BuildingID string
	FloorID    string
	UnitTypeID string
	Code       string
	Status     string
}

func (q *Queries) InsertUnit(ctx context.Context, arg InsertUnitParams) error {
	_, err := q.db.Exec(ctx, insertUnit,
		arg.ID,
		arg.TenantID,
		arg.BuildingID,
		arg.FloorID,
		arg.UnitTypeID,
		arg.Code,
		arg.Status,
	)
	return err
}

const insertUnitType = `-- name: InsertUnitType :exec
INSERT INTO app.unit_types (id, tenant_id, code, name, rate_plan, rate_plan_version)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertUnitTypeParams struct {
	ID              string
	TenantID        string
	Code            string
	Name            []byte
	RatePlan        []byte
	RatePlanVersion int32
}

func (q *Queries) InsertUnitType(ctx context.Context, arg InsertUnitTypeParams) error {
	_, err := q.db.Exec(ctx, insertUnitType,
		arg.ID,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.RatePlan,
		arg.RatePlanVersion,
	)
	return err
}
