// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: finance.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const copyRecurringExpenses = `-- name: CopyRecurringExpenses :execrows
INSERT INTO app.expenses (id, tenant_id, month, category, amount, note, recurring, source, ref_id, root_id, attachment_asset_id, created_by)
SELECT 'ex_' || replace(gen_random_uuid()::text, '-', ''), e.tenant_id, $1::text, e.category, e.amount, e.note, true, 'RECURRING',
       coalesce(e.root_id, e.id) || '@' || $1::text, coalesce(e.root_id, e.id), e.attachment_asset_id, e.created_by
FROM app.expenses e
WHERE e.tenant_id = $2 AND e.month = $3 AND e.recurring AND e.source IN ('MANUAL', 'RECURRING')
ON CONFLICT (tenant_id, source, ref_id) WHERE ref_id IS NOT NULL DO NOTHING
`

type CopyRecurringExpensesParams struct {
	ToMonth   string
	TenantID  string
	FromMonth string
}

// The recurring lines of the month before, copied into @to_month; a chain keeps its first line as root.
func (q *Queries) CopyRecurringExpenses(ctx context.Context, arg CopyRecurringExpensesParams) (int64, error) {
	result, err := q.db.Exec(ctx, copyRecurringExpenses, arg.ToMonth, arg.TenantID, arg.FromMonth)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countRooms = `-- name: CountRooms :one
SELECT count(*)::bigint FROM app.units WHERE tenant_id = $1
`

func (q *Queries) CountRooms(ctx context.Context, tenantID string) (int64, error) {
	row := q.db.QueryRow(ctx, countRooms, tenantID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteExpense = `-- name: DeleteExpense :execrows
DELETE FROM app.expenses WHERE tenant_id = $1 AND id = $2 AND source IN ('MANUAL', 'RECURRING')
`

type DeleteExpenseParams struct {
	TenantID  string
	ExpenseID string
}

func (q *Queries) DeleteExpense(ctx context.Context, arg DeleteExpenseParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpense, arg.TenantID, arg.ExpenseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const earliestRecurringMonth = `-- name: EarliestRecurringMonth :one
SELECT coalesce(min(month), '')::text AS month FROM app.expenses WHERE tenant_id = $1 AND recurring
`

func (q *Queries) EarliestRecurringMonth(ctx context.Context, tenantID string) (string, error) {
	row := q.db.QueryRow(ctx, earliestRecurringMonth, tenantID)
	var month string
	err := row.Scan(&month)
	return month, err
}

const expenseSummaryOfMonth = `-- name: ExpenseSummaryOfMonth :many
SELECT category, source, sum(amount)::bigint AS total FROM app.expenses
WHERE tenant_id = $1 AND month = $2 GROUP BY category, source ORDER BY category, source
`

type ExpenseSummaryOfMonthParams struct {
	TenantID string
	Month    string
}

type ExpenseSummaryOfMonthRow struct {
	Category string
	Source   string
	Total    int64
}

func (q *Queries) ExpenseSummaryOfMonth(ctx context.Context, arg ExpenseSummaryOfMonthParams) ([]ExpenseSummaryOfMonthRow, error) {
	rows, err := q.db.Query(ctx, expenseSummaryOfMonth, arg.TenantID, arg.Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpenseSummaryOfMonthRow
	for rows.Next() {
		var i ExpenseSummaryOfMonthRow
		if err := rows.Scan(&i.Category, &i.Source, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expenseTotalsByCategory = `-- name: ExpenseTotalsByCategory :many
SELECT category, sum(amount)::bigint AS total FROM app.expenses
WHERE tenant_id = $1 AND month >= $2 AND month <= $3 GROUP BY category ORDER BY category
`

type ExpenseTotalsByCategoryParams struct {
	TenantID  string
	FromMonth string
	ToMonth   string
}

type ExpenseTotalsByCategoryRow struct {
	Category string
	Total    int64
}

func (q *Queries) ExpenseTotalsByCategory(ctx context.Context, arg ExpenseTotalsByCategoryParams) ([]ExpenseTotalsByCategoryRow, error) {
	rows, err := q.db.Query(ctx, expenseTotalsByCategory, arg.TenantID, arg.FromMonth, arg.ToMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpenseTotalsByCategoryRow
	for rows.Next() {
		var i ExpenseTotalsByCategoryRow
		if err := rows.Scan(&i.Category, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expenseTotalsByMonth = `-- name: ExpenseTotalsByMonth :many
SELECT month, sum(amount)::bigint AS total FROM app.expenses
WHERE tenant_id = $1 AND month >= $2 AND month <= $3 GROUP BY month ORDER BY month
`

type ExpenseTotalsByMonthParams struct {
	TenantID  string
	FromMonth string
	ToMonth   string
}

type ExpenseTotalsByMonthRow struct {
	Month string
	Total int64
}

func (q *Queries) ExpenseTotalsByMonth(ctx context.Context, arg ExpenseTotalsByMonthParams) ([]ExpenseTotalsByMonthRow, error) {
	rows, err := q.db.Query(ctx, expenseTotalsByMonth, arg.TenantID, arg.FromMonth, arg.ToMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpenseTotalsByMonthRow
	for rows.Next() {
		var i ExpenseTotalsByMonthRow
		if err := rows.Scan(&i.Month, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const freezePayrollLine = `-- name: FreezePayrollLine :execrows
INSERT INTO app.payroll_lines (tenant_id, user_id, month, status, frozen, paid_at, paid_by)
VALUES ($1, $2, $3, 'PAID', $4, $5, $6)
ON CONFLICT (tenant_id, user_id, month) DO UPDATE SET status = 'PAID', frozen = excluded.frozen, paid_at = excluded.paid_at, paid_by = excluded.paid_by
WHERE app.payroll_lines.status = 'UNPAID'
`

type FreezePayrollLineParams struct {
	TenantID string
	UserID   string
	Month    string
	Frozen   []byte
	PaidAt   pgtype.Timestamptz
	PaidBy   pgtype.Text
}

func (q *Queries) FreezePayrollLine(ctx context.Context, arg FreezePayrollLineParams) (int64, error) {
	result, err := q.db.Exec(ctx, freezePayrollLine,
		arg.TenantID,
		arg.UserID,
		arg.Month,
		arg.Frozen,
		arg.PaidAt,
		arg.PaidBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getExpense = `-- name: GetExpense :one
SELECT id, month, category, amount, paid_on, note, recurring, source, attachment_asset_id
FROM app.expenses WHERE tenant_id = $1 AND id = $2
`

type GetExpenseParams struct {
	TenantID  string
	ExpenseID string
}

type GetExpenseRow struct {
	ID                string
	Month             string
	Category          string
	Amount            int64
	PaidOn            pgtype.Date
	Note              pgtype.Text
	Recurring         bool
	Source            string
	AttachmentAssetID pgtype.Text
}

func (q *Queries) GetExpense(ctx context.Context, arg GetExpenseParams) (GetExpenseRow, error) {
	row := q.db.QueryRow(ctx, getExpense, arg.TenantID, arg.ExpenseID)
	var i GetExpenseRow
	err := row.Scan(
		&i.ID,
		&i.Month,
		&i.Category,
		&i.Amount,
		&i.PaidOn,
		&i.Note,
		&i.Recurring,
		&i.Source,
		&i.AttachmentAssetID,
	)
	return i, err
}

const insertAutoExpense = `-- name: InsertAutoExpense :execrows
INSERT INTO app.expenses (id, tenant_id, month, category, amount, paid_on, note, recurring, source, ref_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, false, $8, $9, $10)
ON CONFLICT (tenant_id, source, ref_id) WHERE ref_id IS NOT NULL DO NOTHING
`

type InsertAutoExpenseParams struct {
	ID        string
	TenantID  string
	Month     string
	Category  string
	Amount    int64
	PaidOn    pgtype.Date
	Note      pgtype.Text
	Source    string
	RefID     pgtype.Text
	CreatedBy pgtype.Text
}

// One line per source and reference: posting the same payroll line, ticket or stock movement twice changes nothing.
func (q *Queries) InsertAutoExpense(ctx context.Context, arg InsertAutoExpenseParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertAutoExpense,
		arg.ID,
		arg.TenantID,
		arg.Month,
		arg.Category,
		arg.Amount,
		arg.PaidOn,
		arg.Note,
		arg.Source,
		arg.RefID,
		arg.CreatedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertExpense = `-- name: InsertExpense :exec
INSERT INTO app.expenses (id, tenant_id, month, category, amount, paid_on, note, recurring, source, ref_id, root_id, attachment_asset_id, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
        $11, $12, $13)
`

type InsertExpenseParams struct {
	ID                string
	TenantID          string
	Month             string
	Category          string
	Amount            int64
	PaidOn            pgtype.Date
	Note              pgtype.Text
	Recurring         bool
	Source            string
	RefID             pgtype.Text
	RootID            pgtype.Text
	AttachmentAssetID pgtype.Text
	CreatedBy         pgtype.Text
}

func (q *Queries) InsertExpense(ctx context.Context, arg InsertExpenseParams) error {
	_, err := q.db.Exec(ctx, insertExpense,
		arg.ID,
		arg.TenantID,
		arg.Month,
		arg.Category,
		arg.Amount,
		arg.PaidOn,
		arg.Note,
		arg.Recurring,
		arg.Source,
		arg.RefID,
		arg.RootID,
		arg.AttachmentAssetID,
		arg.CreatedBy,
	)
	return err
}

const listExpensesOfMonth = `-- name: ListExpensesOfMonth :many
SELECT id, month, category, amount, paid_on, note, recurring, source, attachment_asset_id
FROM app.expenses WHERE tenant_id = $1 AND month = $2
ORDER BY category, source, created_at, id
`

type ListExpensesOfMonthParams struct {
	TenantID string
	Month    string
}

type ListExpensesOfMonthRow struct {
	ID                string
	Month             string
	Category          string
	Amount            int64
	PaidOn            pgtype.Date
	Note              pgtype.Text
	Recurring         bool
	Source            string
	AttachmentAssetID pgtype.Text
}

func (q *Queries) ListExpensesOfMonth(ctx context.Context, arg ListExpensesOfMonthParams) ([]ListExpensesOfMonthRow, error) {
	rows, err := q.db.Query(ctx, listExpensesOfMonth, arg.TenantID, arg.Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpensesOfMonthRow
	for rows.Next() {
		var i ListExpensesOfMonthRow
		if err := rows.Scan(
			&i.ID,
			&i.Month,
			&i.Category,
			&i.Amount,
			&i.PaidOn,
			&i.Note,
			&i.Recurring,
			&i.Source,
			&i.AttachmentAssetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayrollLines = `-- name: ListPayrollLines :many
SELECT user_id, bonus, deduction, coalesce(note, '') AS note, status, frozen, paid_at FROM app.payroll_lines
WHERE tenant_id = $1 AND month = $2
`

type ListPayrollLinesParams struct {
	TenantID string
	Month    string
}

type ListPayrollLinesRow struct {
	UserID    string
	Bonus     int64
	Deduction int64
	Note      string
	Status    string
	Frozen    []byte
	PaidAt    pgtype.Timestamptz
}

func (q *Queries) ListPayrollLines(ctx context.Context, arg ListPayrollLinesParams) ([]ListPayrollLinesRow, error) {
	rows, err := q.db.Query(ctx, listPayrollLines, arg.TenantID, arg.Month)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPayrollLinesRow
	for rows.Next() {
		var i ListPayrollLinesRow
		if err := rows.Scan(
			&i.UserID,
			&i.Bonus,
			&i.Deduction,
			&i.Note,
			&i.Status,
			&i.Frozen,
			&i.PaidAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPayrollStaff = `-- name: ListPayrollStaff :many
SELECT u.id, u.name, u.status, p.position, p.pay_type, p.rate, p.fixed_allowance, p.standard_shifts
FROM app.staff_profiles p JOIN app.users u ON u.tenant_id = p.tenant_id AND u.id = p.user_id
WHERE p.tenant_id = $1 AND p.start_date <= $2::date
  AND (u.status <> 'REMOVED'
       OR EXISTS (SELECT 1 FROM app.roster_assignments r WHERE r.tenant_id = u.tenant_id AND r.user_id = u.id
                  AND r.work_date >= $3::date AND r.work_date <= $2::date)
       OR EXISTS (SELECT 1 FROM app.payroll_lines l WHERE l.tenant_id = u.tenant_id AND l.user_id = u.id AND l.month = $4))
ORDER BY u.name, u.id
`

type ListPayrollStaffParams struct {
	TenantID   string
	MonthLast  pgtype.Date
	MonthFirst pgtype.Date
	Month      string
}

type ListPayrollStaffRow struct {
	ID             string
	Name           string
	Status         string
	Position       string
	PayType        string
	Rate           int64
	FixedAllowance int64
	StandardShifts int32
}

func (q *Queries) ListPayrollStaff(ctx context.Context, arg ListPayrollStaffParams) ([]ListPayrollStaffRow, error) {
	rows, err := q.db.Query(ctx, listPayrollStaff,
		arg.TenantID,
		arg.MonthLast,
		arg.MonthFirst,
		arg.Month,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPayrollStaffRow
	for rows.Next() {
		var i ListPayrollStaffRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.Position,
			&i.PayType,
			&i.Rate,
			&i.FixedAllowance,
			&i.StandardShifts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPayrollLine = `-- name: LockPayrollLine :one
SELECT status FROM app.payroll_lines WHERE tenant_id = $1 AND user_id = $2 AND month = $3 FOR UPDATE
`

type LockPayrollLineParams struct {
	TenantID string
	UserID   string
	Month    string
}

func (q *Queries) LockPayrollLine(ctx context.Context, arg LockPayrollLineParams) (string, error) {
	row := q.db.QueryRow(ctx, lockPayrollLine, arg.TenantID, arg.UserID, arg.Month)
	var status string
	err := row.Scan(&status)
	return status, err
}

const markRecurringRan = `-- name: MarkRecurringRan :exec
INSERT INTO app.recurring_runs (tenant_id, month) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type MarkRecurringRanParams struct {
	TenantID string
	Month    string
}

func (q *Queries) MarkRecurringRan(ctx context.Context, arg MarkRecurringRanParams) error {
	_, err := q.db.Exec(ctx, markRecurringRan, arg.TenantID, arg.Month)
	return err
}

const occupiedRoomDays = `-- name: OccupiedRoomDays :one
SELECT count(*)::bigint AS days FROM (
    SELECT DISTINCT s.unit_id, d::date AS day
    FROM app.stays s
    CROSS JOIN LATERAL generate_series(
        greatest((s.check_in_at AT TIME ZONE $1::text)::date, $2::date),
        least((coalesce(s.check_out_at, now()) AT TIME ZONE $1::text)::date, $3::date),
        interval '1 day') d
    WHERE s.tenant_id = $4
) x
`

type OccupiedRoomDaysParams struct {
	Zone     string
	FromDay  pgtype.Date
	ToDay    pgtype.Date
	TenantID string
}

// Distinct (room, local day) pairs with a stay in them between two local days, both included.
func (q *Queries) OccupiedRoomDays(ctx context.Context, arg OccupiedRoomDaysParams) (int64, error) {
	row := q.db.QueryRow(ctx, occupiedRoomDays,
		arg.Zone,
		arg.FromDay,
		arg.ToDay,
		arg.TenantID,
	)
	var days int64
	err := row.Scan(&days)
	return days, err
}

const paidInvoiceTotals = `-- name: PaidInvoiceTotals :one
SELECT coalesce(sum(total), 0)::bigint AS revenue FROM app.invoices
WHERE tenant_id = $1 AND status = 'PAID' AND paid_at >= $2 AND paid_at < $3
`

type PaidInvoiceTotalsParams struct {
	TenantID string
	FromAt   pgtype.Timestamptz
	ToAt     pgtype.Timestamptz
}

// Revenue is what paid invoices were for (the frozen quote total), by the day they were paid.
func (q *Queries) PaidInvoiceTotals(ctx context.Context, arg PaidInvoiceTotalsParams) (int64, error) {
	row := q.db.QueryRow(ctx, paidInvoiceTotals, arg.TenantID, arg.FromAt, arg.ToAt)
	var revenue int64
	err := row.Scan(&revenue)
	return revenue, err
}

const recurringRan = `-- name: RecurringRan :one
SELECT count(*) FROM app.recurring_runs WHERE tenant_id = $1 AND month = $2
`

type RecurringRanParams struct {
	TenantID string
	Month    string
}

func (q *Queries) RecurringRan(ctx context.Context, arg RecurringRanParams) (int64, error) {
	row := q.db.QueryRow(ctx, recurringRan, arg.TenantID, arg.Month)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const revenueBalanceByMethod = `-- name: RevenueBalanceByMethod :many
SELECT p.method AS key, sum(coalesce((iv.quote->>'balanceDue')::bigint, 0))::bigint AS revenue
FROM app.invoices iv JOIN app.payments p ON p.tenant_id = iv.tenant_id AND p.invoice_id = iv.id AND p.status = 'PAID'
WHERE iv.tenant_id = $1 AND iv.status = 'PAID' AND iv.paid_at >= $2 AND iv.paid_at < $3 GROUP BY 1 ORDER BY 1
`

type RevenueBalanceByMethodParams struct {
	TenantID string
	FromAt   pgtype.Timestamptz
	ToAt     pgtype.Timestamptz
}

type RevenueBalanceByMethodRow struct {
	Key     string
	Revenue int64
}

// The part paid after the deposit, by the method of the payment that settled the invoice.
func (q *Queries) RevenueBalanceByMethod(ctx context.Context, arg RevenueBalanceByMethodParams) ([]RevenueBalanceByMethodRow, error) {
	rows, err := q.db.Query(ctx, revenueBalanceByMethod, arg.TenantID, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RevenueBalanceByMethodRow
	for rows.Next() {
		var i RevenueBalanceByMethodRow
		if err := rows.Scan(&i.Key, &i.Revenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revenueByBuilding = `-- name: RevenueByBuilding :many
SELECT u.building_id AS key, sum(iv.total)::bigint AS revenue
FROM app.invoices iv JOIN app.stays s ON s.tenant_id = iv.tenant_id AND s.id = iv.stay_id
JOIN app.units u ON u.tenant_id = s.tenant_id AND u.id = s.unit_id
WHERE iv.tenant_id = $1 AND iv.status = 'PAID' AND iv.paid_at >= $2 AND iv.paid_at < $3 GROUP BY 1 ORDER BY 1
`

type RevenueByBuildingParams struct {
	TenantID string
	FromAt   pgtype.Timestamptz
	ToAt     pgtype.Timestamptz
}

type RevenueByBuildingRow struct {
	Key     string
	Revenue int64
}

func (q *Queries) RevenueByBuilding(ctx context.Context, arg RevenueByBuildingParams) ([]RevenueByBuildingRow, error) {
	rows, err := q.db.Query(ctx, revenueByBuilding, arg.TenantID, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RevenueByBuildingRow
	for rows.Next() {
		var i RevenueByBuildingRow
		if err := rows.Scan(&i.Key, &i.Revenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revenueByMonth = `-- name: RevenueByMonth :many
SELECT to_char(paid_at AT TIME ZONE $1::text, 'YYYY-MM') AS month, sum(total)::bigint AS revenue FROM app.invoices
WHERE tenant_id = $2 AND status = 'PAID' AND paid_at >= $3 AND paid_at < $4 GROUP BY 1 ORDER BY 1
`

type RevenueByMonthParams struct {
	Zone     string
	TenantID string
	FromAt   pgtype.Timestamptz
	ToAt     pgtype.Timestamptz
}

type RevenueByMonthRow struct {
	Month   string
	Revenue int64
}

func (q *Queries) RevenueByMonth(ctx context.Context, arg RevenueByMonthParams) ([]RevenueByMonthRow, error) {
	rows, err := q.db.Query(ctx, revenueByMonth,
		arg.Zone,
		arg.TenantID,
		arg.FromAt,
		arg.ToAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RevenueByMonthRow
	for rows.Next() {
		var i RevenueByMonthRow
		if err := rows.Scan(&i.Month, &i.Revenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revenueByRentalType = `-- name: RevenueByRentalType :many
SELECT s.rental_type AS key, sum(iv.total)::bigint AS revenue
FROM app.invoices iv JOIN app.stays s ON s.tenant_id = iv.tenant_id AND s.id = iv.stay_id
WHERE iv.tenant_id = $1 AND iv.status = 'PAID' AND iv.paid_at >= $2 AND iv.paid_at < $3 GROUP BY 1 ORDER BY 1
`

type RevenueByRentalTypeParams struct {
	TenantID string
	FromAt   pgtype.Timestamptz
	ToAt     pgtype.Timestamptz
}

type RevenueByRentalTypeRow struct {
	Key     string
	Revenue int64
}

func (q *Queries) RevenueByRentalType(ctx context.Context, arg RevenueByRentalTypeParams) ([]RevenueByRentalTypeRow, error) {
	rows, err := q.db.Query(ctx, revenueByRentalType, arg.TenantID, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RevenueByRentalTypeRow
	for rows.Next() {
		var i RevenueByRentalTypeRow
		if err := rows.Scan(&i.Key, &i.Revenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revenueDepositPart = `-- name: RevenueDepositPart :one
SELECT coalesce(sum(least(coalesce((quote->>'depositPaid')::bigint, 0), total)), 0)::bigint AS cash
FROM app.invoices WHERE tenant_id = $1 AND status = 'PAID' AND paid_at >= $2 AND paid_at < $3
`

type RevenueDepositPartParams struct {
	TenantID string
	FromAt   pgtype.Timestamptz
	ToAt     pgtype.Timestamptz
}

// The part of paid invoices that the deposit covered (taken in cash at check-in).
func (q *Queries) RevenueDepositPart(ctx context.Context, arg RevenueDepositPartParams) (int64, error) {
	row := q.db.QueryRow(ctx, revenueDepositPart, arg.TenantID, arg.FromAt, arg.ToAt)
	var cash int64
	err := row.Scan(&cash)
	return cash, err
}

const updateExpense = `-- name: UpdateExpense :execrows
UPDATE app.expenses SET month = $1, category = $2, amount = $3, paid_on = $4, note = $5,
       recurring = $6, attachment_asset_id = $7
WHERE tenant_id = $8 AND id = $9 AND source IN ('MANUAL', 'RECURRING')
`

type UpdateExpenseParams struct {
	Month             string
	Category          string
	Amount            int64
	PaidOn            pgtype.Date
	Note              pgtype.Text
	Recurring         bool
	AttachmentAssetID pgtype.Text
	TenantID          string
	ExpenseID         string
}

// Only lines a person wrote can be edited; the system's lines (PAYROLL, MAINTENANCE, STOCK) are not touched.
func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateExpense,
		arg.Month,
		arg.Category,
		arg.Amount,
		arg.PaidOn,
		arg.Note,
		arg.Recurring,
		arg.AttachmentAssetID,
		arg.TenantID,
		arg.ExpenseID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertPayrollLine = `-- name: UpsertPayrollLine :exec
INSERT INTO app.payroll_lines (tenant_id, user_id, month, bonus, deduction, note)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (tenant_id, user_id, month) DO UPDATE SET bonus = excluded.bonus, deduction = excluded.deduction, note = excluded.note
WHERE app.payroll_lines.status = 'UNPAID'
`

type UpsertPayrollLineParams struct {
	TenantID  string
	UserID    string
	Month     string
	Bonus     int64
	Deduction int64
	Note      pgtype.Text
}

func (q *Queries) UpsertPayrollLine(ctx context.Context, arg UpsertPayrollLineParams) error {
	_, err := q.db.Exec(ctx, upsertPayrollLine,
		arg.TenantID,
		arg.UserID,
		arg.Month,
		arg.Bonus,
		arg.Deduction,
		arg.Note,
	)
	return err
}
