// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guest_ids.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearGuestNumber = `-- name: ClearGuestNumber :execrows
UPDATE app.guest_ids SET number_enc = NULL WHERE tenant_id = $1 AND stay_id = $2 AND number_enc IS NOT NULL
`

type ClearGuestNumberParams struct {
	TenantID string
	StayID   string
}

func (q *Queries) ClearGuestNumber(ctx context.Context, arg ClearGuestNumberParams) (int64, error) {
	result, err := q.db.Exec(ctx, clearGuestNumber, arg.TenantID, arg.StayID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteGuestIDRow = `-- name: DeleteGuestIDRow :exec
DELETE FROM app.guest_ids WHERE tenant_id = $1 AND stay_id = $2
`

type DeleteGuestIDRowParams struct {
	TenantID string
	StayID   string
}

func (q *Queries) DeleteGuestIDRow(ctx context.Context, arg DeleteGuestIDRowParams) error {
	_, err := q.db.Exec(ctx, deleteGuestIDRow, arg.TenantID, arg.StayID)
	return err
}

const deleteGuestPhoto = `-- name: DeleteGuestPhoto :execrows
DELETE FROM app.guest_id_photos WHERE tenant_id = $1 AND stay_id = $2 AND side = $3
`

type DeleteGuestPhotoParams struct {
	TenantID string
	StayID   string
	Side     string
}

func (q *Queries) DeleteGuestPhoto(ctx context.Context, arg DeleteGuestPhotoParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGuestPhoto, arg.TenantID, arg.StayID, arg.Side)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteGuestPhotosOfStay = `-- name: DeleteGuestPhotosOfStay :exec
DELETE FROM app.guest_id_photos WHERE tenant_id = $1 AND stay_id = $2
`

type DeleteGuestPhotosOfStayParams struct {
	TenantID string
	StayID   string
}

func (q *Queries) DeleteGuestPhotosOfStay(ctx context.Context, arg DeleteGuestPhotosOfStayParams) error {
	_, err := q.db.Exec(ctx, deleteGuestPhotosOfStay, arg.TenantID, arg.StayID)
	return err
}

const ensureGuestRecord = `-- name: EnsureGuestRecord :exec
INSERT INTO app.guest_ids (tenant_id, stay_id, collected_at, collected_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, stay_id) DO NOTHING
`

type EnsureGuestRecordParams struct {
	TenantID string
	StayID   string
	At       pgtype.Timestamptz
	By       pgtype.Text
}

func (q *Queries) EnsureGuestRecord(ctx context.Context, arg EnsureGuestRecordParams) error {
	_, err := q.db.Exec(ctx, ensureGuestRecord,
		arg.TenantID,
		arg.StayID,
		arg.At,
		arg.By,
	)
	return err
}

const expiredGuestIDStays = `-- name: ExpiredGuestIDStays :many
SELECT g.stay_id FROM app.guest_ids g
JOIN app.stays s ON s.tenant_id = g.tenant_id AND s.id = g.stay_id
WHERE g.tenant_id = $1 AND s.check_out_at IS NOT NULL AND s.check_out_at < $2
ORDER BY g.stay_id
`

type ExpiredGuestIDStaysParams struct {
	TenantID string
	Cutoff   pgtype.Timestamptz
}

// Stays whose guest ID data is past retention: checked out more than N days ago.
func (q *Queries) ExpiredGuestIDStays(ctx context.Context, arg ExpiredGuestIDStaysParams) ([]string, error) {
	rows, err := q.db.Query(ctx, expiredGuestIDStays, arg.TenantID, arg.Cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var stay_id string
		if err := rows.Scan(&stay_id); err != nil {
			return nil, err
		}
		items = append(items, stay_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGuestIDRow = `-- name: GetGuestIDRow :one
SELECT number_enc, collected_at FROM app.guest_ids WHERE tenant_id = $1 AND stay_id = $2
`

type GetGuestIDRowParams struct {
	TenantID string
	StayID   string
}

type GetGuestIDRowRow struct {
	NumberEnc   []byte
	CollectedAt pgtype.Timestamptz
}

func (q *Queries) GetGuestIDRow(ctx context.Context, arg GetGuestIDRowParams) (GetGuestIDRowRow, error) {
	row := q.db.QueryRow(ctx, getGuestIDRow, arg.TenantID, arg.StayID)
	var i GetGuestIDRowRow
	err := row.Scan(&i.NumberEnc, &i.CollectedAt)
	return i, err
}

const getGuestPhotoEnc = `-- name: GetGuestPhotoEnc :one
SELECT image_enc FROM app.guest_id_photos WHERE tenant_id = $1 AND stay_id = $2 AND side = $3
`

type GetGuestPhotoEncParams struct {
	TenantID string
	StayID   string
	Side     string
}

func (q *Queries) GetGuestPhotoEnc(ctx context.Context, arg GetGuestPhotoEncParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getGuestPhotoEnc, arg.TenantID, arg.StayID, arg.Side)
	var image_enc []byte
	err := row.Scan(&image_enc)
	return image_enc, err
}

const guestIDIndicatorsFor = `-- name: GuestIDIndicatorsFor :many
SELECT g.stay_id,
       (g.number_enc IS NOT NULL)::boolean AS has_number,
       EXISTS (SELECT 1 FROM app.guest_id_photos p WHERE p.tenant_id = g.tenant_id AND p.stay_id = g.stay_id AND p.side = 'FRONT') AS has_front,
       EXISTS (SELECT 1 FROM app.guest_id_photos p WHERE p.tenant_id = g.tenant_id AND p.stay_id = g.stay_id AND p.side = 'BACK') AS has_back
FROM app.guest_ids g
WHERE g.tenant_id = $1 AND g.stay_id = ANY($2::text[])
`

type GuestIDIndicatorsForParams struct {
	TenantID string
	StayIds  []string
}

type GuestIDIndicatorsForRow struct {
	StayID    string
	HasNumber bool
	HasFront  bool
	HasBack   bool
}

// Yes/no flags for a page of stays in one read; stays with no guest ID row are simply absent.
func (q *Queries) GuestIDIndicatorsFor(ctx context.Context, arg GuestIDIndicatorsForParams) ([]GuestIDIndicatorsForRow, error) {
	rows, err := q.db.Query(ctx, guestIDIndicatorsFor, arg.TenantID, arg.StayIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GuestIDIndicatorsForRow
	for rows.Next() {
		var i GuestIDIndicatorsForRow
		if err := rows.Scan(
			&i.StayID,
			&i.HasNumber,
			&i.HasFront,
			&i.HasBack,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const guestIDStay = `-- name: GuestIDStay :one

SELECT s.id, s.status, s.check_out_at, u.building_id, u.code AS room_code
FROM app.stays s JOIN app.units u ON u.tenant_id = s.tenant_id AND u.id = s.unit_id
WHERE s.tenant_id = $1 AND s.id = $2
FOR UPDATE OF s
`

type GuestIDStayParams struct {
	TenantID string
	StayID   string
}

type GuestIDStayRow struct {
	ID         string
	Status     string
	CheckOutAt pgtype.Timestamptz
	BuildingID string
	RoomCode   string
}

// Guest ID data (F-A2). Only the guest ID repository runs these; stay queries see yes/no indicators only.
func (q *Queries) GuestIDStay(ctx context.Context, arg GuestIDStayParams) (GuestIDStayRow, error) {
	row := q.db.QueryRow(ctx, guestIDStay, arg.TenantID, arg.StayID)
	var i GuestIDStayRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CheckOutAt,
		&i.BuildingID,
		&i.RoomCode,
	)
	return i, err
}

const idRetentionDays = `-- name: IdRetentionDays :one
SELECT id_retention_days FROM app.properties WHERE tenant_id = $1 ORDER BY created_at, id LIMIT 1
`

func (q *Queries) IdRetentionDays(ctx context.Context, tenantID string) (int32, error) {
	row := q.db.QueryRow(ctx, idRetentionDays, tenantID)
	var id_retention_days int32
	err := row.Scan(&id_retention_days)
	return id_retention_days, err
}

const listGuestPhotoMeta = `-- name: ListGuestPhotoMeta :many
SELECT p.side, p.bytes, p.uploaded_at, COALESCE(u.name, '') AS uploaded_by
FROM app.guest_id_photos p LEFT JOIN app.users u ON u.tenant_id = p.tenant_id AND u.id = p.uploaded_by
WHERE p.tenant_id = $1 AND p.stay_id = $2 ORDER BY p.side
`

type ListGuestPhotoMetaParams struct {
	TenantID string
	StayID   string
}

type ListGuestPhotoMetaRow struct {
	Side       string
	Bytes      int32
	UploadedAt pgtype.Timestamptz
	UploadedBy string
}

func (q *Queries) ListGuestPhotoMeta(ctx context.Context, arg ListGuestPhotoMetaParams) ([]ListGuestPhotoMetaRow, error) {
	rows, err := q.db.Query(ctx, listGuestPhotoMeta, arg.TenantID, arg.StayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGuestPhotoMetaRow
	for rows.Next() {
		var i ListGuestPhotoMetaRow
		if err := rows.Scan(
			&i.Side,
			&i.Bytes,
			&i.UploadedAt,
			&i.UploadedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGuestNumber = `-- name: UpsertGuestNumber :exec
INSERT INTO app.guest_ids (tenant_id, stay_id, number_enc, collected_at, collected_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, stay_id) DO UPDATE SET number_enc = EXCLUDED.number_enc
`

type UpsertGuestNumberParams struct {
	TenantID  string
	StayID    string
	NumberEnc []byte
	At        pgtype.Timestamptz
	By        pgtype.Text
}

func (q *Queries) UpsertGuestNumber(ctx context.Context, arg UpsertGuestNumberParams) error {
	_, err := q.db.Exec(ctx, upsertGuestNumber,
		arg.TenantID,
		arg.StayID,
		arg.NumberEnc,
		arg.At,
		arg.By,
	)
	return err
}

const upsertGuestPhoto = `-- name: UpsertGuestPhoto :exec
INSERT INTO app.guest_id_photos (tenant_id, stay_id, side, image_enc, bytes, uploaded_at, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (tenant_id, stay_id, side) DO UPDATE
SET image_enc = EXCLUDED.image_enc, bytes = EXCLUDED.bytes, uploaded_at = EXCLUDED.uploaded_at, uploaded_by = EXCLUDED.uploaded_by
`

type UpsertGuestPhotoParams struct {
	TenantID   string
	StayID     string
	Side       string
	ImageEnc   []byte
	Bytes      int32
	UploadedAt pgtype.Timestamptz
	UploadedBy pgtype.Text
}

func (q *Queries) UpsertGuestPhoto(ctx context.Context, arg UpsertGuestPhotoParams) error {
	_, err := q.db.Exec(ctx, upsertGuestPhoto,
		arg.TenantID,
		arg.StayID,
		arg.Side,
		arg.ImageEnc,
		arg.Bytes,
		arg.UploadedAt,
		arg.UploadedBy,
	)
	return err
}
