// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: housekeeping.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listToCleanRooms = `-- name: ListToCleanRooms :many

SELECT u.id, u.code, u.building_id,
       COALESCE((SELECT max(s.check_out_at) FROM app.stays s WHERE s.tenant_id = u.tenant_id AND s.unit_id = u.id),
                t.created_at)::timestamptz AS cleaning_since
FROM app.units u
JOIN app.tenants t ON t.id = u.tenant_id
WHERE u.tenant_id = $1 AND u.status = 'TO_CLEAN' AND NOT u.retired
ORDER BY cleaning_since, u.code
`

type ListToCleanRoomsRow struct {
	ID            string
	Code          string
	BuildingID    string
	CleaningSince pgtype.Timestamptz
}

// Every query filters by tenant explicitly; RLS is the second guard (ADR-005).
// A task is a room in TO_CLEAN; its id is the room id. createdAt is the last check-out, or the tenant's creation.
func (q *Queries) ListToCleanRooms(ctx context.Context, tenantID string) ([]ListToCleanRoomsRow, error) {
	rows, err := q.db.Query(ctx, listToCleanRooms, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListToCleanRoomsRow
	for rows.Next() {
		var i ListToCleanRoomsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.BuildingID,
			&i.CleaningSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRoomForClean = `-- name: LockRoomForClean :one
SELECT u.id, u.code, u.building_id, u.status,
       COALESCE((SELECT max(s.check_out_at) FROM app.stays s WHERE s.tenant_id = u.tenant_id AND s.unit_id = u.id),
                t.created_at)::timestamptz AS cleaning_since
FROM app.units u
JOIN app.tenants t ON t.id = u.tenant_id
WHERE u.tenant_id = $1 AND u.id = $2
FOR UPDATE OF u
`

type LockRoomForCleanParams struct {
	TenantID string
	UnitID   string
}

type LockRoomForCleanRow struct {
	ID            string
	Code          string
	BuildingID    string
	Status        string
	CleaningSince pgtype.Timestamptz
}

func (q *Queries) LockRoomForClean(ctx context.Context, arg LockRoomForCleanParams) (LockRoomForCleanRow, error) {
	row := q.db.QueryRow(ctx, lockRoomForClean, arg.TenantID, arg.UnitID)
	var i LockRoomForCleanRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.BuildingID,
		&i.Status,
		&i.CleaningSince,
	)
	return i, err
}

const markRoomClean = `-- name: MarkRoomClean :execrows
UPDATE app.units SET status = 'VACANT'
WHERE tenant_id = $1 AND id = $2 AND status = 'TO_CLEAN'
`

type MarkRoomCleanParams struct {
	TenantID string
	UnitID   string
}

func (q *Queries) MarkRoomClean(ctx context.Context, arg MarkRoomCleanParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRoomClean, arg.TenantID, arg.UnitID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
