// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const beginIdempotencyKey = `-- name: BeginIdempotencyKey :one
INSERT INTO app.idempotency_keys (tenant_id, route, key, request_hash, expires_at)
VALUES ($1, $2, $3, $4, now() + make_interval(secs => $5::float8))
ON CONFLICT (tenant_id, route, key) DO UPDATE
    SET request_hash = EXCLUDED.request_hash, status_code = NULL, response_body = NULL,
        created_at = now(), expires_at = EXCLUDED.expires_at
    WHERE app.idempotency_keys.expires_at <= now()
RETURNING key
`

type BeginIdempotencyKeyParams struct {
	TenantID    string
	Route       string
	Key         string
	RequestHash string
	TtlSeconds  float64
}

// Claims the key, or takes over an expired one. No row back means a live key exists: the caller reads it.
// The insert waits on the primary key while another transaction holds the same key, so only one proceeds.
func (q *Queries) BeginIdempotencyKey(ctx context.Context, arg BeginIdempotencyKeyParams) (string, error) {
	row := q.db.QueryRow(ctx, beginIdempotencyKey,
		arg.TenantID,
		arg.Route,
		arg.Key,
		arg.RequestHash,
		arg.TtlSeconds,
	)
	var key string
	err := row.Scan(&key)
	return key, err
}

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :execrows
UPDATE app.idempotency_keys
SET status_code = $1, response_body = $2
WHERE tenant_id = $3 AND route = $4 AND key = $5
`

type CompleteIdempotencyKeyParams struct {
	StatusCode   pgtype.Int4
	ResponseBody []byte
	TenantID     string
	Route        string
	Key          string
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeIdempotencyKey,
		arg.StatusCode,
		arg.ResponseBody,
		arg.TenantID,
		arg.Route,
		arg.Key,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT request_hash, status_code, response_body
FROM app.idempotency_keys
WHERE tenant_id = $1 AND route = $2 AND key = $3
`

type GetIdempotencyKeyParams struct {
	TenantID string
	Route    string
	Key      string
}

type GetIdempotencyKeyRow struct {
	RequestHash  string
	StatusCode   pgtype.Int4
	ResponseBody []byte
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (GetIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.TenantID, arg.Route, arg.Key)
	var i GetIdempotencyKeyRow
	err := row.Scan(&i.RequestHash, &i.StatusCode, &i.ResponseBody)
	return i, err
}
