// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteOtherUserSessions = `-- name: DeleteOtherUserSessions :exec
DELETE FROM app.sessions WHERE tenant_id = $1 AND user_id = $2 AND token_hash <> $3
`

type DeleteOtherUserSessionsParams struct {
	TenantID string
	UserID   string
	KeepHash string
}

func (q *Queries) DeleteOtherUserSessions(ctx context.Context, arg DeleteOtherUserSessionsParams) error {
	_, err := q.db.Exec(ctx, deleteOtherUserSessions, arg.TenantID, arg.UserID, arg.KeepHash)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM app.sessions WHERE tenant_id = $1 AND token_hash = $2
`

type DeleteSessionParams struct {
	TenantID  string
	TokenHash string
}

func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) error {
	_, err := q.db.Exec(ctx, deleteSession, arg.TenantID, arg.TokenHash)
	return err
}

const getPinState = `-- name: GetPinState :one
SELECT pin_hash, failed_count, first_failed_at, locked_until, must_change, one_time_expires_at
FROM app.pin_credentials WHERE tenant_id = $1 AND user_id = $2
FOR UPDATE
`

type GetPinStateParams struct {
	TenantID string
	UserID   string
}

type GetPinStateRow struct {
	PinHash          string
	FailedCount      int32
	FirstFailedAt    pgtype.Timestamptz
	LockedUntil      pgtype.Timestamptz
	MustChange       bool
	OneTimeExpiresAt pgtype.Timestamptz
}

func (q *Queries) GetPinState(ctx context.Context, arg GetPinStateParams) (GetPinStateRow, error) {
	row := q.db.QueryRow(ctx, getPinState, arg.TenantID, arg.UserID)
	var i GetPinStateRow
	err := row.Scan(
		&i.PinHash,
		&i.FailedCount,
		&i.FirstFailedAt,
		&i.LockedUntil,
		&i.MustChange,
		&i.OneTimeExpiresAt,
	)
	return i, err
}

const getSignInUser = `-- name: GetSignInUser :one
SELECT u.id, u.name, u.role, u.locale, u.app_access, u.status,
       c.pin_hash, c.failed_count, c.first_failed_at, c.locked_until, c.must_change, c.one_time_expires_at
FROM app.users u
JOIN app.pin_credentials c ON c.tenant_id = u.tenant_id AND c.user_id = u.id
WHERE u.tenant_id = $1 AND u.username = $2
`

type GetSignInUserParams struct {
	TenantID string
	Username pgtype.Text
}

type GetSignInUserRow struct {
	ID               string
	Name             string
	Role             string
	Locale           string
	AppAccess        string
	Status           string
	PinHash          string
	FailedCount      int32
	FirstFailedAt    pgtype.Timestamptz
	LockedUntil      pgtype.Timestamptz
	MustChange       bool
	OneTimeExpiresAt pgtype.Timestamptz
}

func (q *Queries) GetSignInUser(ctx context.Context, arg GetSignInUserParams) (GetSignInUserRow, error) {
	row := q.db.QueryRow(ctx, getSignInUser, arg.TenantID, arg.Username)
	var i GetSignInUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.Locale,
		&i.AppAccess,
		&i.Status,
		&i.PinHash,
		&i.FailedCount,
		&i.FirstFailedAt,
		&i.LockedUntil,
		&i.MustChange,
		&i.OneTimeExpiresAt,
	)
	return i, err
}

const getTenantInfo = `-- name: GetTenantInfo :one
SELECT id, name, time_zone, currency FROM app.tenants WHERE id = $1
`

type GetTenantInfoRow struct {
	ID       string
	Name     string
	TimeZone string
	Currency string
}

func (q *Queries) GetTenantInfo(ctx context.Context, tenantID string) (GetTenantInfoRow, error) {
	row := q.db.QueryRow(ctx, getTenantInfo, tenantID)
	var i GetTenantInfoRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TimeZone,
		&i.Currency,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT u.id, u.name, u.role, u.locale,
       (u.status <> 'ACTIVE' OR u.app_access = 'NONE')::boolean AS blocked,
       COALESCE(c.must_change, false)::boolean AS must_change_pin
FROM app.users u
LEFT JOIN app.pin_credentials c ON c.tenant_id = u.tenant_id AND c.user_id = u.id
WHERE u.tenant_id = $1 AND u.id = $2
`

type GetUserByIDParams struct {
	TenantID string
	ID       string
}

type GetUserByIDRow struct {
	ID            string
	Name          string
	Role          string
	Locale        string
	Blocked       bool
	MustChangePin bool
}

func (q *Queries) GetUserByID(ctx context.Context, arg GetUserByIDParams) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, arg.TenantID, arg.ID)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.Locale,
		&i.Blocked,
		&i.MustChangePin,
	)
	return i, err
}

const getUserByRole = `-- name: GetUserByRole :one
SELECT id, name, role, locale FROM app.users
WHERE tenant_id = $1 AND role = $2
ORDER BY created_at, id
LIMIT 1
`

type GetUserByRoleParams struct {
	TenantID string
	Role     string
}

type GetUserByRoleRow struct {
	ID     string
	Name   string
	Role   string
	Locale string
}

func (q *Queries) GetUserByRole(ctx context.Context, arg GetUserByRoleParams) (GetUserByRoleRow, error) {
	row := q.db.QueryRow(ctx, getUserByRole, arg.TenantID, arg.Role)
	var i GetUserByRoleRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.Locale,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO app.sessions (token_hash, tenant_id, user_id, expires_at)
VALUES ($1, $2, $3, $4)
`

type InsertSessionParams struct {
	TokenHash string
	TenantID  string
	UserID    string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.TokenHash,
		arg.TenantID,
		arg.UserID,
		arg.ExpiresAt,
	)
	return err
}

const insertTrialTenant = `-- name: InsertTrialTenant :exec

INSERT INTO app.tenants (id, name, is_trial, expires_at)
VALUES ($1, $2, true, $3)
`

type InsertTrialTenantParams struct {
	ID        string
	Name      string
	ExpiresAt pgtype.Timestamptz
}

// Every query filters by tenant explicitly; RLS is the second guard (ADR-005).
func (q *Queries) InsertTrialTenant(ctx context.Context, arg InsertTrialTenantParams) error {
	_, err := q.db.Exec(ctx, insertTrialTenant, arg.ID, arg.Name, arg.ExpiresAt)
	return err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO app.users (id, tenant_id, name, role, locale, app_access)
VALUES ($1, $2, $3, $4, $5, $4)
RETURNING id, name, role, locale
`

type InsertUserParams struct {
	ID       string
	TenantID string
	Name     string
	Role     string
	Locale   string
}

type InsertUserRow struct {
	ID     string
	Name   string
	Role   string
	Locale string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (InsertUserRow, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Role,
		arg.Locale,
	)
	var i InsertUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.Locale,
	)
	return i, err
}

const listBuildingIDs = `-- name: ListBuildingIDs :many
SELECT id FROM app.buildings WHERE tenant_id = $1 ORDER BY id
`

func (q *Queries) ListBuildingIDs(ctx context.Context, tenantID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listBuildingIDs, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trialTenantActive = `-- name: TrialTenantActive :one
SELECT EXISTS (
    SELECT 1 FROM app.tenants
    WHERE id = $1 AND is_trial AND expires_at > $2
)
`

type TrialTenantActiveParams struct {
	TenantID string
	Now      pgtype.Timestamptz
}

func (q *Queries) TrialTenantActive(ctx context.Context, arg TrialTenantActiveParams) (bool, error) {
	row := q.db.QueryRow(ctx, trialTenantActive, arg.TenantID, arg.Now)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updatePinFailures = `-- name: UpdatePinFailures :exec
UPDATE app.pin_credentials
SET failed_count = $1, first_failed_at = $2, locked_until = $3
WHERE tenant_id = $4 AND user_id = $5
`

type UpdatePinFailuresParams struct {
	FailedCount   int32
	FirstFailedAt pgtype.Timestamptz
	LockedUntil   pgtype.Timestamptz
	TenantID      string
	UserID        string
}

func (q *Queries) UpdatePinFailures(ctx context.Context, arg UpdatePinFailuresParams) error {
	_, err := q.db.Exec(ctx, updatePinFailures,
		arg.FailedCount,
		arg.FirstFailedAt,
		arg.LockedUntil,
		arg.TenantID,
		arg.UserID,
	)
	return err
}

const updatePinHash = `-- name: UpdatePinHash :exec
UPDATE app.pin_credentials SET pin_hash = $1 WHERE tenant_id = $2 AND user_id = $3
`

type UpdatePinHashParams struct {
	PinHash  string
	TenantID string
	UserID   string
}

func (q *Queries) UpdatePinHash(ctx context.Context, arg UpdatePinHashParams) error {
	_, err := q.db.Exec(ctx, updatePinHash, arg.PinHash, arg.TenantID, arg.UserID)
	return err
}

const updateUserLocale = `-- name: UpdateUserLocale :execrows
UPDATE app.users SET locale = $1 WHERE tenant_id = $2 AND id = $3
`

type UpdateUserLocaleParams struct {
	Locale   string
	TenantID string
	ID       string
}

func (q *Queries) UpdateUserLocale(ctx context.Context, arg UpdateUserLocaleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserLocale, arg.Locale, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertPin = `-- name: UpsertPin :exec
INSERT INTO app.pin_credentials (tenant_id, user_id, pin_hash, must_change, one_time_expires_at, changed_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (tenant_id, user_id) DO UPDATE
SET pin_hash = EXCLUDED.pin_hash, must_change = EXCLUDED.must_change,
    one_time_expires_at = EXCLUDED.one_time_expires_at, changed_at = EXCLUDED.changed_at,
    failed_count = 0, first_failed_at = NULL, locked_until = NULL
`

type UpsertPinParams struct {
	TenantID         string
	UserID           string
	PinHash          string
	MustChange       bool
	OneTimeExpiresAt pgtype.Timestamptz
	Now              pgtype.Timestamptz
}

func (q *Queries) UpsertPin(ctx context.Context, arg UpsertPinParams) error {
	_, err := q.db.Exec(ctx, upsertPin,
		arg.TenantID,
		arg.UserID,
		arg.PinHash,
		arg.MustChange,
		arg.OneTimeExpiresAt,
		arg.Now,
	)
	return err
}
