// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppAlert struct {
	ID        string
	TenantID  string
	Kind      string
	RoomCode  pgtype.Text
	ShiftID   pgtype.Text
	StayID    pgtype.Text
	ActorID   pgtype.Text
	Amount    pgtype.Int8
	Details   []byte
	CreatedAt pgtype.Timestamptz
	ReadAt    pgtype.Timestamptz
	ReadBy    pgtype.Text
}

type AppAuditLog struct {
	ID         string
	TenantID   string
	ActorID    pgtype.Text
	Action     string
	EntityType string
	EntityID   string
	Before     []byte
	After      []byte
	TraceID    pgtype.Text
	CreatedAt  pgtype.Timestamptz
}

type AppBankAccount struct {
	ID                       string
	TenantID                 string
	BankBin                  string
	BankName                 string
	AccountEnc               []byte
	AccountNoMasked          string
	AccountName              string
	AccountFp                string
	IsDefault                bool
	SepayStatus              string
	MakeDefaultWhenConnected bool
	LastWebhookAt            pgtype.Timestamptz
	CreatedAt                pgtype.Timestamptz
}

type AppBuilding struct {
	ID         string
	TenantID   string
	PropertyID string
	Code       string
	Name       string
}

type AppBuildingPermission struct {
	TenantID   string
	UserID     string
	BuildingID string
	Level      string
	UpdatedAt  pgtype.Timestamptz
}

type AppCashEntry struct {
	ID          string
	TenantID    string
	ShiftID     string
	Kind        string
	Amount      int64
	StayID      pgtype.Text
	PaymentID   pgtype.Text
	Description pgtype.Text
	CreatedBy   pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

type AppExpense struct {
	ID                string
	TenantID          string
	Month             string
	Category          string
	Amount            int64
	PaidOn            pgtype.Date
	Note              pgtype.Text
	Recurring         bool
	Source            string
	RefID             pgtype.Text
	RootID            pgtype.Text
	AttachmentAssetID pgtype.Text
	CreatedBy         pgtype.Text
	CreatedAt         pgtype.Timestamptz
}

type AppFloor struct {
	ID         string
	TenantID   string
	BuildingID string
	Level      int32
	Name       pgtype.Text
}

type AppGuestID struct {
	TenantID    string
	StayID      string
	NumberEnc   []byte
	CollectedAt pgtype.Timestamptz
	CollectedBy pgtype.Text
	CreatedAt   pgtype.Timestamptz
	LegalBasis  string
}

type AppGuestIDPhoto struct {
	TenantID   string
	StayID     string
	Side       string
	ImageEnc   []byte
	Bytes      int32
	UploadedAt pgtype.Timestamptz
	UploadedBy pgtype.Text
}

type AppIdempotencyKey struct {
	TenantID     string
	Route        string
	Key          string
	RequestHash  string
	StatusCode   pgtype.Int4
	ResponseBody []byte
	CreatedAt    pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
}

type AppInvoice struct {
	ID        string
	TenantID  string
	StayID    string
	BillCode  string
	Quote     []byte
	Total     int64
	Status    string
	CreatedAt pgtype.Timestamptz
	PaidAt    pgtype.Timestamptz
}

type AppLeaveRequest struct {
	ID            string
	TenantID      string
	UserID        string
	FromDate      pgtype.Date
	ToDate        pgtype.Date
	Shift         pgtype.Text
	Kind          string
	Reason        pgtype.Text
	CoverUserID   pgtype.Text
	Status        string
	DeclineReason pgtype.Text
	CreatedAt     pgtype.Timestamptz
	DecidedAt     pgtype.Timestamptz
	DecidedBy     pgtype.Text
}

type AppMaintenanceTicket struct {
	ID             string
	TenantID       string
	Code           string
	UnitID         string
	Category       string
	Description    string
	Status         string
	RoomLocked     bool
	ReportedBy     pgtype.Text
	ReportedAt     pgtype.Timestamptz
	ExpectedDoneOn pgtype.Date
	PartsCost      pgtype.Int8
	LabourCost     pgtype.Int8
	Repairer       pgtype.Text
	Note           pgtype.Text
	CompletedAt    pgtype.Timestamptz
	CompletedBy    pgtype.Text
}

type AppPayment struct {
	ID             string
	TenantID       string
	InvoiceID      string
	Method         string
	Status         string
	Amount         int64
	ReferenceCode  pgtype.Text
	CreatedAt      pgtype.Timestamptz
	PaidAt         pgtype.Timestamptz
	ReceivedAmount pgtype.Int8
	TransactionID  pgtype.Text
}

type AppPaymentEvent struct {
	ID            string
	TenantID      pgtype.Text
	Provider      string
	ExternalID    string
	Amount        int64
	ReferenceCode pgtype.Text
	Result        string
	ReceivedAt    pgtype.Timestamptz
	InvoiceID     pgtype.Text
}

type AppPayrollLine struct {
	TenantID  string
	UserID    string
	Month     string
	Bonus     int64
	Deduction int64
	Note      pgtype.Text
	Status    string
	Frozen    []byte
	PaidAt    pgtype.Timestamptz
	PaidBy    pgtype.Text
}

type AppPinCredential struct {
	TenantID         string
	UserID           string
	PinHash          string
	FailedCount      int32
	FirstFailedAt    pgtype.Timestamptz
	LockedUntil      pgtype.Timestamptz
	MustChange       bool
	OneTimeExpiresAt pgtype.Timestamptz
	ChangedAt        pgtype.Timestamptz
}

type AppProperty struct {
	ID                   string
	TenantID             string
	Name                 string
	Vertical             string
	CreatedAt            pgtype.Timestamptz
	Address              pgtype.Text
	Phone                pgtype.Text
	QrExpiryMinutes      int32
	IDRetentionDays      int32
	FrontDeskHistoryDays int32
}

type AppRecurringRun struct {
	TenantID string
	Month    string
	RanAt    pgtype.Timestamptz
}

type AppRosterAssignment struct {
	TenantID  string
	UserID    string
	WorkDate  pgtype.Date
	Shift     string
	CreatedBy pgtype.Text
	CreatedAt pgtype.Timestamptz
}

type AppService struct {
	ID             string
	TenantID       string
	Name           []byte
	Price          int64
	Stock          int64
	Code           string
	Unit           string
	LowStockAt     int32
	OnSale         bool
	LatestUnitCost pgtype.Int8
}

type AppSession struct {
	TokenHash string
	TenantID  string
	UserID    string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type AppShift struct {
	ID               string
	TenantID         string
	UserID           string
	Status           string
	ShiftCode        string
	OpenedAt         pgtype.Timestamptz
	ClosedAt         pgtype.Timestamptz
	OpeningFloat     int64
	ExpectedCash     pgtype.Int8
	CountedCash      pgtype.Int8
	Difference       pgtype.Int8
	Reason           pgtype.Text
	ReasonRecordedAt pgtype.Timestamptz
	FloatLeft        pgtype.Int8
	HandoverToUserID pgtype.Text
	Counts           []byte
}

type AppStaffProfile struct {
	TenantID        string
	UserID          string
	Phone           pgtype.Text
	Position        string
	PayType         string
	Rate            int64
	FixedAllowance  int64
	StandardShifts  int32
	StartDate       pgtype.Date
	AnnualLeaveDays int32
	CreatedAt       pgtype.Timestamptz
}

type AppStay struct {
	ID               string
	TenantID         string
	UnitID           string
	RentalType       string
	Status           string
	Deposit          int64
	CheckInAt        pgtype.Timestamptz
	CheckOutAt       pgtype.Timestamptz
	RatePlanSnapshot []byte
	BillingMode      string
	GuestName        string
	GuestPhone       string
	RatePlanSchema   int16
	CreatedBy        pgtype.Text
}

type AppStayEdit struct {
	ID           string
	TenantID     string
	StayID       string
	Kind         string
	ActorID      pgtype.Text
	OldCheckInAt pgtype.Timestamptz
	NewCheckInAt pgtype.Timestamptz
	ReasonCode   pgtype.Text
	Note         pgtype.Text
	FromRoomCode pgtype.Text
	ToRoomCode   pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

type AppStayExtra struct {
	ID         string
	TenantID   string
	StayID     string
	ServiceID  string
	Quantity   int32
	UnitAmount int64
	Amount     int64
	CreatedAt  pgtype.Timestamptz
	CreatedBy  pgtype.Text
}

type AppStockMovement struct {
	ID        string
	TenantID  string
	ServiceID string
	Kind      string
	Quantity  int32
	UnitCost  pgtype.Int8
	Ref       pgtype.Text
	ActorID   pgtype.Text
	CreatedAt pgtype.Timestamptz
}

type AppStocktake struct {
	ID              string
	TenantID        string
	ActorID         pgtype.Text
	Note            pgtype.Text
	ValueDifference int64
	CreatedAt       pgtype.Timestamptz
}

type AppTenant struct {
	ID               string
	Name             string
	DefaultLocale    string
	Currency         string
	TimeZone         string
	IsTrial          bool
	ExpiresAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	GuesthouseCode   pgtype.Text
	HookID           pgtype.Text
	SepaySecretEnc   []byte
	SepaySignatureOk pgtype.Bool
	TicketSeq        int32
}

type AppTransaction struct {
	TenantID       string
	ID             string
	HappenedAt     pgtype.Timestamptz
	Amount         int64
	Method         string
	RoomCode       string
	BillCode       string
	Reconciliation string
	TransferNote   string
	PaymentEventID string
	ShiftID        string
}

type AppUnit struct {
	ID         string
	TenantID   string
	BuildingID string
	FloorID    string
	UnitTypeID string
	Code       string
	Status     string
	Attributes []byte
	Retired    bool
}

type AppUnitType struct {
	ID              string
	TenantID        string
	Name            []byte
	RatePlan        []byte
	RatePlanVersion int32
	Code            string
	UpdatedAt       pgtype.Timestamptz
}

type AppUser struct {
	ID        string
	TenantID  string
	Name      string
	Role      string
	CreatedAt pgtype.Timestamptz
	Locale    string
	AppAccess string
	Status    string
	Username  pgtype.Text
}
