// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppAuditLog struct {
	ID         string
	TenantID   string
	ActorID    pgtype.Text
	Action     string
	EntityType string
	EntityID   string
	Before     []byte
	After      []byte
	TraceID    pgtype.Text
	CreatedAt  pgtype.Timestamptz
}

type AppBuilding struct {
	ID         string
	TenantID   string
	PropertyID string
	Code       string
	Name       string
}

type AppFloor struct {
	ID         string
	TenantID   string
	BuildingID string
	Level      int32
}

type AppIdempotencyKey struct {
	TenantID     string
	Route        string
	Key          string
	RequestHash  string
	StatusCode   pgtype.Int4
	ResponseBody []byte
	CreatedAt    pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
}

type AppInvoice struct {
	ID        string
	TenantID  string
	StayID    string
	BillCode  string
	Quote     []byte
	Total     int64
	Status    string
	CreatedAt pgtype.Timestamptz
	PaidAt    pgtype.Timestamptz
}

type AppPayment struct {
	ID            string
	TenantID      string
	InvoiceID     string
	Method        string
	Status        string
	Amount        int64
	ReferenceCode pgtype.Text
	CreatedAt     pgtype.Timestamptz
	PaidAt        pgtype.Timestamptz
}

type AppPaymentEvent struct {
	ID            string
	TenantID      pgtype.Text
	Provider      string
	ExternalID    string
	Amount        int64
	ReferenceCode pgtype.Text
	Result        string
	ReceivedAt    pgtype.Timestamptz
}

type AppProperty struct {
	ID        string
	TenantID  string
	Name      string
	Vertical  string
	CreatedAt pgtype.Timestamptz
}

type AppService struct {
	ID       string
	TenantID string
	Name     []byte
	Price    int64
	Stock    int64
	Code     string
}

type AppSession struct {
	TokenHash string
	TenantID  string
	UserID    string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type AppStay struct {
	ID               string
	TenantID         string
	UnitID           string
	RentalType       string
	Status           string
	Deposit          int64
	CheckInAt        pgtype.Timestamptz
	CheckOutAt       pgtype.Timestamptz
	RatePlanSnapshot []byte
	IDNumberEnc      []byte
	BillingMode      string
	GuestName        string
	GuestPhone       string
	RatePlanSchema   int16
}

type AppStayExtra struct {
	ID         string
	TenantID   string
	StayID     string
	ServiceID  string
	Quantity   int32
	UnitAmount int64
	Amount     int64
	CreatedAt  pgtype.Timestamptz
}

type AppTenant struct {
	ID             string
	Name           string
	DefaultLocale  string
	Currency       string
	TimeZone       string
	IsTrial        bool
	ExpiresAt      pgtype.Timestamptz
	BankAccountEnc []byte
	CreatedAt      pgtype.Timestamptz
}

type AppUnit struct {
	ID         string
	TenantID   string
	BuildingID string
	FloorID    string
	UnitTypeID string
	Code       string
	Status     string
	Attributes []byte
}

type AppUnitType struct {
	ID              string
	TenantID        string
	Name            []byte
	RatePlan        []byte
	RatePlanVersion int32
	Code            string
}

type AppUser struct {
	ID        string
	TenantID  string
	Name      string
	Role      string
	CreatedAt pgtype.Timestamptz
	Locale    string
}
