// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: monitor.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listAlerts = `-- name: ListAlerts :many
SELECT a.id, a.kind, coalesce(a.room_code, '') AS room_code, coalesce(a.shift_id, '') AS shift_id, coalesce(a.stay_id, '') AS stay_id,
       coalesce(u.name, '') AS actor_name, a.amount, a.details, a.created_at
FROM app.alerts a
LEFT JOIN app.users u ON u.tenant_id = a.tenant_id AND u.id = a.actor_id
WHERE a.tenant_id = $1
  AND (NOT $2::boolean OR a.read_at IS NULL)
  AND ($3::text IS NULL OR a.kind = $3::text)
  AND ($4::timestamptz IS NULL OR (a.created_at, a.id) < ($4::timestamptz, $5::text))
ORDER BY a.created_at DESC, a.id DESC
LIMIT $6
`

type ListAlertsParams struct {
	TenantID   string
	UnreadOnly bool
	Kind       pgtype.Text
	CursorAt   pgtype.Timestamptz
	CursorID   pgtype.Text
	RowLimit   int32
}

type ListAlertsRow struct {
	ID        string
	Kind      string
	RoomCode  string
	ShiftID   string
	StayID    string
	ActorName string
	Amount    pgtype.Int8
	Details   []byte
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) ListAlerts(ctx context.Context, arg ListAlertsParams) ([]ListAlertsRow, error) {
	rows, err := q.db.Query(ctx, listAlerts,
		arg.TenantID,
		arg.UnreadOnly,
		arg.Kind,
		arg.CursorAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlertsRow
	for rows.Next() {
		var i ListAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.RoomCode,
			&i.ShiftID,
			&i.StayID,
			&i.ActorName,
			&i.Amount,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT a.id, a.created_at, coalesce(u.name, '') AS actor_name, coalesce(u.role, '') AS actor_role, a.action, a.after
FROM app.audit_logs a
LEFT JOIN app.users u ON u.tenant_id = a.tenant_id AND u.id = a.actor_id
WHERE a.tenant_id = $1 AND a.created_at >= $2 AND a.created_at < $3
  AND ($4::text IS NULL OR a.actor_id = $4::text)
  AND (cardinality($5::text[]) = 0 OR a.action LIKE ANY($5::text[]))
  AND ($6::text IS NULL OR a.action ILIKE $6::text ESCAPE '\'
       OR a.entity_id ILIKE $6::text ESCAPE '\' OR u.name ILIKE $6::text ESCAPE '\')
  AND ($7::timestamptz IS NULL OR (a.created_at, a.id) < ($7::timestamptz, $8::text))
ORDER BY a.created_at DESC, a.id DESC
LIMIT $9
`

type ListAuditLogsParams struct {
	TenantID string
	FromAt   pgtype.Timestamptz
	ToAt     pgtype.Timestamptz
	ActorID  pgtype.Text
	Prefixes []string
	Pattern  pgtype.Text
	CursorAt pgtype.Timestamptz
	CursorID pgtype.Text
	RowLimit int32
}

type ListAuditLogsRow struct {
	ID        string
	CreatedAt pgtype.Timestamptz
	ActorName string
	ActorRole string
	Action    string
	After     []byte
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.TenantID,
		arg.FromAt,
		arg.ToAt,
		arg.ActorID,
		arg.Prefixes,
		arg.Pattern,
		arg.CursorAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditLogsRow
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.ActorName,
			&i.ActorRole,
			&i.Action,
			&i.After,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLongToClean = `-- name: ListLongToClean :many
SELECT u.code AS room_code, max(s.check_out_at)::timestamptz AS since
FROM app.units u
JOIN app.stays s ON s.tenant_id = u.tenant_id AND s.unit_id = u.id AND s.check_out_at IS NOT NULL
WHERE u.tenant_id = $1 AND u.status = 'TO_CLEAN' AND NOT u.retired
GROUP BY u.code
HAVING max(s.check_out_at) < $2
ORDER BY since, u.code
`

type ListLongToCleanParams struct {
	TenantID string
	Before   pgtype.Timestamptz
}

type ListLongToCleanRow struct {
	RoomCode string
	Since    pgtype.Timestamptz
}

// Rooms waiting to be cleaned since before the cutoff (last check-out time).
func (q *Queries) ListLongToClean(ctx context.Context, arg ListLongToCleanParams) ([]ListLongToCleanRow, error) {
	rows, err := q.db.Query(ctx, listLongToClean, arg.TenantID, arg.Before)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLongToCleanRow
	for rows.Next() {
		var i ListLongToCleanRow
		if err := rows.Scan(&i.RoomCode, &i.Since); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
SELECT t.id, t.happened_at, t.amount, t.method, t.room_code, t.bill_code, t.reconciliation, t.transfer_note,
       t.payment_event_id, t.shift_id
FROM app.transactions t
WHERE t.tenant_id = $1 AND t.happened_at >= $2 AND t.happened_at < $3
  AND ($4::text = 'ALL' OR ($4::text = 'NEEDS_ACTION' AND t.reconciliation IN ('MISMATCH', 'UNMATCHED')) OR t.method = $4::text)
  AND ($5::text IS NULL OR t.room_code ILIKE $5::text ESCAPE '\'
       OR t.bill_code ILIKE $5::text ESCAPE '\' OR t.transfer_note ILIKE $5::text ESCAPE '\')
  AND ($6::timestamptz IS NULL OR (t.happened_at, t.id) < ($6::timestamptz, $7::text))
ORDER BY t.happened_at DESC, t.id DESC
LIMIT $8
`

type ListTransactionsParams struct {
	TenantID string
	FromAt   pgtype.Timestamptz
	ToAt     pgtype.Timestamptz
	Kind     string
	Pattern  pgtype.Text
	CursorAt pgtype.Timestamptz
	CursorID pgtype.Text
	RowLimit int32
}

type ListTransactionsRow struct {
	ID             string
	HappenedAt     pgtype.Timestamptz
	Amount         int64
	Method         string
	RoomCode       string
	BillCode       string
	Reconciliation string
	TransferNote   string
	PaymentEventID string
	ShiftID        string
}

// Reads the app.transactions view (migration 0015): paid cash and transfers, transfers with a wrong amount (MISMATCH)
// and bank events nobody matched (UNMATCHED). The view runs with the caller's rights, so row-level security applies.
func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listTransactions,
		arg.TenantID,
		arg.FromAt,
		arg.ToAt,
		arg.Kind,
		arg.Pattern,
		arg.CursorAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsRow
	for rows.Next() {
		var i ListTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.HappenedAt,
			&i.Amount,
			&i.Method,
			&i.RoomCode,
			&i.BillCode,
			&i.Reconciliation,
			&i.TransferNote,
			&i.PaymentEventID,
			&i.ShiftID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPaymentEvent = `-- name: LockPaymentEvent :one
SELECT id, provider, external_id, amount, coalesce(reference_code, '') AS content, result, received_at
FROM app.payment_events
WHERE tenant_id = $1 AND id = $2
FOR UPDATE
`

type LockPaymentEventParams struct {
	TenantID pgtype.Text
	EventID  string
}

type LockPaymentEventRow struct {
	ID         string
	Provider   string
	ExternalID string
	Amount     int64
	Content    string
	Result     string
	ReceivedAt pgtype.Timestamptz
}

func (q *Queries) LockPaymentEvent(ctx context.Context, arg LockPaymentEventParams) (LockPaymentEventRow, error) {
	row := q.db.QueryRow(ctx, lockPaymentEvent, arg.TenantID, arg.EventID)
	var i LockPaymentEventRow
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ExternalID,
		&i.Amount,
		&i.Content,
		&i.Result,
		&i.ReceivedAt,
	)
	return i, err
}

const markAlertRead = `-- name: MarkAlertRead :execrows
UPDATE app.alerts SET read_at = coalesce(read_at, $1), read_by = coalesce(read_by, $2)
WHERE tenant_id = $3 AND id = $4
`

type MarkAlertReadParams struct {
	ReadAt   pgtype.Timestamptz
	ReadBy   pgtype.Text
	TenantID string
	AlertID  string
}

// An alert already read stays as it was: the first reader and time are kept, and the call still succeeds.
func (q *Queries) MarkAlertRead(ctx context.Context, arg MarkAlertReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markAlertRead,
		arg.ReadAt,
		arg.ReadBy,
		arg.TenantID,
		arg.AlertID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
