// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: monitor.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadAlerts = `-- name: CountUnreadAlerts :one
SELECT count(*)::bigint FROM app.alerts WHERE tenant_id = $1 AND read_at IS NULL AND resolved_at IS NULL
`

// Alerts nobody read and that still need the owner (not resolved): the overview's badge. Not limited like the overview list.
func (q *Queries) CountUnreadAlerts(ctx context.Context, tenantID string) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadAlerts, tenantID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const listAlerts = `-- name: ListAlerts :many
SELECT a.id, a.kind, coalesce(a.room_code, '') AS room_code, coalesce(a.shift_id, '') AS shift_id, coalesce(a.stay_id, '') AS stay_id,
       coalesce(u.name, '') AS actor_name, a.amount, a.details, a.created_at, a.resolved_at, a.resolution,
       a.read_at, coalesce(ru.name, '') AS read_by_name
FROM app.alerts a
LEFT JOIN app.users u ON u.tenant_id = a.tenant_id AND u.id = a.actor_id
LEFT JOIN app.users ru ON ru.tenant_id = a.tenant_id AND ru.id = a.read_by
WHERE a.tenant_id = $1
  AND (NOT $2::boolean OR a.read_at IS NULL)
  AND (NOT $3::boolean OR a.resolved_at IS NULL)
  AND ($4::text IS NULL OR a.kind = $4::text)
  AND ($5::timestamptz IS NULL OR (a.created_at, a.id) < ($5::timestamptz, $6::text))
ORDER BY a.created_at DESC, a.id DESC
LIMIT $7
`

type ListAlertsParams struct {
	TenantID       string
	UnreadOnly     bool
	UnresolvedOnly bool
	Kind           pgtype.Text
	CursorAt       pgtype.Timestamptz
	CursorID       pgtype.Text
	RowLimit       int32
}

type ListAlertsRow struct {
	ID         string
	Kind       string
	RoomCode   string
	ShiftID    string
	StayID     string
	ActorName  string
	Amount     pgtype.Int8
	Details    []byte
	CreatedAt  pgtype.Timestamptz
	ResolvedAt pgtype.Timestamptz
	Resolution pgtype.Text
	ReadAt     pgtype.Timestamptz
	ReadByName string
}

func (q *Queries) ListAlerts(ctx context.Context, arg ListAlertsParams) ([]ListAlertsRow, error) {
	rows, err := q.db.Query(ctx, listAlerts,
		arg.TenantID,
		arg.UnreadOnly,
		arg.UnresolvedOnly,
		arg.Kind,
		arg.CursorAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAlertsRow
	for rows.Next() {
		var i ListAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.RoomCode,
			&i.ShiftID,
			&i.StayID,
			&i.ActorName,
			&i.Amount,
			&i.Details,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.Resolution,
			&i.ReadAt,
			&i.ReadByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT a.id, a.created_at, coalesce(u.name, '') AS actor_name, coalesce(u.role, '') AS actor_role, a.action, a.after,
       coalesce(ru.code, '')::text AS room_code, coalesce(inv.bill_code, '')::text AS bill_code
FROM app.audit_logs a
LEFT JOIN app.users u ON u.tenant_id = a.tenant_id AND u.id = a.actor_id
LEFT JOIN app.payments pm ON pm.tenant_id = a.tenant_id AND a.entity_type = 'payment' AND pm.id = a.entity_id
LEFT JOIN app.invoices inv ON inv.tenant_id = a.tenant_id
     AND ((a.entity_type = 'invoice' AND inv.id = a.entity_id) OR (a.entity_type = 'payment' AND inv.id = pm.invoice_id)
          OR (a.entity_type = 'stay' AND inv.stay_id = a.entity_id))
LEFT JOIN app.stays st ON st.tenant_id = a.tenant_id AND st.id = CASE WHEN a.entity_type = 'stay' THEN a.entity_id ELSE inv.stay_id END
LEFT JOIN app.units ru ON ru.tenant_id = a.tenant_id AND ru.id = CASE WHEN a.entity_type = 'room' THEN a.entity_id ELSE st.unit_id END
WHERE a.tenant_id = $1 AND a.created_at >= $2 AND a.created_at < $3
  AND ($4::text IS NULL OR a.actor_id = $4::text)
  AND (cardinality($5::text[]) = 0 OR a.action LIKE ANY($5::text[]))
  AND ($6::text IS NULL OR a.action ILIKE $6::text ESCAPE '\'
       OR a.entity_id ILIKE $6::text ESCAPE '\' OR u.name ILIKE $6::text ESCAPE '\')
  AND ($7::timestamptz IS NULL OR (a.created_at, a.id) < ($7::timestamptz, $8::text))
ORDER BY a.created_at DESC, a.id DESC
LIMIT $9
`

type ListAuditLogsParams struct {
	TenantID string
	FromAt   pgtype.Timestamptz
	ToAt     pgtype.Timestamptz
	ActorID  pgtype.Text
	Prefixes []string
	Pattern  pgtype.Text
	CursorAt pgtype.Timestamptz
	CursorID pgtype.Text
	RowLimit int32
}

type ListAuditLogsRow struct {
	ID        string
	CreatedAt pgtype.Timestamptz
	ActorName string
	ActorRole string
	Action    string
	After     []byte
	RoomCode  string
	BillCode  string
}

// room_code and bill_code are resolved here from entity_type and entity_id (stay, invoice, payment, room), so rows
// written before the documents carried them are filled too.
func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]ListAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.TenantID,
		arg.FromAt,
		arg.ToAt,
		arg.ActorID,
		arg.Prefixes,
		arg.Pattern,
		arg.CursorAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditLogsRow
	for rows.Next() {
		var i ListAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.ActorName,
			&i.ActorRole,
			&i.Action,
			&i.After,
			&i.RoomCode,
			&i.BillCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLongToClean = `-- name: ListLongToClean :many
SELECT u.code AS room_code, max(s.check_out_at)::timestamptz AS since
FROM app.units u
JOIN app.stays s ON s.tenant_id = u.tenant_id AND s.unit_id = u.id AND s.check_out_at IS NOT NULL
WHERE u.tenant_id = $1 AND u.status = 'TO_CLEAN' AND NOT u.retired
GROUP BY u.code
HAVING max(s.check_out_at) < $2
ORDER BY since, u.code
`

type ListLongToCleanParams struct {
	TenantID string
	Before   pgtype.Timestamptz
}

type ListLongToCleanRow struct {
	RoomCode string
	Since    pgtype.Timestamptz
}

// Rooms waiting to be cleaned since before the cutoff (last check-out time).
func (q *Queries) ListLongToClean(ctx context.Context, arg ListLongToCleanParams) ([]ListLongToCleanRow, error) {
	rows, err := q.db.Query(ctx, listLongToClean, arg.TenantID, arg.Before)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLongToCleanRow
	for rows.Next() {
		var i ListLongToCleanRow
		if err := rows.Scan(&i.RoomCode, &i.Since); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
SELECT t.id, t.happened_at, t.amount, t.method, t.room_code, t.bill_code, t.reconciliation, t.transfer_note,
       t.payment_event_id, t.shift_id, t.kind, t.received_at, t.settled_at
FROM app.transactions t
WHERE t.tenant_id = $1 AND t.happened_at >= $2 AND t.happened_at < $3
  AND ($4::text = 'ALL' OR ($4::text = 'NEEDS_ACTION' AND t.reconciliation IN ('MISMATCH', 'UNMATCHED')) OR t.method = $4::text)
  AND ($5::text IS NULL OR t.room_code ILIKE $5::text ESCAPE '\'
       OR t.bill_code ILIKE $5::text ESCAPE '\' OR t.transfer_note ILIKE $5::text ESCAPE '\')
  AND ($6::timestamptz IS NULL OR (t.happened_at, t.id) < ($6::timestamptz, $7::text))
ORDER BY t.happened_at DESC, t.id DESC
LIMIT $8
`

type ListTransactionsParams struct {
	TenantID string
	FromAt   pgtype.Timestamptz
	ToAt     pgtype.Timestamptz
	Kind     string
	Pattern  pgtype.Text
	CursorAt pgtype.Timestamptz
	CursorID pgtype.Text
	RowLimit int32
}

type ListTransactionsRow struct {
	ID             string
	HappenedAt     pgtype.Timestamptz
	Amount         int64
	Method         string
	RoomCode       string
	BillCode       string
	Reconciliation string
	TransferNote   string
	PaymentEventID string
	ShiftID        string
	Kind           string
	ReceivedAt     pgtype.Timestamptz
	SettledAt      pgtype.Timestamptz
}

// Reads the app.transactions view (migration 0015): paid cash and transfers, transfers with a wrong amount (MISMATCH)
// and bank events nobody matched (UNMATCHED). The view runs with the caller's rights, so row-level security applies.
func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listTransactions,
		arg.TenantID,
		arg.FromAt,
		arg.ToAt,
		arg.Kind,
		arg.Pattern,
		arg.CursorAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionsRow
	for rows.Next() {
		var i ListTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.HappenedAt,
			&i.Amount,
			&i.Method,
			&i.RoomCode,
			&i.BillCode,
			&i.Reconciliation,
			&i.TransferNote,
			&i.PaymentEventID,
			&i.ShiftID,
			&i.Kind,
			&i.ReceivedAt,
			&i.SettledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnpaidInvoices = `-- name: ListUnpaidInvoices :many
SELECT iv.id, iv.bill_code, un.code AS room_code, s.guest_name, s.check_out_at, iv.total,
       least(coalesce((iv.quote->>'depositPaid')::bigint, 0), iv.total)::bigint AS deposit,
       (coalesce((SELECT sum(coalesce(p.received_amount, 0)) FROM app.payments p
                  WHERE p.tenant_id = iv.tenant_id AND p.invoice_id = iv.id AND p.status = 'MISMATCH'), 0)
        + coalesce((SELECT sum(pe.amount) FROM app.payment_events pe
                    WHERE pe.tenant_id = iv.tenant_id AND pe.invoice_id = iv.id AND pe.result = 'PARTIAL'), 0))::bigint AS reported
FROM app.invoices iv
JOIN app.stays s ON s.tenant_id = iv.tenant_id AND s.id = iv.stay_id
JOIN app.units un ON un.tenant_id = s.tenant_id AND un.id = s.unit_id
WHERE iv.tenant_id = $1 AND iv.status = 'OPEN' AND s.check_out_at IS NOT NULL
  AND coalesce((iv.quote->>'balanceDue')::bigint, 0) > 0
ORDER BY s.check_out_at DESC, iv.id DESC
LIMIT 500
`

type ListUnpaidInvoicesRow struct {
	ID         string
	BillCode   string
	RoomCode   string
	GuestName  string
	CheckOutAt pgtype.Timestamptz
	Total      int64
	Deposit    int64
	Reported   int64
}

// Checked-out invoices still open with something to pay. paid is the deposit plus money the bank reported that did not
// settle the invoice (a transfer of the wrong amount); the caller works out the balance and the order.
func (q *Queries) ListUnpaidInvoices(ctx context.Context, tenantID string) ([]ListUnpaidInvoicesRow, error) {
	rows, err := q.db.Query(ctx, listUnpaidInvoices, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnpaidInvoicesRow
	for rows.Next() {
		var i ListUnpaidInvoicesRow
		if err := rows.Scan(
			&i.ID,
			&i.BillCode,
			&i.RoomCode,
			&i.GuestName,
			&i.CheckOutAt,
			&i.Total,
			&i.Deposit,
			&i.Reported,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPaymentEvent = `-- name: LockPaymentEvent :one
SELECT id, provider, external_id, amount, coalesce(reference_code, '') AS content, result, received_at
FROM app.payment_events
WHERE tenant_id = $1 AND id = $2
FOR UPDATE
`

type LockPaymentEventParams struct {
	TenantID pgtype.Text
	EventID  string
}

type LockPaymentEventRow struct {
	ID         string
	Provider   string
	ExternalID string
	Amount     int64
	Content    string
	Result     string
	ReceivedAt pgtype.Timestamptz
}

func (q *Queries) LockPaymentEvent(ctx context.Context, arg LockPaymentEventParams) (LockPaymentEventRow, error) {
	row := q.db.QueryRow(ctx, lockPaymentEvent, arg.TenantID, arg.EventID)
	var i LockPaymentEventRow
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ExternalID,
		&i.Amount,
		&i.Content,
		&i.Result,
		&i.ReceivedAt,
	)
	return i, err
}

const markAlertRead = `-- name: MarkAlertRead :execrows
UPDATE app.alerts SET read_at = coalesce(read_at, $1), read_by = coalesce(read_by, $2)
WHERE tenant_id = $3 AND id = $4
`

type MarkAlertReadParams struct {
	ReadAt   pgtype.Timestamptz
	ReadBy   pgtype.Text
	TenantID string
	AlertID  string
}

// An alert already read stays as it was: the first reader and time are kept, and the call still succeeds.
func (q *Queries) MarkAlertRead(ctx context.Context, arg MarkAlertReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markAlertRead,
		arg.ReadAt,
		arg.ReadBy,
		arg.TenantID,
		arg.AlertID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
