// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: owner.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ownerLatestPayments = `-- name: OwnerLatestPayments :many
SELECT p.id, u.code AS room_code, p.method, p.amount, p.paid_at
FROM app.payments p
JOIN app.invoices i ON i.tenant_id = p.tenant_id AND i.id = p.invoice_id
JOIN app.stays s ON s.tenant_id = i.tenant_id AND s.id = i.stay_id
JOIN app.units u ON u.tenant_id = s.tenant_id AND u.id = s.unit_id
WHERE p.tenant_id = $1 AND p.status = 'PAID'
ORDER BY p.paid_at DESC, p.id DESC
LIMIT $2
`

type OwnerLatestPaymentsParams struct {
	TenantID string
	MaxRows  int32
}

type OwnerLatestPaymentsRow struct {
	ID       string
	RoomCode string
	Method   string
	Amount   int64
	PaidAt   pgtype.Timestamptz
}

func (q *Queries) OwnerLatestPayments(ctx context.Context, arg OwnerLatestPaymentsParams) ([]OwnerLatestPaymentsRow, error) {
	rows, err := q.db.Query(ctx, ownerLatestPayments, arg.TenantID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OwnerLatestPaymentsRow
	for rows.Next() {
		var i OwnerLatestPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomCode,
			&i.Method,
			&i.Amount,
			&i.PaidAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ownerRevenueByBuilding = `-- name: OwnerRevenueByBuilding :many

SELECT b.id, b.name,
       COALESCE(SUM(least(coalesce((iv.quote->>'depositPaid')::bigint, 0), iv.total)
                    + CASE WHEN p.method = 'CASH' THEN coalesce((iv.quote->>'balanceDue')::bigint, 0) ELSE 0 END), 0)::bigint AS cash,
       COALESCE(SUM(CASE WHEN p.method = 'TRANSFER' THEN coalesce((iv.quote->>'balanceDue')::bigint, 0) ELSE 0 END), 0)::bigint AS transfer
FROM app.buildings b
LEFT JOIN app.units u ON u.tenant_id = b.tenant_id AND u.building_id = b.id
LEFT JOIN app.stays s ON s.tenant_id = u.tenant_id AND s.unit_id = u.id
LEFT JOIN app.invoices iv ON iv.tenant_id = s.tenant_id AND iv.stay_id = s.id AND iv.status = 'PAID'
                         AND iv.paid_at >= $1 AND iv.paid_at < $2
LEFT JOIN app.payments p ON p.tenant_id = iv.tenant_id AND p.invoice_id = iv.id AND p.status = 'PAID'
WHERE b.tenant_id = $3
GROUP BY b.id, b.name, b.code
ORDER BY b.code
`

type OwnerRevenueByBuildingParams struct {
	FromAt   pgtype.Timestamptz
	ToAt     pgtype.Timestamptz
	TenantID string
}

type OwnerRevenueByBuildingRow struct {
	ID       string
	Name     string
	Cash     int64
	Transfer int64
}

// Every query filters by tenant explicitly; RLS is the second guard (ADR-005).
// Revenue is what invoices paid in [from, to) were for, like the income and cost report: the deposit (taken in cash at
// check-in) counts as cash, and the rest by the method of the payment that settled the invoice. Buildings without
// invoices are listed with zeros.
func (q *Queries) OwnerRevenueByBuilding(ctx context.Context, arg OwnerRevenueByBuildingParams) ([]OwnerRevenueByBuildingRow, error) {
	rows, err := q.db.Query(ctx, ownerRevenueByBuilding, arg.FromAt, arg.ToAt, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OwnerRevenueByBuildingRow
	for rows.Next() {
		var i OwnerRevenueByBuildingRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Cash,
			&i.Transfer,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
