// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const expirePendingForInvoice = `-- name: ExpirePendingForInvoice :exec
UPDATE app.payments SET status = 'EXPIRED'
WHERE tenant_id = $1 AND invoice_id = $2 AND status = 'PENDING'
`

type ExpirePendingForInvoiceParams struct {
	TenantID  string
	InvoiceID string
}

func (q *Queries) ExpirePendingForInvoice(ctx context.Context, arg ExpirePendingForInvoiceParams) error {
	_, err := q.db.Exec(ctx, expirePendingForInvoice, arg.TenantID, arg.InvoiceID)
	return err
}

const getDefaultBankAccount = `-- name: GetDefaultBankAccount :one
SELECT id, account_enc FROM app.bank_accounts
WHERE tenant_id = $1 AND is_default AND sepay_status = 'CONNECTED'
`

type GetDefaultBankAccountRow struct {
	ID         string
	AccountEnc []byte
}

func (q *Queries) GetDefaultBankAccount(ctx context.Context, tenantID string) (GetDefaultBankAccountRow, error) {
	row := q.db.QueryRow(ctx, getDefaultBankAccount, tenantID)
	var i GetDefaultBankAccountRow
	err := row.Scan(&i.ID, &i.AccountEnc)
	return i, err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT p.id, p.invoice_id, p.method, p.status, p.amount, p.received_amount, p.paid_at, p.transaction_id,
       i.bill_code, u.building_id
FROM app.payments p
JOIN app.invoices i ON i.tenant_id = p.tenant_id AND i.id = p.invoice_id
JOIN app.stays s ON s.tenant_id = i.tenant_id AND s.id = i.stay_id
JOIN app.units u ON u.tenant_id = s.tenant_id AND u.id = s.unit_id
WHERE p.tenant_id = $1 AND p.id = $2
`

type GetPaymentByIDParams struct {
	TenantID  string
	PaymentID string
}

type GetPaymentByIDRow struct {
	ID             string
	InvoiceID      string
	Method         string
	Status         string
	Amount         int64
	ReceivedAmount pgtype.Int8
	PaidAt         pgtype.Timestamptz
	TransactionID  pgtype.Text
	BillCode       string
	BuildingID     string
}

func (q *Queries) GetPaymentByID(ctx context.Context, arg GetPaymentByIDParams) (GetPaymentByIDRow, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, arg.TenantID, arg.PaymentID)
	var i GetPaymentByIDRow
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.Method,
		&i.Status,
		&i.Amount,
		&i.ReceivedAmount,
		&i.PaidAt,
		&i.TransactionID,
		&i.BillCode,
		&i.BuildingID,
	)
	return i, err
}

const getPendingPaymentForInvoice = `-- name: GetPendingPaymentForInvoice :one
SELECT p.id, p.invoice_id, p.method, p.status, p.amount, p.received_amount, p.paid_at, p.transaction_id,
       i.bill_code, u.building_id
FROM app.payments p
JOIN app.invoices i ON i.tenant_id = p.tenant_id AND i.id = p.invoice_id
JOIN app.stays s ON s.tenant_id = i.tenant_id AND s.id = i.stay_id
JOIN app.units u ON u.tenant_id = s.tenant_id AND u.id = s.unit_id
WHERE p.tenant_id = $1 AND p.invoice_id = $2 AND p.status = 'PENDING'
`

type GetPendingPaymentForInvoiceParams struct {
	TenantID  string
	InvoiceID string
}

type GetPendingPaymentForInvoiceRow struct {
	ID             string
	InvoiceID      string
	Method         string
	Status         string
	Amount         int64
	ReceivedAmount pgtype.Int8
	PaidAt         pgtype.Timestamptz
	TransactionID  pgtype.Text
	BillCode       string
	BuildingID     string
}

func (q *Queries) GetPendingPaymentForInvoice(ctx context.Context, arg GetPendingPaymentForInvoiceParams) (GetPendingPaymentForInvoiceRow, error) {
	row := q.db.QueryRow(ctx, getPendingPaymentForInvoice, arg.TenantID, arg.InvoiceID)
	var i GetPendingPaymentForInvoiceRow
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.Method,
		&i.Status,
		&i.Amount,
		&i.ReceivedAmount,
		&i.PaidAt,
		&i.TransactionID,
		&i.BillCode,
		&i.BuildingID,
	)
	return i, err
}

const insertCashPayment = `-- name: InsertCashPayment :exec
INSERT INTO app.payments (id, tenant_id, invoice_id, method, status, amount, created_at, paid_at, received_amount)
VALUES ($1, $2, $3, 'CASH', 'PAID', $4, $5, $5, $4)
`

type InsertCashPaymentParams struct {
	ID        string
	TenantID  string
	InvoiceID string
	Amount    int64
	At        pgtype.Timestamptz
}

func (q *Queries) InsertCashPayment(ctx context.Context, arg InsertCashPaymentParams) error {
	_, err := q.db.Exec(ctx, insertCashPayment,
		arg.ID,
		arg.TenantID,
		arg.InvoiceID,
		arg.Amount,
		arg.At,
	)
	return err
}

const insertPaymentEvent = `-- name: InsertPaymentEvent :execrows
INSERT INTO app.payment_events (id, tenant_id, provider, external_id, amount, reference_code, result, received_at)
VALUES ($1, $2, $3, $4, $5, $6, 'UNMATCHED', $7)
ON CONFLICT (provider, external_id) DO NOTHING
`

type InsertPaymentEventParams struct {
	ID            string
	TenantID      pgtype.Text
	Provider      string
	ExternalID    string
	Amount        int64
	ReferenceCode pgtype.Text
	ReceivedAt    pgtype.Timestamptz
}

func (q *Queries) InsertPaymentEvent(ctx context.Context, arg InsertPaymentEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertPaymentEvent,
		arg.ID,
		arg.TenantID,
		arg.Provider,
		arg.ExternalID,
		arg.Amount,
		arg.ReferenceCode,
		arg.ReceivedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertPendingTransfer = `-- name: InsertPendingTransfer :exec
INSERT INTO app.payments (id, tenant_id, invoice_id, method, status, amount, reference_code, created_at)
VALUES ($1, $2, $3, 'TRANSFER', 'PENDING', $4, $5, $6)
`

type InsertPendingTransferParams struct {
	ID            string
	TenantID      string
	InvoiceID     string
	Amount        int64
	ReferenceCode pgtype.Text
	CreatedAt     pgtype.Timestamptz
}

func (q *Queries) InsertPendingTransfer(ctx context.Context, arg InsertPendingTransferParams) error {
	_, err := q.db.Exec(ctx, insertPendingTransfer,
		arg.ID,
		arg.TenantID,
		arg.InvoiceID,
		arg.Amount,
		arg.ReferenceCode,
		arg.CreatedAt,
	)
	return err
}

const listPendingTransfers = `-- name: ListPendingTransfers :many
SELECT p.id, p.invoice_id, p.amount, i.bill_code, i.stay_id, u.code AS room_code
FROM app.payments p
JOIN app.invoices i ON i.tenant_id = p.tenant_id AND i.id = p.invoice_id
JOIN app.stays s ON s.tenant_id = i.tenant_id AND s.id = i.stay_id
JOIN app.units u ON u.tenant_id = s.tenant_id AND u.id = s.unit_id
WHERE p.tenant_id = $1 AND p.method = 'TRANSFER' AND p.status = 'PENDING'
`

type ListPendingTransfersRow struct {
	ID        string
	InvoiceID string
	Amount    int64
	BillCode  string
	StayID    string
	RoomCode  string
}

func (q *Queries) ListPendingTransfers(ctx context.Context, tenantID string) ([]ListPendingTransfersRow, error) {
	rows, err := q.db.Query(ctx, listPendingTransfers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingTransfersRow
	for rows.Next() {
		var i ListPendingTransfersRow
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceID,
			&i.Amount,
			&i.BillCode,
			&i.StayID,
			&i.RoomCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockInvoiceForPayment = `-- name: LockInvoiceForPayment :one

SELECT i.id, i.status, i.bill_code, i.stay_id, i.quote, u.building_id
FROM app.invoices i
JOIN app.stays s ON s.tenant_id = i.tenant_id AND s.id = i.stay_id
JOIN app.units u ON u.tenant_id = s.tenant_id AND u.id = s.unit_id
WHERE i.tenant_id = $1 AND i.id = $2
FOR UPDATE OF i
`

type LockInvoiceForPaymentParams struct {
	TenantID  string
	InvoiceID string
}

type LockInvoiceForPaymentRow struct {
	ID         string
	Status     string
	BillCode   string
	StayID     string
	Quote      []byte
	BuildingID string
}

// Every query filters by tenant explicitly; RLS is the second guard (ADR-005).
// Rule: a TRANSFER payment is created PENDING and becomes PAID only through SettleTransfer, which only the
// payment-event handler calls (CLAUDE.md §4.4). TestOnlySettleQuerySetsPaid_A2 guards this file.
func (q *Queries) LockInvoiceForPayment(ctx context.Context, arg LockInvoiceForPaymentParams) (LockInvoiceForPaymentRow, error) {
	row := q.db.QueryRow(ctx, lockInvoiceForPayment, arg.TenantID, arg.InvoiceID)
	var i LockInvoiceForPaymentRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.BillCode,
		&i.StayID,
		&i.Quote,
		&i.BuildingID,
	)
	return i, err
}

const markInvoicePaid = `-- name: MarkInvoicePaid :execrows
UPDATE app.invoices SET status = 'PAID', paid_at = $1
WHERE tenant_id = $2 AND id = $3 AND status = 'OPEN'
`

type MarkInvoicePaidParams struct {
	PaidAt    pgtype.Timestamptz
	TenantID  string
	InvoiceID string
}

func (q *Queries) MarkInvoicePaid(ctx context.Context, arg MarkInvoicePaidParams) (int64, error) {
	result, err := q.db.Exec(ctx, markInvoicePaid, arg.PaidAt, arg.TenantID, arg.InvoiceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markTransferMismatch = `-- name: MarkTransferMismatch :execrows
UPDATE app.payments
SET status = 'MISMATCH', received_amount = $1, transaction_id = $2
WHERE tenant_id = $3 AND id = $4 AND method = 'TRANSFER' AND status = 'PENDING'
`

type MarkTransferMismatchParams struct {
	ReceivedAmount pgtype.Int8
	TransactionID  pgtype.Text
	TenantID       string
	PaymentID      string
}

func (q *Queries) MarkTransferMismatch(ctx context.Context, arg MarkTransferMismatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, markTransferMismatch,
		arg.ReceivedAmount,
		arg.TransactionID,
		arg.TenantID,
		arg.PaymentID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseRoomToClean = `-- name: ReleaseRoomToClean :exec
UPDATE app.units u SET status = 'TO_CLEAN'
FROM app.stays s
WHERE u.tenant_id = $1 AND u.status = 'OCCUPIED'
  AND s.tenant_id = u.tenant_id AND s.id = $2 AND s.unit_id = u.id
`

type ReleaseRoomToCleanParams struct {
	TenantID string
	StayID   string
}

func (q *Queries) ReleaseRoomToClean(ctx context.Context, arg ReleaseRoomToCleanParams) error {
	_, err := q.db.Exec(ctx, releaseRoomToClean, arg.TenantID, arg.StayID)
	return err
}

const setPaymentEventResult = `-- name: SetPaymentEventResult :exec
UPDATE app.payment_events SET result = $1
WHERE tenant_id = $2 AND provider = $3 AND external_id = $4
`

type SetPaymentEventResultParams struct {
	Result     string
	TenantID   pgtype.Text
	Provider   string
	ExternalID string
}

func (q *Queries) SetPaymentEventResult(ctx context.Context, arg SetPaymentEventResultParams) error {
	_, err := q.db.Exec(ctx, setPaymentEventResult,
		arg.Result,
		arg.TenantID,
		arg.Provider,
		arg.ExternalID,
	)
	return err
}

const settleTransfer = `-- name: SettleTransfer :execrows
UPDATE app.payments
SET status = 'PAID', paid_at = $1, received_amount = $2, transaction_id = $3
WHERE tenant_id = $4 AND id = $5 AND method = 'TRANSFER' AND status = 'PENDING'
`

type SettleTransferParams struct {
	PaidAt         pgtype.Timestamptz
	ReceivedAmount pgtype.Int8
	TransactionID  pgtype.Text
	TenantID       string
	PaymentID      string
}

func (q *Queries) SettleTransfer(ctx context.Context, arg SettleTransferParams) (int64, error) {
	result, err := q.db.Exec(ctx, settleTransfer,
		arg.PaidAt,
		arg.ReceivedAmount,
		arg.TransactionID,
		arg.TenantID,
		arg.PaymentID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
