// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rooms.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listBuildings = `-- name: ListBuildings :many

SELECT id, code, name FROM app.buildings WHERE tenant_id = $1 ORDER BY code, id
`

type ListBuildingsRow struct {
	ID   string
	Code string
	Name string
}

// Every query filters by tenant explicitly; RLS is the second guard (ADR-005).
func (q *Queries) ListBuildings(ctx context.Context, tenantID string) ([]ListBuildingsRow, error) {
	rows, err := q.db.Query(ctx, listBuildings, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBuildingsRow
	for rows.Next() {
		var i ListBuildingsRow
		if err := rows.Scan(&i.ID, &i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFloors = `-- name: ListFloors :many
SELECT id, building_id, level, name FROM app.floors WHERE tenant_id = $1 ORDER BY building_id, level, id
`

type ListFloorsRow struct {
	ID         string
	BuildingID string
	Level      int32
	Name       pgtype.Text
}

func (q *Queries) ListFloors(ctx context.Context, tenantID string) ([]ListFloorsRow, error) {
	rows, err := q.db.Query(ctx, listFloors, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFloorsRow
	for rows.Next() {
		var i ListFloorsRow
		if err := rows.Scan(
			&i.ID,
			&i.BuildingID,
			&i.Level,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRooms = `-- name: ListRooms :many
SELECT u.id, u.code, u.building_id, f.id AS floor_id, f.name AS floor_name, f.level AS floor_level,
       ut.code AS unit_type_code, ut.name AS unit_type_name, u.status,
       coalesce(jsonb_typeof(u.attributes->'note') = 'string', false)::boolean AS has_note, coalesce(u.attributes->>'note', '')::text AS note,
       s.id AS stay_id, s.rental_type AS stay_rental_type, s.guest_name AS stay_guest_name,
       s.check_in_at AS stay_check_in_at, s.rate_plan_snapshot AS stay_rate_plan_snapshot, s.check_out_at AS stay_check_out_at,
       iv.id AS inv_id, coalesce(iv.total, 0)::bigint AS inv_total,
       coalesce(s.deposit, 0)::bigint AS inv_deposit,
       greatest(coalesce(s.deposit, 0) - coalesce(iv.total, 0), 0)::bigint AS inv_refund_due, iv.created_at AS inv_created_at,
       coalesce((SELECT sum(pe.amount) FROM app.payment_events pe WHERE pe.tenant_id = iv.tenant_id AND pe.invoice_id = iv.id AND pe.result = 'PARTIAL'), 0)::bigint AS inv_received,
       coalesce((SELECT p.id FROM app.payments p WHERE p.tenant_id = iv.tenant_id AND p.invoice_id = iv.id AND p.method = 'TRANSFER' AND p.status = 'PENDING'
                 ORDER BY p.created_at DESC LIMIT 1), '')::text AS inv_payment_id
FROM app.units u
JOIN app.floors f ON f.tenant_id = u.tenant_id AND f.id = u.floor_id
JOIN app.unit_types ut ON ut.tenant_id = u.tenant_id AND ut.id = u.unit_type_id
LEFT JOIN app.stays s ON s.tenant_id = u.tenant_id AND s.unit_id = u.id
     AND (s.status = 'ACTIVE' OR (s.status = 'CHECKED_OUT' AND EXISTS (SELECT 1 FROM app.invoices x WHERE x.tenant_id = s.tenant_id AND x.stay_id = s.id AND x.status = 'OPEN')))
LEFT JOIN app.invoices iv ON iv.tenant_id = s.tenant_id AND iv.stay_id = s.id AND iv.status = 'OPEN'
WHERE u.tenant_id = $1 AND NOT u.retired
  AND ($2::text = '' OR u.building_id = $2::text)
  AND ($3::text = '' OR u.id = $3::text)
ORDER BY u.building_id, u.code
`

type ListRoomsParams struct {
	TenantID   string
	BuildingID string
	UnitID     string
}

type ListRoomsRow struct {
	ID                   string
	Code                 string
	BuildingID           string
	FloorID              string
	FloorName            pgtype.Text
	FloorLevel           int32
	UnitTypeCode         string
	UnitTypeName         []byte
	Status               string
	HasNote              bool
	Note                 string
	StayID               pgtype.Text
	StayRentalType       pgtype.Text
	StayGuestName        pgtype.Text
	StayCheckInAt        pgtype.Timestamptz
	StayRatePlanSnapshot []byte
	StayCheckOutAt       pgtype.Timestamptz
	InvID                pgtype.Text
	InvTotal             int64
	InvDeposit           int64
	InvRefundDue         int64
	InvCreatedAt         pgtype.Timestamptz
	InvReceived          int64
	InvPaymentID         string
}

// One statement for the whole map; an empty filter argument means no filter. A checked-out stay whose invoice is still open
// (the room stays OCCUPIED until it is paid) comes with that invoice's money so far.
func (q *Queries) ListRooms(ctx context.Context, arg ListRoomsParams) ([]ListRoomsRow, error) {
	rows, err := q.db.Query(ctx, listRooms, arg.TenantID, arg.BuildingID, arg.UnitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomsRow
	for rows.Next() {
		var i ListRoomsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.BuildingID,
			&i.FloorID,
			&i.FloorName,
			&i.FloorLevel,
			&i.UnitTypeCode,
			&i.UnitTypeName,
			&i.Status,
			&i.HasNote,
			&i.Note,
			&i.StayID,
			&i.StayRentalType,
			&i.StayGuestName,
			&i.StayCheckInAt,
			&i.StayRatePlanSnapshot,
			&i.StayCheckOutAt,
			&i.InvID,
			&i.InvTotal,
			&i.InvDeposit,
			&i.InvRefundDue,
			&i.InvCreatedAt,
			&i.InvReceived,
			&i.InvPaymentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tenantTimezone = `-- name: TenantTimezone :one
SELECT time_zone FROM app.tenants WHERE id = $1
`

func (q *Queries) TenantTimezone(ctx context.Context, tenantID string) (string, error) {
	row := q.db.QueryRow(ctx, tenantTimezone, tenantID)
	var time_zone string
	err := row.Scan(&time_zone)
	return time_zone, err
}
