// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rooms.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listBuildings = `-- name: ListBuildings :many

SELECT id, code, name FROM app.buildings WHERE tenant_id = $1 ORDER BY code, id
`

type ListBuildingsRow struct {
	ID   string
	Code string
	Name string
}

// Every query filters by tenant explicitly; RLS is the second guard (ADR-005).
func (q *Queries) ListBuildings(ctx context.Context, tenantID string) ([]ListBuildingsRow, error) {
	rows, err := q.db.Query(ctx, listBuildings, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBuildingsRow
	for rows.Next() {
		var i ListBuildingsRow
		if err := rows.Scan(&i.ID, &i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRooms = `-- name: ListRooms :many
SELECT u.id, u.code, u.building_id, f.level AS floor_level,
       ut.code AS unit_type_code, ut.name AS unit_type_name, u.status,
       coalesce(jsonb_typeof(u.attributes->'note') = 'string', false)::boolean AS has_note, coalesce(u.attributes->>'note', '')::text AS note,
       s.id AS stay_id, s.rental_type AS stay_rental_type, s.guest_name AS stay_guest_name,
       s.check_in_at AS stay_check_in_at, s.rate_plan_snapshot AS stay_rate_plan_snapshot
FROM app.units u
JOIN app.floors f ON f.tenant_id = u.tenant_id AND f.id = u.floor_id
JOIN app.unit_types ut ON ut.tenant_id = u.tenant_id AND ut.id = u.unit_type_id
LEFT JOIN app.stays s ON s.tenant_id = u.tenant_id AND s.unit_id = u.id AND s.status = 'ACTIVE'
WHERE u.tenant_id = $1 AND NOT u.retired
  AND ($2::text = '' OR u.building_id = $2::text)
  AND ($3::text = '' OR u.id = $3::text)
ORDER BY u.building_id, u.code
`

type ListRoomsParams struct {
	TenantID   string
	BuildingID string
	UnitID     string
}

type ListRoomsRow struct {
	ID                   string
	Code                 string
	BuildingID           string
	FloorLevel           int32
	UnitTypeCode         string
	UnitTypeName         []byte
	Status               string
	HasNote              bool
	Note                 string
	StayID               pgtype.Text
	StayRentalType       pgtype.Text
	StayGuestName        pgtype.Text
	StayCheckInAt        pgtype.Timestamptz
	StayRatePlanSnapshot []byte
}

// One statement for the whole map; an empty filter argument means no filter.
func (q *Queries) ListRooms(ctx context.Context, arg ListRoomsParams) ([]ListRoomsRow, error) {
	rows, err := q.db.Query(ctx, listRooms, arg.TenantID, arg.BuildingID, arg.UnitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomsRow
	for rows.Next() {
		var i ListRoomsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.BuildingID,
			&i.FloorLevel,
			&i.UnitTypeCode,
			&i.UnitTypeName,
			&i.Status,
			&i.HasNote,
			&i.Note,
			&i.StayID,
			&i.StayRentalType,
			&i.StayGuestName,
			&i.StayCheckInAt,
			&i.StayRatePlanSnapshot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tenantTimezone = `-- name: TenantTimezone :one
SELECT time_zone FROM app.tenants WHERE id = $1
`

func (q *Queries) TenantTimezone(ctx context.Context, tenantID string) (string, error) {
	row := q.db.QueryRow(ctx, tenantTimezone, tenantID)
	var time_zone string
	err := row.Scan(&time_zone)
	return time_zone, err
}
