// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roster.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const copyRosterWeek = `-- name: CopyRosterWeek :execrows
INSERT INTO app.roster_assignments (tenant_id, user_id, work_date, shift, created_by)
SELECT r.tenant_id, r.user_id, r.work_date + 7, r.shift, $1
FROM app.roster_assignments r
JOIN app.users u ON u.tenant_id = r.tenant_id AND u.id = r.user_id AND u.status <> 'REMOVED'
WHERE r.tenant_id = $2 AND r.work_date >= $3::date AND r.work_date < $3::date + 7
ON CONFLICT DO NOTHING
`

type CopyRosterWeekParams struct {
	CreatedBy pgtype.Text
	TenantID  string
	SrcFrom   pgtype.Date
}

// Seven days from @src_from, moved forward a week; people removed since are not copied.
func (q *Queries) CopyRosterWeek(ctx context.Context, arg CopyRosterWeekParams) (int64, error) {
	result, err := q.db.Exec(ctx, copyRosterWeek, arg.CreatedBy, arg.TenantID, arg.SrcFrom)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countOverlappingLeave = `-- name: CountOverlappingLeave :one
SELECT count(*) FROM app.leave_requests
WHERE tenant_id = $1 AND user_id = $2 AND status IN ('PENDING', 'APPROVED', 'CANCEL_REQUESTED')
  AND to_date >= $3 AND from_date <= $4
`

type CountOverlappingLeaveParams struct {
	TenantID string
	UserID   string
	FromDate pgtype.Date
	ToDate   pgtype.Date
}

func (q *Queries) CountOverlappingLeave(ctx context.Context, arg CountOverlappingLeaveParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOverlappingLeave,
		arg.TenantID,
		arg.UserID,
		arg.FromDate,
		arg.ToDate,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRosterBetween = `-- name: CountRosterBetween :one
SELECT count(*) FROM app.roster_assignments WHERE tenant_id = $1 AND work_date >= $2 AND work_date <= $3
`

type CountRosterBetweenParams struct {
	TenantID string
	FromDate pgtype.Date
	ToDate   pgtype.Date
}

func (q *Queries) CountRosterBetween(ctx context.Context, arg CountRosterBetweenParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRosterBetween, arg.TenantID, arg.FromDate, arg.ToDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteRosterAssignment = `-- name: DeleteRosterAssignment :execrows
DELETE FROM app.roster_assignments WHERE tenant_id = $1 AND user_id = $2 AND work_date = $3 AND shift = $4
`

type DeleteRosterAssignmentParams struct {
	TenantID string
	UserID   string
	WorkDate pgtype.Date
	Shift    string
}

func (q *Queries) DeleteRosterAssignment(ctx context.Context, arg DeleteRosterAssignmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRosterAssignment,
		arg.TenantID,
		arg.UserID,
		arg.WorkDate,
		arg.Shift,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAnnualLeaveDays = `-- name: GetAnnualLeaveDays :one
SELECT annual_leave_days FROM app.staff_profiles WHERE tenant_id = $1 AND user_id = $2
`

type GetAnnualLeaveDaysParams struct {
	TenantID string
	UserID   string
}

func (q *Queries) GetAnnualLeaveDays(ctx context.Context, arg GetAnnualLeaveDaysParams) (int32, error) {
	row := q.db.QueryRow(ctx, getAnnualLeaveDays, arg.TenantID, arg.UserID)
	var annual_leave_days int32
	err := row.Scan(&annual_leave_days)
	return annual_leave_days, err
}

const getLeave = `-- name: GetLeave :one
SELECT l.id, l.user_id, u.name AS user_name, l.from_date, l.to_date, coalesce(l.shift, '') AS shift, l.kind, coalesce(l.reason, '') AS reason,
       coalesce(l.cover_user_id, '') AS cover_user_id, l.status, coalesce(l.decline_reason, '') AS decline_reason, l.created_at, l.decided_at
FROM app.leave_requests l JOIN app.users u ON u.tenant_id = l.tenant_id AND u.id = l.user_id
WHERE l.tenant_id = $1 AND l.id = $2
`

type GetLeaveParams struct {
	TenantID string
	LeaveID  string
}

type GetLeaveRow struct {
	ID            string
	UserID        string
	UserName      string
	FromDate      pgtype.Date
	ToDate        pgtype.Date
	Shift         string
	Kind          string
	Reason        string
	CoverUserID   string
	Status        string
	DeclineReason string
	CreatedAt     pgtype.Timestamptz
	DecidedAt     pgtype.Timestamptz
}

func (q *Queries) GetLeave(ctx context.Context, arg GetLeaveParams) (GetLeaveRow, error) {
	row := q.db.QueryRow(ctx, getLeave, arg.TenantID, arg.LeaveID)
	var i GetLeaveRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserName,
		&i.FromDate,
		&i.ToDate,
		&i.Shift,
		&i.Kind,
		&i.Reason,
		&i.CoverUserID,
		&i.Status,
		&i.DeclineReason,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const insertLeave = `-- name: InsertLeave :exec
INSERT INTO app.leave_requests (id, tenant_id, user_id, from_date, to_date, shift, kind, reason, cover_user_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertLeaveParams struct {
	ID          string
	TenantID    string
	UserID      string
	FromDate    pgtype.Date
	ToDate      pgtype.Date
	Shift       pgtype.Text
	Kind        string
	Reason      pgtype.Text
	CoverUserID pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) InsertLeave(ctx context.Context, arg InsertLeaveParams) error {
	_, err := q.db.Exec(ctx, insertLeave,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.FromDate,
		arg.ToDate,
		arg.Shift,
		arg.Kind,
		arg.Reason,
		arg.CoverUserID,
		arg.CreatedAt,
	)
	return err
}

const insertRosterAssignment = `-- name: InsertRosterAssignment :execrows
INSERT INTO app.roster_assignments (tenant_id, user_id, work_date, shift, created_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT DO NOTHING
`

type InsertRosterAssignmentParams struct {
	TenantID  string
	UserID    string
	WorkDate  pgtype.Date
	Shift     string
	CreatedBy pgtype.Text
}

func (q *Queries) InsertRosterAssignment(ctx context.Context, arg InsertRosterAssignmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertRosterAssignment,
		arg.TenantID,
		arg.UserID,
		arg.WorkDate,
		arg.Shift,
		arg.CreatedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listActiveUserIDs = `-- name: ListActiveUserIDs :many
SELECT id FROM app.users WHERE tenant_id = $1 AND id = ANY($2::text[]) AND status <> 'REMOVED'
`

type ListActiveUserIDsParams struct {
	TenantID string
	UserIds  []string
}

// Who a roster may use: everyone not removed, including staff with no sign-in.
func (q *Queries) ListActiveUserIDs(ctx context.Context, arg ListActiveUserIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listActiveUserIDs, arg.TenantID, arg.UserIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeave = `-- name: ListLeave :many
SELECT l.id, l.user_id, u.name AS user_name, l.from_date, l.to_date, coalesce(l.shift, '') AS shift, l.kind, coalesce(l.reason, '') AS reason,
       coalesce(l.cover_user_id, '') AS cover_user_id, l.status, coalesce(l.decline_reason, '') AS decline_reason, l.created_at, l.decided_at
FROM app.leave_requests l JOIN app.users u ON u.tenant_id = l.tenant_id AND u.id = l.user_id
WHERE l.tenant_id = $1
  AND ($2::text IS NULL OR l.status = $2::text)
  AND ($3::text IS NULL OR l.user_id = $3::text)
  AND ($4::date IS NULL OR (l.to_date >= $4::date AND l.from_date <= $5::date))
  AND (NOT $6::boolean OR l.status IN ('PENDING', 'APPROVED', 'CANCEL_REQUESTED'))
ORDER BY l.from_date DESC, l.created_at DESC, l.id DESC
`

type ListLeaveParams struct {
	TenantID     string
	Status       pgtype.Text
	UserID       pgtype.Text
	FromDate     pgtype.Date
	ToDate       pgtype.Date
	StandingOnly bool
}

type ListLeaveRow struct {
	ID            string
	UserID        string
	UserName      string
	FromDate      pgtype.Date
	ToDate        pgtype.Date
	Shift         string
	Kind          string
	Reason        string
	CoverUserID   string
	Status        string
	DeclineReason string
	CreatedAt     pgtype.Timestamptz
	DecidedAt     pgtype.Timestamptz
}

// Filters are all optional: a status, a person, and the days a request must touch.
func (q *Queries) ListLeave(ctx context.Context, arg ListLeaveParams) ([]ListLeaveRow, error) {
	rows, err := q.db.Query(ctx, listLeave,
		arg.TenantID,
		arg.Status,
		arg.UserID,
		arg.FromDate,
		arg.ToDate,
		arg.StandingOnly,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLeaveRow
	for rows.Next() {
		var i ListLeaveRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.UserName,
			&i.FromDate,
			&i.ToDate,
			&i.Shift,
			&i.Kind,
			&i.Reason,
			&i.CoverUserID,
			&i.Status,
			&i.DeclineReason,
			&i.CreatedAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingLeave = `-- name: ListPendingLeave :many
SELECT l.id, u.name AS user_name FROM app.leave_requests l JOIN app.users u ON u.tenant_id = l.tenant_id AND u.id = l.user_id
WHERE l.tenant_id = $1 AND l.status = 'PENDING' ORDER BY l.created_at, l.id
`

type ListPendingLeaveRow struct {
	ID       string
	UserName string
}

func (q *Queries) ListPendingLeave(ctx context.Context, tenantID string) ([]ListPendingLeaveRow, error) {
	rows, err := q.db.Query(ctx, listPendingLeave, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingLeaveRow
	for rows.Next() {
		var i ListPendingLeaveRow
		if err := rows.Scan(&i.ID, &i.UserName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRosterAssignments = `-- name: ListRosterAssignments :many
SELECT user_id, work_date, shift FROM app.roster_assignments
WHERE tenant_id = $1 AND work_date >= $2 AND work_date <= $3
ORDER BY work_date, shift, user_id
`

type ListRosterAssignmentsParams struct {
	TenantID string
	FromDate pgtype.Date
	ToDate   pgtype.Date
}

type ListRosterAssignmentsRow struct {
	UserID   string
	WorkDate pgtype.Date
	Shift    string
}

func (q *Queries) ListRosterAssignments(ctx context.Context, arg ListRosterAssignmentsParams) ([]ListRosterAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listRosterAssignments, arg.TenantID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRosterAssignmentsRow
	for rows.Next() {
		var i ListRosterAssignmentsRow
		if err := rows.Scan(&i.UserID, &i.WorkDate, &i.Shift); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledShifts = `-- name: ListScheduledShifts :many
SELECT shift FROM app.roster_assignments
WHERE tenant_id = $1 AND user_id = $2
  AND ((work_date = $3::date AND shift <> 'NIGHT') OR (work_date = $3::date - 1 AND shift = 'NIGHT') OR (work_date = $3::date AND shift = 'NIGHT'))
ORDER BY CASE shift WHEN 'MORNING' THEN 1 WHEN 'AFTERNOON' THEN 2 ELSE 3 END
`

type ListScheduledShiftsParams struct {
	TenantID string
	UserID   string
	Day      pgtype.Date
}

// The shifts a person is rostered for on a day; a NIGHT shift started the evening before still counts after midnight.
func (q *Queries) ListScheduledShifts(ctx context.Context, arg ListScheduledShiftsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listScheduledShifts, arg.TenantID, arg.UserID, arg.Day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var shift string
		if err := rows.Scan(&shift); err != nil {
			return nil, err
		}
		items = append(items, shift)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLeave = `-- name: LockLeave :one
SELECT id FROM app.leave_requests WHERE tenant_id = $1 AND id = $2 FOR UPDATE
`

type LockLeaveParams struct {
	TenantID string
	LeaveID  string
}

func (q *Queries) LockLeave(ctx context.Context, arg LockLeaveParams) (string, error) {
	row := q.db.QueryRow(ctx, lockLeave, arg.TenantID, arg.LeaveID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const setLeaveStatus = `-- name: SetLeaveStatus :exec
UPDATE app.leave_requests SET status = $1, decline_reason = $2, decided_at = $3, decided_by = $4
WHERE tenant_id = $5 AND id = $6
`

type SetLeaveStatusParams struct {
	Status        string
	DeclineReason pgtype.Text
	DecidedAt     pgtype.Timestamptz
	DecidedBy     pgtype.Text
	TenantID      string
	LeaveID       string
}

func (q *Queries) SetLeaveStatus(ctx context.Context, arg SetLeaveStatusParams) error {
	_, err := q.db.Exec(ctx, setLeaveStatus,
		arg.Status,
		arg.DeclineReason,
		arg.DecidedAt,
		arg.DecidedBy,
		arg.TenantID,
		arg.LeaveID,
	)
	return err
}

const sumPaidLeaveDays = `-- name: SumPaidLeaveDays :one
SELECT coalesce(sum(least(to_date, $1::date) - greatest(from_date, $2::date) + 1), 0)::bigint AS days
FROM app.leave_requests
WHERE tenant_id = $3 AND user_id = $4 AND kind = 'PAID' AND status IN ('APPROVED', 'CANCEL_REQUESTED')
  AND to_date >= $2::date AND from_date <= $1::date
`

type SumPaidLeaveDaysParams struct {
	YearEnd   pgtype.Date
	YearStart pgtype.Date
	TenantID  string
	UserID    string
}

// Days of paid leave that stand (approved, or approved with a cancel pending) inside the year.
func (q *Queries) SumPaidLeaveDays(ctx context.Context, arg SumPaidLeaveDaysParams) (int64, error) {
	row := q.db.QueryRow(ctx, sumPaidLeaveDays,
		arg.YearEnd,
		arg.YearStart,
		arg.TenantID,
		arg.UserID,
	)
	var days int64
	err := row.Scan(&days)
	return days, err
}
