// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const decrementServiceStock = `-- name: DecrementServiceStock :one
UPDATE app.services SET stock = stock - $1
WHERE tenant_id = $2 AND id = $3 AND stock >= $1
RETURNING price
`

type DecrementServiceStockParams struct {
	Qty       int64
	TenantID  string
	ServiceID string
}

// The guard is in the WHERE: zero rows means not enough stock, never a read followed by a write.
func (q *Queries) DecrementServiceStock(ctx context.Context, arg DecrementServiceStockParams) (int64, error) {
	row := q.db.QueryRow(ctx, decrementServiceStock, arg.Qty, arg.TenantID, arg.ServiceID)
	var price int64
	err := row.Scan(&price)
	return price, err
}

const listServices = `-- name: ListServices :many

SELECT s.id, s.code, s.name, s.price, s.stock, s.unit, s.low_stock_at, s.on_sale, s.latest_unit_cost,
       COALESCE((SELECT sum(x.quantity) FROM app.stay_extras x
                 WHERE x.tenant_id = s.tenant_id AND x.service_id = s.id AND x.created_at >= $1), 0)::bigint AS sold_recent
FROM app.services s
WHERE s.tenant_id = $2 AND (s.on_sale OR $3::boolean)
ORDER BY s.code
`

type ListServicesParams struct {
	Since          pgtype.Timestamptz
	TenantID       string
	IncludeOffSale bool
}

type ListServicesRow struct {
	ID             string
	Code           string
	Name           []byte
	Price          int64
	Stock          int64
	Unit           string
	LowStockAt     int32
	OnSale         bool
	LatestUnitCost pgtype.Int8
	SoldRecent     int64
}

// Every query filters by tenant explicitly; RLS is the second guard (ADR-005).
// The front desk sees items on sale; the owner and manager see everything. soldLast7Days counts extras added in the window.
func (q *Queries) ListServices(ctx context.Context, arg ListServicesParams) ([]ListServicesRow, error) {
	rows, err := q.db.Query(ctx, listServices, arg.Since, arg.TenantID, arg.IncludeOffSale)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListServicesRow
	for rows.Next() {
		var i ListServicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Price,
			&i.Stock,
			&i.Unit,
			&i.LowStockAt,
			&i.OnSale,
			&i.LatestUnitCost,
			&i.SoldRecent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesByCodes = `-- name: ListServicesByCodes :many
SELECT id, code, name, price, stock
FROM app.services
WHERE tenant_id = $1 AND on_sale AND code = ANY($2::text[])
ORDER BY code
`

type ListServicesByCodesParams struct {
	TenantID string
	Codes    []string
}

type ListServicesByCodesRow struct {
	ID    string
	Code  string
	Name  []byte
	Price int64
	Stock int64
}

func (q *Queries) ListServicesByCodes(ctx context.Context, arg ListServicesByCodesParams) ([]ListServicesByCodesRow, error) {
	rows, err := q.db.Query(ctx, listServicesByCodes, arg.TenantID, arg.Codes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListServicesByCodesRow
	for rows.Next() {
		var i ListServicesByCodesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Price,
			&i.Stock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
