// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package sqlcgen

import (
	"context"
)

const decrementServiceStock = `-- name: DecrementServiceStock :one
UPDATE app.services SET stock = stock - $1
WHERE tenant_id = $2 AND id = $3 AND stock >= $1
RETURNING price
`

type DecrementServiceStockParams struct {
	Qty       int64
	TenantID  string
	ServiceID string
}

// The guard is in the WHERE: zero rows means not enough stock, never a read followed by a write.
func (q *Queries) DecrementServiceStock(ctx context.Context, arg DecrementServiceStockParams) (int64, error) {
	row := q.db.QueryRow(ctx, decrementServiceStock, arg.Qty, arg.TenantID, arg.ServiceID)
	var price int64
	err := row.Scan(&price)
	return price, err
}

const listServices = `-- name: ListServices :many

SELECT id, code, name, price, stock
FROM app.services
WHERE tenant_id = $1 AND on_sale
ORDER BY code
`

type ListServicesRow struct {
	ID    string
	Code  string
	Name  []byte
	Price int64
	Stock int64
}

// Every query filters by tenant explicitly; RLS is the second guard (ADR-005).
func (q *Queries) ListServices(ctx context.Context, tenantID string) ([]ListServicesRow, error) {
	rows, err := q.db.Query(ctx, listServices, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListServicesRow
	for rows.Next() {
		var i ListServicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Price,
			&i.Stock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesByCodes = `-- name: ListServicesByCodes :many
SELECT id, code, name, price, stock
FROM app.services
WHERE tenant_id = $1 AND on_sale AND code = ANY($2::text[])
ORDER BY code
`

type ListServicesByCodesParams struct {
	TenantID string
	Codes    []string
}

type ListServicesByCodesRow struct {
	ID    string
	Code  string
	Name  []byte
	Price int64
	Stock int64
}

func (q *Queries) ListServicesByCodes(ctx context.Context, arg ListServicesByCodesParams) ([]ListServicesByCodesRow, error) {
	rows, err := q.db.Query(ctx, listServicesByCodes, arg.TenantID, arg.Codes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListServicesByCodesRow
	for rows.Next() {
		var i ListServicesByCodesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Price,
			&i.Stock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
