// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: setup.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addServiceStock = `-- name: AddServiceStock :one
UPDATE app.services SET stock = stock + $1, latest_unit_cost = COALESCE($2, latest_unit_cost)
WHERE tenant_id = $3 AND id = $4 RETURNING stock
`

type AddServiceStockParams struct {
	Qty      int64
	UnitCost pgtype.Int8
	TenantID string
	ID       string
}

// Stock changes only here and in DecrementServiceStock, each with a movement row beside it.
func (q *Queries) AddServiceStock(ctx context.Context, arg AddServiceStockParams) (int64, error) {
	row := q.db.QueryRow(ctx, addServiceStock,
		arg.Qty,
		arg.UnitCost,
		arg.TenantID,
		arg.ID,
	)
	var stock int64
	err := row.Scan(&stock)
	return stock, err
}

const buildingStatusCounts = `-- name: BuildingStatusCounts :many
SELECT status, count(*)::int AS n FROM app.units
WHERE tenant_id = $1 AND building_id = $2 AND NOT retired GROUP BY status
`

type BuildingStatusCountsParams struct {
	TenantID   string
	BuildingID string
}

type BuildingStatusCountsRow struct {
	Status string
	N      int32
}

func (q *Queries) BuildingStatusCounts(ctx context.Context, arg BuildingStatusCountsParams) ([]BuildingStatusCountsRow, error) {
	rows, err := q.db.Query(ctx, buildingStatusCounts, arg.TenantID, arg.BuildingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuildingStatusCountsRow
	for rows.Next() {
		var i BuildingStatusCountsRow
		if err := rows.Scan(&i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteServiceItem = `-- name: DeleteServiceItem :exec
DELETE FROM app.services WHERE tenant_id = $1 AND id = $2
`

type DeleteServiceItemParams struct {
	TenantID string
	ID       string
}

func (q *Queries) DeleteServiceItem(ctx context.Context, arg DeleteServiceItemParams) error {
	_, err := q.db.Exec(ctx, deleteServiceItem, arg.TenantID, arg.ID)
	return err
}

const existingRoomCodes = `-- name: ExistingRoomCodes :many
SELECT code FROM app.units WHERE tenant_id = $1 AND code = ANY($2::text[])
`

type ExistingRoomCodesParams struct {
	TenantID string
	Codes    []string
}

func (q *Queries) ExistingRoomCodes(ctx context.Context, arg ExistingRoomCodesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, existingRoomCodes, arg.TenantID, arg.Codes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const firstPropertyID = `-- name: FirstPropertyID :one

SELECT id FROM app.properties WHERE tenant_id = $1 ORDER BY created_at, id LIMIT 1
`

// Setup of buildings, rooms, rates and items (L-A4). Every query filters by tenant; RLS is the second guard.
func (q *Queries) FirstPropertyID(ctx context.Context, tenantID string) (string, error) {
	row := q.db.QueryRow(ctx, firstPropertyID, tenantID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getBuilding = `-- name: GetBuilding :one
SELECT id, code, name FROM app.buildings WHERE tenant_id = $1 AND id = $2 FOR UPDATE
`

type GetBuildingParams struct {
	TenantID string
	ID       string
}

type GetBuildingRow struct {
	ID   string
	Code string
	Name string
}

func (q *Queries) GetBuilding(ctx context.Context, arg GetBuildingParams) (GetBuildingRow, error) {
	row := q.db.QueryRow(ctx, getBuilding, arg.TenantID, arg.ID)
	var i GetBuildingRow
	err := row.Scan(&i.ID, &i.Code, &i.Name)
	return i, err
}

const getFloor = `-- name: GetFloor :one
SELECT id, building_id, level, name FROM app.floors WHERE tenant_id = $1 AND id = $2
`

type GetFloorParams struct {
	TenantID string
	ID       string
}

type GetFloorRow struct {
	ID         string
	BuildingID string
	Level      int32
	Name       pgtype.Text
}

func (q *Queries) GetFloor(ctx context.Context, arg GetFloorParams) (GetFloorRow, error) {
	row := q.db.QueryRow(ctx, getFloor, arg.TenantID, arg.ID)
	var i GetFloorRow
	err := row.Scan(
		&i.ID,
		&i.BuildingID,
		&i.Level,
		&i.Name,
	)
	return i, err
}

const getServiceForUpdate = `-- name: GetServiceForUpdate :one
SELECT id, code, name, price, stock, unit, low_stock_at, on_sale, latest_unit_cost FROM app.services
WHERE tenant_id = $1 AND code = $2 FOR UPDATE
`

type GetServiceForUpdateParams struct {
	TenantID string
	Code     string
}

type GetServiceForUpdateRow struct {
	ID             string
	Code           string
	Name           []byte
	Price          int64
	Stock          int64
	Unit           string
	LowStockAt     int32
	OnSale         bool
	LatestUnitCost pgtype.Int8
}

func (q *Queries) GetServiceForUpdate(ctx context.Context, arg GetServiceForUpdateParams) (GetServiceForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getServiceForUpdate, arg.TenantID, arg.Code)
	var i GetServiceForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Price,
		&i.Stock,
		&i.Unit,
		&i.LowStockAt,
		&i.OnSale,
		&i.LatestUnitCost,
	)
	return i, err
}

const getUnitTypeByCode = `-- name: GetUnitTypeByCode :one
SELECT id, code, name, rate_plan, rate_plan_version, updated_at FROM app.unit_types
WHERE tenant_id = $1 AND code = $2
`

type GetUnitTypeByCodeParams struct {
	TenantID string
	Code     string
}

type GetUnitTypeByCodeRow struct {
	ID              string
	Code            string
	Name            []byte
	RatePlan        []byte
	RatePlanVersion int32
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) GetUnitTypeByCode(ctx context.Context, arg GetUnitTypeByCodeParams) (GetUnitTypeByCodeRow, error) {
	row := q.db.QueryRow(ctx, getUnitTypeByCode, arg.TenantID, arg.Code)
	var i GetUnitTypeByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.RatePlan,
		&i.RatePlanVersion,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRoom = `-- name: InsertRoom :exec
INSERT INTO app.units (id, tenant_id, building_id, floor_id, unit_type_id, code, status, attributes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertRoomParams struct {
	ID         string
	TenantID   string
	BuildingID string
	FloorID    string
	UnitTypeID string
	Code       string
	Status     string
	Attributes []byte
}

func (q *Queries) InsertRoom(ctx context.Context, arg InsertRoomParams) error {
	_, err := q.db.Exec(ctx, insertRoom,
		arg.ID,
		arg.TenantID,
		arg.BuildingID,
		arg.FloorID,
		arg.UnitTypeID,
		arg.Code,
		arg.Status,
		arg.Attributes,
	)
	return err
}

const insertSaleMovement = `-- name: InsertSaleMovement :exec
INSERT INTO app.stock_movements (id, tenant_id, service_id, kind, quantity, ref, actor_id, created_at)
SELECT $1, $2, $3, 'SALE', (0 - $4::int), u.code, $5, $6
FROM app.stays s JOIN app.units u ON u.tenant_id = s.tenant_id AND u.id = s.unit_id
WHERE s.tenant_id = $2 AND s.id = $7
`

type InsertSaleMovementParams struct {
	ID        string
	TenantID  string
	ServiceID string
	Qty       int32
	ActorID   pgtype.Text
	CreatedAt pgtype.Timestamptz
	StayID    string
}

// A sale is one movement beside the guarded decrement: the room code and the person who added the extra.
func (q *Queries) InsertSaleMovement(ctx context.Context, arg InsertSaleMovementParams) error {
	_, err := q.db.Exec(ctx, insertSaleMovement,
		arg.ID,
		arg.TenantID,
		arg.ServiceID,
		arg.Qty,
		arg.ActorID,
		arg.CreatedAt,
		arg.StayID,
	)
	return err
}

const insertServiceItem = `-- name: InsertServiceItem :exec
INSERT INTO app.services (id, tenant_id, code, name, price, stock, unit, low_stock_at, on_sale, latest_unit_cost)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertServiceItemParams struct {
	ID             string
	TenantID       string
	Code           string
	Name           []byte
	Price          int64
	Stock          int64
	Unit           string
	LowStockAt     int32
	OnSale         bool
	LatestUnitCost pgtype.Int8
}

func (q *Queries) InsertServiceItem(ctx context.Context, arg InsertServiceItemParams) error {
	_, err := q.db.Exec(ctx, insertServiceItem,
		arg.ID,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.Price,
		arg.Stock,
		arg.Unit,
		arg.LowStockAt,
		arg.OnSale,
		arg.LatestUnitCost,
	)
	return err
}

const insertStockMovement = `-- name: InsertStockMovement :exec
INSERT INTO app.stock_movements (id, tenant_id, service_id, kind, quantity, unit_cost, ref, actor_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertStockMovementParams struct {
	ID        string
	TenantID  string
	ServiceID string
	Kind      string
	Quantity  int32
	UnitCost  pgtype.Int8
	Ref       pgtype.Text
	ActorID   pgtype.Text
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertStockMovement(ctx context.Context, arg InsertStockMovementParams) error {
	_, err := q.db.Exec(ctx, insertStockMovement,
		arg.ID,
		arg.TenantID,
		arg.ServiceID,
		arg.Kind,
		arg.Quantity,
		arg.UnitCost,
		arg.Ref,
		arg.ActorID,
		arg.CreatedAt,
	)
	return err
}

const insertStocktake = `-- name: InsertStocktake :exec
INSERT INTO app.stocktakes (id, tenant_id, actor_id, note, value_difference, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertStocktakeParams struct {
	ID              string
	TenantID        string
	ActorID         pgtype.Text
	Note            pgtype.Text
	ValueDifference int64
	CreatedAt       pgtype.Timestamptz
}

func (q *Queries) InsertStocktake(ctx context.Context, arg InsertStocktakeParams) error {
	_, err := q.db.Exec(ctx, insertStocktake,
		arg.ID,
		arg.TenantID,
		arg.ActorID,
		arg.Note,
		arg.ValueDifference,
		arg.CreatedAt,
	)
	return err
}

const listStockMovements = `-- name: ListStockMovements :many
SELECT m.id, m.kind, m.quantity, m.unit_cost, m.ref, m.created_at, COALESCE(u.name, '') AS actor_name
FROM app.stock_movements m
LEFT JOIN app.users u ON u.tenant_id = m.tenant_id AND u.id = m.actor_id
WHERE m.tenant_id = $1 AND m.service_id = $2
  AND ($3::text IS NULL OR m.kind = $3)
  AND ($4::timestamptz IS NULL OR (m.created_at, m.id) < ($4::timestamptz, $5::text))
ORDER BY m.created_at DESC, m.id DESC
LIMIT $6
`

type ListStockMovementsParams struct {
	TenantID  string
	ServiceID string
	Kind      pgtype.Text
	BeforeAt  pgtype.Timestamptz
	BeforeID  pgtype.Text
	PageSize  int32
}

type ListStockMovementsRow struct {
	ID        string
	Kind      string
	Quantity  int32
	UnitCost  pgtype.Int8
	Ref       pgtype.Text
	CreatedAt pgtype.Timestamptz
	ActorName string
}

func (q *Queries) ListStockMovements(ctx context.Context, arg ListStockMovementsParams) ([]ListStockMovementsRow, error) {
	rows, err := q.db.Query(ctx, listStockMovements,
		arg.TenantID,
		arg.ServiceID,
		arg.Kind,
		arg.BeforeAt,
		arg.BeforeID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStockMovementsRow
	for rows.Next() {
		var i ListStockMovementsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Quantity,
			&i.UnitCost,
			&i.Ref,
			&i.CreatedAt,
			&i.ActorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnitTypes = `-- name: ListUnitTypes :many
SELECT id, code, name, rate_plan, rate_plan_version, updated_at FROM app.unit_types
WHERE tenant_id = $1 ORDER BY code
`

type ListUnitTypesRow struct {
	ID              string
	Code            string
	Name            []byte
	RatePlan        []byte
	RatePlanVersion int32
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) ListUnitTypes(ctx context.Context, tenantID string) ([]ListUnitTypesRow, error) {
	rows, err := q.db.Query(ctx, listUnitTypes, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnitTypesRow
	for rows.Next() {
		var i ListUnitTypesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.RatePlan,
			&i.RatePlanVersion,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRoomForSetup = `-- name: LockRoomForSetup :one
SELECT u.id, u.code, u.building_id, u.floor_id, f.name AS floor_name, u.unit_type_id, u.status, u.retired, u.attributes, f.level AS floor_level,
       ut.code AS unit_type_code, ut.name AS unit_type_name,
       EXISTS (SELECT 1 FROM app.stays s WHERE s.tenant_id = u.tenant_id AND s.unit_id = u.id AND s.status = 'ACTIVE') AS has_guest
FROM app.units u
JOIN app.floors f ON f.tenant_id = u.tenant_id AND f.id = u.floor_id
JOIN app.unit_types ut ON ut.tenant_id = u.tenant_id AND ut.id = u.unit_type_id
WHERE u.tenant_id = $1 AND u.id = $2
FOR UPDATE OF u
`

type LockRoomForSetupParams struct {
	TenantID string
	ID       string
}

type LockRoomForSetupRow struct {
	ID           string
	Code         string
	BuildingID   string
	FloorID      string
	FloorName    pgtype.Text
	UnitTypeID   string
	Status       string
	Retired      bool
	Attributes   []byte
	FloorLevel   int32
	UnitTypeCode string
	UnitTypeName []byte
	HasGuest     bool
}

func (q *Queries) LockRoomForSetup(ctx context.Context, arg LockRoomForSetupParams) (LockRoomForSetupRow, error) {
	row := q.db.QueryRow(ctx, lockRoomForSetup, arg.TenantID, arg.ID)
	var i LockRoomForSetupRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.BuildingID,
		&i.FloorID,
		&i.FloorName,
		&i.UnitTypeID,
		&i.Status,
		&i.Retired,
		&i.Attributes,
		&i.FloorLevel,
		&i.UnitTypeCode,
		&i.UnitTypeName,
		&i.HasGuest,
	)
	return i, err
}

const maxFloorLevel = `-- name: MaxFloorLevel :one
SELECT COALESCE(max(level), 0)::int FROM app.floors WHERE tenant_id = $1 AND building_id = $2
`

type MaxFloorLevelParams struct {
	TenantID   string
	BuildingID string
}

func (q *Queries) MaxFloorLevel(ctx context.Context, arg MaxFloorLevelParams) (int32, error) {
	row := q.db.QueryRow(ctx, maxFloorLevel, arg.TenantID, arg.BuildingID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const serviceCodeTaken = `-- name: ServiceCodeTaken :one
SELECT EXISTS (SELECT 1 FROM app.services WHERE tenant_id = $1 AND code = $2)
`

type ServiceCodeTakenParams struct {
	TenantID string
	Code     string
}

func (q *Queries) ServiceCodeTaken(ctx context.Context, arg ServiceCodeTakenParams) (bool, error) {
	row := q.db.QueryRow(ctx, serviceCodeTaken, arg.TenantID, arg.Code)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const serviceHasSales = `-- name: ServiceHasSales :one
SELECT EXISTS (SELECT 1 FROM app.stay_extras WHERE tenant_id = $1 AND service_id = $2)
`

type ServiceHasSalesParams struct {
	TenantID  string
	ServiceID string
}

func (q *Queries) ServiceHasSales(ctx context.Context, arg ServiceHasSalesParams) (bool, error) {
	row := q.db.QueryRow(ctx, serviceHasSales, arg.TenantID, arg.ServiceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateBuildingName = `-- name: UpdateBuildingName :exec
UPDATE app.buildings SET name = $1 WHERE tenant_id = $2 AND id = $3
`

type UpdateBuildingNameParams struct {
	Name     string
	TenantID string
	ID       string
}

func (q *Queries) UpdateBuildingName(ctx context.Context, arg UpdateBuildingNameParams) error {
	_, err := q.db.Exec(ctx, updateBuildingName, arg.Name, arg.TenantID, arg.ID)
	return err
}

const updateRoomRow = `-- name: UpdateRoomRow :exec
UPDATE app.units SET code = $1, unit_type_id = $2, status = $3, retired = $4, attributes = $5
WHERE tenant_id = $6 AND id = $7
`

type UpdateRoomRowParams struct {
	Code       string
	UnitTypeID string
	Status     string
	Retired    bool
	Attributes []byte
	TenantID   string
	ID         string
}

func (q *Queries) UpdateRoomRow(ctx context.Context, arg UpdateRoomRowParams) error {
	_, err := q.db.Exec(ctx, updateRoomRow,
		arg.Code,
		arg.UnitTypeID,
		arg.Status,
		arg.Retired,
		arg.Attributes,
		arg.TenantID,
		arg.ID,
	)
	return err
}

const updateServiceItem = `-- name: UpdateServiceItem :exec
UPDATE app.services
SET name = COALESCE($1::jsonb, name), price = COALESCE($2, price), unit = COALESCE($3, unit),
    low_stock_at = COALESCE($4, low_stock_at), on_sale = COALESCE($5, on_sale)
WHERE tenant_id = $6 AND id = $7
`

type UpdateServiceItemParams struct {
	Name       []byte
	Price      pgtype.Int8
	Unit       pgtype.Text
	LowStockAt pgtype.Int4
	OnSale     pgtype.Bool
	TenantID   string
	ID         string
}

func (q *Queries) UpdateServiceItem(ctx context.Context, arg UpdateServiceItemParams) error {
	_, err := q.db.Exec(ctx, updateServiceItem,
		arg.Name,
		arg.Price,
		arg.Unit,
		arg.LowStockAt,
		arg.OnSale,
		arg.TenantID,
		arg.ID,
	)
	return err
}

const updateUnitTypeRatePlan = `-- name: UpdateUnitTypeRatePlan :exec
UPDATE app.unit_types SET rate_plan = $1, rate_plan_version = $2, updated_at = $3
WHERE tenant_id = $4 AND id = $5
`

type UpdateUnitTypeRatePlanParams struct {
	RatePlan        []byte
	RatePlanVersion int32
	Now             pgtype.Timestamptz
	TenantID        string
	ID              string
}

func (q *Queries) UpdateUnitTypeRatePlan(ctx context.Context, arg UpdateUnitTypeRatePlanParams) error {
	_, err := q.db.Exec(ctx, updateUnitTypeRatePlan,
		arg.RatePlan,
		arg.RatePlanVersion,
		arg.Now,
		arg.TenantID,
		arg.ID,
	)
	return err
}
