// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shifts.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeShift = `-- name: CloseShift :execrows
UPDATE app.shifts SET status = 'CLOSED', closed_at = $1, expected_cash = $2, counted_cash = $3,
       difference = $4, reason = $5, reason_recorded_at = $6,
       float_left = $7, handover_to_user_id = $8, counts = $9
WHERE tenant_id = $10 AND id = $11 AND status = 'OPEN'
`

type CloseShiftParams struct {
	ClosedAt         pgtype.Timestamptz
	ExpectedCash     pgtype.Int8
	CountedCash      pgtype.Int8
	Difference       pgtype.Int8
	Reason           pgtype.Text
	ReasonRecordedAt pgtype.Timestamptz
	FloatLeft        pgtype.Int8
	HandoverToUserID pgtype.Text
	Counts           []byte
	TenantID         string
	ShiftID          string
}

func (q *Queries) CloseShift(ctx context.Context, arg CloseShiftParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeShift,
		arg.ClosedAt,
		arg.ExpectedCash,
		arg.CountedCash,
		arg.Difference,
		arg.Reason,
		arg.ReasonRecordedAt,
		arg.FloatLeft,
		arg.HandoverToUserID,
		arg.Counts,
		arg.TenantID,
		arg.ShiftID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getShiftByID = `-- name: GetShiftByID :one
SELECT s.id, s.user_id, u.name AS user_name, s.status, s.shift_code, s.opened_at, s.closed_at, s.opening_float,
       s.expected_cash, s.counted_cash, s.difference, s.reason, s.reason_recorded_at, s.float_left
FROM app.shifts s JOIN app.users u ON u.tenant_id = s.tenant_id AND u.id = s.user_id
WHERE s.tenant_id = $1 AND s.id = $2
`

type GetShiftByIDParams struct {
	TenantID string
	ShiftID  string
}

type GetShiftByIDRow struct {
	ID               string
	UserID           string
	UserName         string
	Status           string
	ShiftCode        string
	OpenedAt         pgtype.Timestamptz
	ClosedAt         pgtype.Timestamptz
	OpeningFloat     int64
	ExpectedCash     pgtype.Int8
	CountedCash      pgtype.Int8
	Difference       pgtype.Int8
	Reason           pgtype.Text
	ReasonRecordedAt pgtype.Timestamptz
	FloatLeft        pgtype.Int8
}

func (q *Queries) GetShiftByID(ctx context.Context, arg GetShiftByIDParams) (GetShiftByIDRow, error) {
	row := q.db.QueryRow(ctx, getShiftByID, arg.TenantID, arg.ShiftID)
	var i GetShiftByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserName,
		&i.Status,
		&i.ShiftCode,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.OpeningFloat,
		&i.ExpectedCash,
		&i.CountedCash,
		&i.Difference,
		&i.Reason,
		&i.ReasonRecordedAt,
		&i.FloatLeft,
	)
	return i, err
}

const insertCashEntry = `-- name: InsertCashEntry :exec
INSERT INTO app.cash_entries (id, tenant_id, shift_id, kind, amount, stay_id, payment_id, description, created_by, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
        $9, $10)
`

type InsertCashEntryParams struct {
	ID          string
	TenantID    string
	ShiftID     string
	Kind        string
	Amount      int64
	StayID      pgtype.Text
	PaymentID   pgtype.Text
	Description pgtype.Text
	CreatedBy   pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) InsertCashEntry(ctx context.Context, arg InsertCashEntryParams) error {
	_, err := q.db.Exec(ctx, insertCashEntry,
		arg.ID,
		arg.TenantID,
		arg.ShiftID,
		arg.Kind,
		arg.Amount,
		arg.StayID,
		arg.PaymentID,
		arg.Description,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const insertShift = `-- name: InsertShift :execrows
INSERT INTO app.shifts (id, tenant_id, user_id, shift_code, opened_at, opening_float)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (tenant_id, user_id) WHERE status = 'OPEN' DO NOTHING
`

type InsertShiftParams struct {
	ID           string
	TenantID     string
	UserID       string
	ShiftCode    string
	OpenedAt     pgtype.Timestamptz
	OpeningFloat int64
}

// A race between two first cash actions of one user ends in DO NOTHING for the loser, who then reads the winner's shift.
func (q *Queries) InsertShift(ctx context.Context, arg InsertShiftParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertShift,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.ShiftCode,
		arg.OpenedAt,
		arg.OpeningFloat,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lastFloatLeft = `-- name: LastFloatLeft :one
SELECT float_left FROM app.shifts
WHERE tenant_id = $1 AND status = 'CLOSED'
ORDER BY closed_at DESC, id DESC LIMIT 1
`

// The float left in the drawer by the shift closed last, which the next shift opens with.
func (q *Queries) LastFloatLeft(ctx context.Context, tenantID string) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, lastFloatLeft, tenantID)
	var float_left pgtype.Int8
	err := row.Scan(&float_left)
	return float_left, err
}

const listClosedShifts = `-- name: ListClosedShifts :many
SELECT s.id, u.name AS user_name, s.shift_code, s.opened_at, s.closed_at, s.difference
FROM app.shifts s JOIN app.users u ON u.tenant_id = s.tenant_id AND u.id = s.user_id
WHERE s.tenant_id = $1 AND s.status = 'CLOSED'
  AND ($2::timestamptz IS NULL OR (s.closed_at >= $2::timestamptz AND s.closed_at < $3::timestamptz))
  AND ($4::text IS NULL OR s.user_id = $4::text)
  AND (NOT $5::boolean OR s.difference <> 0)
  AND ($6::timestamptz IS NULL OR (s.closed_at, s.id) < ($6::timestamptz, $7::text))
ORDER BY s.closed_at DESC, s.id DESC
LIMIT $8
`

type ListClosedShiftsParams struct {
	TenantID        string
	FromAt          pgtype.Timestamptz
	ToAt            pgtype.Timestamptz
	UserID          pgtype.Text
	OnlyDifferences bool
	CursorAt        pgtype.Timestamptz
	CursorID        pgtype.Text
	RowLimit        int32
}

type ListClosedShiftsRow struct {
	ID         string
	UserName   string
	ShiftCode  string
	OpenedAt   pgtype.Timestamptz
	ClosedAt   pgtype.Timestamptz
	Difference pgtype.Int8
}

func (q *Queries) ListClosedShifts(ctx context.Context, arg ListClosedShiftsParams) ([]ListClosedShiftsRow, error) {
	rows, err := q.db.Query(ctx, listClosedShifts,
		arg.TenantID,
		arg.FromAt,
		arg.ToAt,
		arg.UserID,
		arg.OnlyDifferences,
		arg.CursorAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClosedShiftsRow
	for rows.Next() {
		var i ListClosedShiftsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserName,
			&i.ShiftCode,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.Difference,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShiftCashIn = `-- name: ListShiftCashIn :many
SELECT un.code AS room_code, st.rental_type, e.created_at, e.amount
FROM app.cash_entries e
JOIN app.stays st ON st.tenant_id = e.tenant_id AND st.id = e.stay_id
JOIN app.units un ON un.tenant_id = st.tenant_id AND un.id = st.unit_id
WHERE e.tenant_id = $1 AND e.shift_id = $2 AND e.kind IN ('DEPOSIT', 'PAYMENT')
ORDER BY e.created_at, e.id
`

type ListShiftCashInParams struct {
	TenantID string
	ShiftID  string
}

type ListShiftCashInRow struct {
	RoomCode   string
	RentalType string
	CreatedAt  pgtype.Timestamptz
	Amount     int64
}

func (q *Queries) ListShiftCashIn(ctx context.Context, arg ListShiftCashInParams) ([]ListShiftCashInRow, error) {
	rows, err := q.db.Query(ctx, listShiftCashIn, arg.TenantID, arg.ShiftID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShiftCashInRow
	for rows.Next() {
		var i ListShiftCashInRow
		if err := rows.Scan(
			&i.RoomCode,
			&i.RentalType,
			&i.CreatedAt,
			&i.Amount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOpenShift = `-- name: LockOpenShift :one
SELECT s.id, s.user_id, u.name AS user_name, s.status, s.shift_code, s.opened_at, s.closed_at, s.opening_float
FROM app.shifts s JOIN app.users u ON u.tenant_id = s.tenant_id AND u.id = s.user_id
WHERE s.tenant_id = $1 AND s.user_id = $2 AND s.status = 'OPEN'
FOR UPDATE OF s
`

type LockOpenShiftParams struct {
	TenantID string
	UserID   string
}

type LockOpenShiftRow struct {
	ID           string
	UserID       string
	UserName     string
	Status       string
	ShiftCode    string
	OpenedAt     pgtype.Timestamptz
	ClosedAt     pgtype.Timestamptz
	OpeningFloat int64
}

func (q *Queries) LockOpenShift(ctx context.Context, arg LockOpenShiftParams) (LockOpenShiftRow, error) {
	row := q.db.QueryRow(ctx, lockOpenShift, arg.TenantID, arg.UserID)
	var i LockOpenShiftRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserName,
		&i.Status,
		&i.ShiftCode,
		&i.OpenedAt,
		&i.ClosedAt,
		&i.OpeningFloat,
	)
	return i, err
}

const shiftCash = `-- name: ShiftCash :one
SELECT coalesce(sum(amount) FILTER (WHERE kind IN ('DEPOSIT', 'PAYMENT')), 0)::bigint AS cash_in,
       coalesce(sum(amount) FILTER (WHERE kind IN ('REFUND', 'PAYOUT')), 0)::bigint AS cash_out
FROM app.cash_entries WHERE tenant_id = $1 AND shift_id = $2
`

type ShiftCashParams struct {
	TenantID string
	ShiftID  string
}

type ShiftCashRow struct {
	CashIn  int64
	CashOut int64
}

func (q *Queries) ShiftCash(ctx context.Context, arg ShiftCashParams) (ShiftCashRow, error) {
	row := q.db.QueryRow(ctx, shiftCash, arg.TenantID, arg.ShiftID)
	var i ShiftCashRow
	err := row.Scan(&i.CashIn, &i.CashOut)
	return i, err
}

const staffMonthStats = `-- name: StaffMonthStats :one
SELECT count(*)::bigint AS shifts_with_difference,
       coalesce(sum(-difference) FILTER (WHERE difference < 0), 0)::bigint AS total_short
FROM app.shifts
WHERE tenant_id = $1 AND user_id = $2 AND status = 'CLOSED' AND difference <> 0
  AND closed_at >= $3 AND closed_at < $4
`

type StaffMonthStatsParams struct {
	TenantID string
	UserID   string
	FromAt   pgtype.Timestamptz
	ToAt     pgtype.Timestamptz
}

type StaffMonthStatsRow struct {
	ShiftsWithDifference int64
	TotalShort           int64
}

func (q *Queries) StaffMonthStats(ctx context.Context, arg StaffMonthStatsParams) (StaffMonthStatsRow, error) {
	row := q.db.QueryRow(ctx, staffMonthStats,
		arg.TenantID,
		arg.UserID,
		arg.FromAt,
		arg.ToAt,
	)
	var i StaffMonthStatsRow
	err := row.Scan(&i.ShiftsWithDifference, &i.TotalShort)
	return i, err
}

const transfersBetween = `-- name: TransfersBetween :one
SELECT coalesce(sum(coalesce(received_amount, amount)), 0)::bigint AS total
FROM app.payments
WHERE tenant_id = $1 AND method = 'TRANSFER' AND status = 'PAID' AND paid_at >= $2 AND paid_at < $3
`

type TransfersBetweenParams struct {
	TenantID string
	FromAt   pgtype.Timestamptz
	ToAt     pgtype.Timestamptz
}

func (q *Queries) TransfersBetween(ctx context.Context, arg TransfersBetweenParams) (int64, error) {
	row := q.db.QueryRow(ctx, transfersBetween, arg.TenantID, arg.FromAt, arg.ToAt)
	var total int64
	err := row.Scan(&total)
	return total, err
}
