// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: staff.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const buildingExists = `-- name: BuildingExists :one
SELECT EXISTS (SELECT 1 FROM app.buildings WHERE tenant_id = $1 AND id = $2)
`

type BuildingExistsParams struct {
	TenantID string
	ID       string
}

func (q *Queries) BuildingExists(ctx context.Context, arg BuildingExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, buildingExists, arg.TenantID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM app.sessions WHERE tenant_id = $1 AND user_id = $2
`

type DeleteUserSessionsParams struct {
	TenantID string
	UserID   string
}

func (q *Queries) DeleteUserSessions(ctx context.Context, arg DeleteUserSessionsParams) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, arg.TenantID, arg.UserID)
	return err
}

const getBuildingPermission = `-- name: GetBuildingPermission :one
SELECT level FROM app.building_permissions WHERE tenant_id = $1 AND user_id = $2 AND building_id = $3
`

type GetBuildingPermissionParams struct {
	TenantID   string
	UserID     string
	BuildingID string
}

func (q *Queries) GetBuildingPermission(ctx context.Context, arg GetBuildingPermissionParams) (string, error) {
	row := q.db.QueryRow(ctx, getBuildingPermission, arg.TenantID, arg.UserID, arg.BuildingID)
	var level string
	err := row.Scan(&level)
	return level, err
}

const getUserRoleStatus = `-- name: GetUserRoleStatus :one
SELECT role, status, app_access, name FROM app.users WHERE tenant_id = $1 AND id = $2
`

type GetUserRoleStatusParams struct {
	TenantID string
	ID       string
}

type GetUserRoleStatusRow struct {
	Role      string
	Status    string
	AppAccess string
	Name      string
}

func (q *Queries) GetUserRoleStatus(ctx context.Context, arg GetUserRoleStatusParams) (GetUserRoleStatusRow, error) {
	row := q.db.QueryRow(ctx, getUserRoleStatus, arg.TenantID, arg.ID)
	var i GetUserRoleStatusRow
	err := row.Scan(
		&i.Role,
		&i.Status,
		&i.AppAccess,
		&i.Name,
	)
	return i, err
}

const grantAllBuildings = `-- name: GrantAllBuildings :exec
INSERT INTO app.building_permissions (tenant_id, user_id, building_id, level)
SELECT b.tenant_id, $1, b.id, $2 FROM app.buildings b WHERE b.tenant_id = $3
ON CONFLICT (tenant_id, user_id, building_id) DO NOTHING
`

type GrantAllBuildingsParams struct {
	UserID   string
	Level    string
	TenantID string
}

func (q *Queries) GrantAllBuildings(ctx context.Context, arg GrantAllBuildingsParams) error {
	_, err := q.db.Exec(ctx, grantAllBuildings, arg.UserID, arg.Level, arg.TenantID)
	return err
}

const insertStaffProfile = `-- name: InsertStaffProfile :exec
INSERT INTO app.staff_profiles (tenant_id, user_id, phone, position, pay_type, rate, fixed_allowance, standard_shifts, start_date, annual_leave_days)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertStaffProfileParams struct {
	TenantID        string
	UserID          string
	Phone           pgtype.Text
	Position        string
	PayType         string
	Rate            int64
	FixedAllowance  int64
	StandardShifts  int32
	StartDate       pgtype.Date
	AnnualLeaveDays int32
}

func (q *Queries) InsertStaffProfile(ctx context.Context, arg InsertStaffProfileParams) error {
	_, err := q.db.Exec(ctx, insertStaffProfile,
		arg.TenantID,
		arg.UserID,
		arg.Phone,
		arg.Position,
		arg.PayType,
		arg.Rate,
		arg.FixedAllowance,
		arg.StandardShifts,
		arg.StartDate,
		arg.AnnualLeaveDays,
	)
	return err
}

const insertStaffUser = `-- name: InsertStaffUser :exec
INSERT INTO app.users (id, tenant_id, name, role, locale, app_access, username)
VALUES ($1, $2, $3, $4, 'vi', $5, $6)
`

type InsertStaffUserParams struct {
	ID        string
	TenantID  string
	Name      string
	Role      string
	AppAccess string
	Username  pgtype.Text
}

func (q *Queries) InsertStaffUser(ctx context.Context, arg InsertStaffUserParams) error {
	_, err := q.db.Exec(ctx, insertStaffUser,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Role,
		arg.AppAccess,
		arg.Username,
	)
	return err
}

const listPermissionUsers = `-- name: ListPermissionUsers :many
SELECT id, name, role FROM app.users
WHERE tenant_id = $1 AND status <> 'REMOVED' AND app_access <> 'NONE' AND role <> 'OWNER'
ORDER BY name, id
`

type ListPermissionUsersRow struct {
	ID   string
	Name string
	Role string
}

func (q *Queries) ListPermissionUsers(ctx context.Context, tenantID string) ([]ListPermissionUsersRow, error) {
	rows, err := q.db.Query(ctx, listPermissionUsers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPermissionUsersRow
	for rows.Next() {
		var i ListPermissionUsersRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaffBuildingLevels = `-- name: ListStaffBuildingLevels :many
SELECT user_id, building_id, level FROM app.building_permissions WHERE tenant_id = $1 ORDER BY user_id, building_id
`

type ListStaffBuildingLevelsRow struct {
	UserID     string
	BuildingID string
	Level      string
}

func (q *Queries) ListStaffBuildingLevels(ctx context.Context, tenantID string) ([]ListStaffBuildingLevelsRow, error) {
	rows, err := q.db.Query(ctx, listStaffBuildingLevels, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaffBuildingLevelsRow
	for rows.Next() {
		var i ListStaffBuildingLevelsRow
		if err := rows.Scan(&i.UserID, &i.BuildingID, &i.Level); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaffRows = `-- name: ListStaffRows :many

SELECT u.id, u.name, u.role, u.app_access, u.status, u.username,
       p.phone, p.position, p.pay_type, p.rate, p.fixed_allowance, p.standard_shifts, p.start_date, p.annual_leave_days,
       c.locked_until,
       (SELECT max(s.created_at) FROM app.sessions s WHERE s.tenant_id = u.tenant_id AND s.user_id = u.id)::timestamptz AS last_activity_at
FROM app.users u
JOIN app.staff_profiles p ON p.tenant_id = u.tenant_id AND p.user_id = u.id
LEFT JOIN app.pin_credentials c ON c.tenant_id = u.tenant_id AND c.user_id = u.id
WHERE u.tenant_id = $1
  AND ($2::text IS NULL OR p.position = $2)
  AND ($3::text IS NULL OR u.id = $3)
ORDER BY (u.status = 'REMOVED'), u.name, u.id
`

type ListStaffRowsParams struct {
	TenantID string
	Position pgtype.Text
	UserID   pgtype.Text
}

type ListStaffRowsRow struct {
	ID              string
	Name            string
	Role            string
	AppAccess       string
	Status          string
	Username        pgtype.Text
	Phone           pgtype.Text
	Position        string
	PayType         string
	Rate            int64
	FixedAllowance  int64
	StandardShifts  int32
	StartDate       pgtype.Date
	AnnualLeaveDays int32
	LockedUntil     pgtype.Timestamptz
	LastActivityAt  pgtype.Timestamptz
}

// Staff are users with a staff_profile; the owner has none and is never listed.
func (q *Queries) ListStaffRows(ctx context.Context, arg ListStaffRowsParams) ([]ListStaffRowsRow, error) {
	rows, err := q.db.Query(ctx, listStaffRows, arg.TenantID, arg.Position, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaffRowsRow
	for rows.Next() {
		var i ListStaffRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.AppAccess,
			&i.Status,
			&i.Username,
			&i.Phone,
			&i.Position,
			&i.PayType,
			&i.Rate,
			&i.FixedAllowance,
			&i.StandardShifts,
			&i.StartDate,
			&i.AnnualLeaveDays,
			&i.LockedUntil,
			&i.LastActivityAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserBuildingLevels = `-- name: ListUserBuildingLevels :many
SELECT building_id, level FROM app.building_permissions WHERE tenant_id = $1 AND user_id = $2
`

type ListUserBuildingLevelsParams struct {
	TenantID string
	UserID   string
}

type ListUserBuildingLevelsRow struct {
	BuildingID string
	Level      string
}

func (q *Queries) ListUserBuildingLevels(ctx context.Context, arg ListUserBuildingLevelsParams) ([]ListUserBuildingLevelsRow, error) {
	rows, err := q.db.Query(ctx, listUserBuildingLevels, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserBuildingLevelsRow
	for rows.Next() {
		var i ListUserBuildingLevelsRow
		if err := rows.Scan(&i.BuildingID, &i.Level); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setStaffStatus = `-- name: SetStaffStatus :execrows
UPDATE app.users SET status = $1
WHERE users.tenant_id = $2 AND users.id = $3 AND users.status <> 'REMOVED'
  AND EXISTS (SELECT 1 FROM app.staff_profiles p WHERE p.tenant_id = users.tenant_id AND p.user_id = users.id)
`

type SetStaffStatusParams struct {
	Status   string
	TenantID string
	ID       string
}

func (q *Queries) SetStaffStatus(ctx context.Context, arg SetStaffStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setStaffStatus, arg.Status, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStaffProfile = `-- name: UpdateStaffProfile :exec
UPDATE app.staff_profiles
SET phone = COALESCE($1, phone), position = COALESCE($2, position),
    pay_type = COALESCE($3, pay_type), rate = COALESCE($4, rate),
    fixed_allowance = COALESCE($5, fixed_allowance),
    standard_shifts = COALESCE($6, standard_shifts),
    start_date = COALESCE($7, start_date),
    annual_leave_days = COALESCE($8, annual_leave_days)
WHERE tenant_id = $9 AND user_id = $10
`

type UpdateStaffProfileParams struct {
	Phone           pgtype.Text
	Position        pgtype.Text
	PayType         pgtype.Text
	Rate            pgtype.Int8
	FixedAllowance  pgtype.Int8
	StandardShifts  pgtype.Int4
	StartDate       pgtype.Date
	AnnualLeaveDays pgtype.Int4
	TenantID        string
	UserID          string
}

func (q *Queries) UpdateStaffProfile(ctx context.Context, arg UpdateStaffProfileParams) error {
	_, err := q.db.Exec(ctx, updateStaffProfile,
		arg.Phone,
		arg.Position,
		arg.PayType,
		arg.Rate,
		arg.FixedAllowance,
		arg.StandardShifts,
		arg.StartDate,
		arg.AnnualLeaveDays,
		arg.TenantID,
		arg.UserID,
	)
	return err
}

const updateStaffUser = `-- name: UpdateStaffUser :execrows
UPDATE app.users
SET name = COALESCE($1, name), role = COALESCE($2, role), app_access = COALESCE($3, app_access)
WHERE users.tenant_id = $4 AND users.id = $5 AND users.status <> 'REMOVED'
  AND EXISTS (SELECT 1 FROM app.staff_profiles p WHERE p.tenant_id = users.tenant_id AND p.user_id = users.id)
`

type UpdateStaffUserParams struct {
	Name      pgtype.Text
	Role      pgtype.Text
	AppAccess pgtype.Text
	TenantID  string
	ID        string
}

func (q *Queries) UpdateStaffUser(ctx context.Context, arg UpdateStaffUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStaffUser,
		arg.Name,
		arg.Role,
		arg.AppAccess,
		arg.TenantID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertBuildingPermission = `-- name: UpsertBuildingPermission :exec
INSERT INTO app.building_permissions (tenant_id, user_id, building_id, level, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, user_id, building_id) DO UPDATE SET level = EXCLUDED.level, updated_at = EXCLUDED.updated_at
`

type UpsertBuildingPermissionParams struct {
	TenantID   string
	UserID     string
	BuildingID string
	Level      string
	Now        pgtype.Timestamptz
}

func (q *Queries) UpsertBuildingPermission(ctx context.Context, arg UpsertBuildingPermissionParams) error {
	_, err := q.db.Exec(ctx, upsertBuildingPermission,
		arg.TenantID,
		arg.UserID,
		arg.BuildingID,
		arg.Level,
		arg.Now,
	)
	return err
}
