// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stays.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCheckInRoom = `-- name: GetCheckInRoom :one

SELECT u.id, u.code, u.building_id, u.status, ut.rate_plan, ut.rate_plan_version
FROM app.units u
JOIN app.unit_types ut ON ut.tenant_id = u.tenant_id AND ut.id = u.unit_type_id
WHERE u.tenant_id = $1 AND u.id = $2
`

type GetCheckInRoomParams struct {
	TenantID string
	UnitID   string
}

type GetCheckInRoomRow struct {
	ID              string
	Code            string
	BuildingID      string
	Status          string
	RatePlan        []byte
	RatePlanVersion int32
}

// Every query filters by tenant explicitly; RLS is the second guard (ADR-005).
func (q *Queries) GetCheckInRoom(ctx context.Context, arg GetCheckInRoomParams) (GetCheckInRoomRow, error) {
	row := q.db.QueryRow(ctx, getCheckInRoom, arg.TenantID, arg.UnitID)
	var i GetCheckInRoomRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.BuildingID,
		&i.Status,
		&i.RatePlan,
		&i.RatePlanVersion,
	)
	return i, err
}

const getStayByID = `-- name: GetStayByID :one
SELECT s.id, s.unit_id, u.code AS room_code, u.building_id, s.rental_type, s.status, s.guest_name, s.guest_phone,
       s.id_number_enc, s.deposit, s.check_in_at, s.check_out_at, s.rate_plan_snapshot
FROM app.stays s
JOIN app.units u ON u.tenant_id = s.tenant_id AND u.id = s.unit_id
WHERE s.tenant_id = $1 AND s.id = $2
`

type GetStayByIDParams struct {
	TenantID string
	StayID   string
}

type GetStayByIDRow struct {
	ID               string
	UnitID           string
	RoomCode         string
	BuildingID       string
	RentalType       string
	Status           string
	GuestName        string
	GuestPhone       string
	IDNumberEnc      []byte
	Deposit          int64
	CheckInAt        pgtype.Timestamptz
	CheckOutAt       pgtype.Timestamptz
	RatePlanSnapshot []byte
}

func (q *Queries) GetStayByID(ctx context.Context, arg GetStayByIDParams) (GetStayByIDRow, error) {
	row := q.db.QueryRow(ctx, getStayByID, arg.TenantID, arg.StayID)
	var i GetStayByIDRow
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.RoomCode,
		&i.BuildingID,
		&i.RentalType,
		&i.Status,
		&i.GuestName,
		&i.GuestPhone,
		&i.IDNumberEnc,
		&i.Deposit,
		&i.CheckInAt,
		&i.CheckOutAt,
		&i.RatePlanSnapshot,
	)
	return i, err
}

const insertStay = `-- name: InsertStay :exec
INSERT INTO app.stays (id, tenant_id, unit_id, rental_type, status, deposit, check_in_at,
                       rate_plan_snapshot, rate_plan_schema, guest_name, guest_phone, id_number_enc)
VALUES ($1, $2, $3, $4, 'ACTIVE', $5, $6,
        $7, $8, $9, $10, $11)
`

type InsertStayParams struct {
	ID               string
	TenantID         string
	UnitID           string
	RentalType       string
	Deposit          int64
	CheckInAt        pgtype.Timestamptz
	RatePlanSnapshot []byte
	RatePlanSchema   int16
	GuestName        string
	GuestPhone       string
	IDNumberEnc      []byte
}

// check_in_at comes from the argument (the server clock of the use case), never from now().
func (q *Queries) InsertStay(ctx context.Context, arg InsertStayParams) error {
	_, err := q.db.Exec(ctx, insertStay,
		arg.ID,
		arg.TenantID,
		arg.UnitID,
		arg.RentalType,
		arg.Deposit,
		arg.CheckInAt,
		arg.RatePlanSnapshot,
		arg.RatePlanSchema,
		arg.GuestName,
		arg.GuestPhone,
		arg.IDNumberEnc,
	)
	return err
}

const listStayExtras = `-- name: ListStayExtras :many
SELECT sv.id AS service_id, sv.name AS service_name, e.quantity, e.unit_amount
FROM app.stay_extras e
JOIN app.services sv ON sv.tenant_id = e.tenant_id AND sv.id = e.service_id
WHERE e.tenant_id = $1 AND e.stay_id = $2
ORDER BY e.created_at, e.id
`

type ListStayExtrasParams struct {
	TenantID string
	StayID   string
}

type ListStayExtrasRow struct {
	ServiceID   string
	ServiceName []byte
	Quantity    int32
	UnitAmount  int64
}

func (q *Queries) ListStayExtras(ctx context.Context, arg ListStayExtrasParams) ([]ListStayExtrasRow, error) {
	rows, err := q.db.Query(ctx, listStayExtras, arg.TenantID, arg.StayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStayExtrasRow
	for rows.Next() {
		var i ListStayExtrasRow
		if err := rows.Scan(
			&i.ServiceID,
			&i.ServiceName,
			&i.Quantity,
			&i.UnitAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCheckInRoom = `-- name: LockCheckInRoom :one
SELECT u.id, u.code, u.building_id, u.status, ut.rate_plan, ut.rate_plan_version
FROM app.units u
JOIN app.unit_types ut ON ut.tenant_id = u.tenant_id AND ut.id = u.unit_type_id
WHERE u.tenant_id = $1 AND u.id = $2
FOR UPDATE OF u
`

type LockCheckInRoomParams struct {
	TenantID string
	UnitID   string
}

type LockCheckInRoomRow struct {
	ID              string
	Code            string
	BuildingID      string
	Status          string
	RatePlan        []byte
	RatePlanVersion int32
}

// FOR UPDATE OF u serializes concurrent check-ins of one room; the unit type row stays unlocked.
func (q *Queries) LockCheckInRoom(ctx context.Context, arg LockCheckInRoomParams) (LockCheckInRoomRow, error) {
	row := q.db.QueryRow(ctx, lockCheckInRoom, arg.TenantID, arg.UnitID)
	var i LockCheckInRoomRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.BuildingID,
		&i.Status,
		&i.RatePlan,
		&i.RatePlanVersion,
	)
	return i, err
}

const occupyRoom = `-- name: OccupyRoom :execrows
UPDATE app.units SET status = 'OCCUPIED'
WHERE tenant_id = $1 AND id = $2 AND status = 'VACANT'
`

type OccupyRoomParams struct {
	TenantID string
	UnitID   string
}

func (q *Queries) OccupyRoom(ctx context.Context, arg OccupyRoomParams) (int64, error) {
	result, err := q.db.Exec(ctx, occupyRoom, arg.TenantID, arg.UnitID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
