// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stay_edits.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const firstRecordedCheckIn = `-- name: FirstRecordedCheckIn :one
SELECT old_check_in_at FROM app.stay_edits
WHERE tenant_id = $1 AND stay_id = $2 AND kind = 'CHECK_IN'
ORDER BY created_at, id LIMIT 1
`

type FirstRecordedCheckInParams struct {
	TenantID string
	StayID   string
}

func (q *Queries) FirstRecordedCheckIn(ctx context.Context, arg FirstRecordedCheckInParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, firstRecordedCheckIn, arg.TenantID, arg.StayID)
	var old_check_in_at pgtype.Timestamptz
	err := row.Scan(&old_check_in_at)
	return old_check_in_at, err
}

const insertStayEdit = `-- name: InsertStayEdit :exec
INSERT INTO app.stay_edits (id, tenant_id, stay_id, kind, actor_id, old_check_in_at, new_check_in_at, reason_code, note,
                            from_room_code, to_room_code, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7,
        $8, $9, $10, $11, $12)
`

type InsertStayEditParams struct {
	ID           string
	TenantID     string
	StayID       string
	Kind         string
	ActorID      pgtype.Text
	OldCheckInAt pgtype.Timestamptz
	NewCheckInAt pgtype.Timestamptz
	ReasonCode   pgtype.Text
	Note         pgtype.Text
	FromRoomCode pgtype.Text
	ToRoomCode   pgtype.Text
	CreatedAt    pgtype.Timestamptz
}

func (q *Queries) InsertStayEdit(ctx context.Context, arg InsertStayEditParams) error {
	_, err := q.db.Exec(ctx, insertStayEdit,
		arg.ID,
		arg.TenantID,
		arg.StayID,
		arg.Kind,
		arg.ActorID,
		arg.OldCheckInAt,
		arg.NewCheckInAt,
		arg.ReasonCode,
		arg.Note,
		arg.FromRoomCode,
		arg.ToRoomCode,
		arg.CreatedAt,
	)
	return err
}

const moveStay = `-- name: MoveStay :execrows
UPDATE app.stays SET unit_id = $1, rental_type = $2, rate_plan_snapshot = $3,
       rate_plan_schema = $4
WHERE tenant_id = $5 AND id = $6 AND status = 'ACTIVE'
`

type MoveStayParams struct {
	UnitID           string
	RentalType       string
	RatePlanSnapshot []byte
	RatePlanSchema   int16
	TenantID         string
	StayID           string
}

func (q *Queries) MoveStay(ctx context.Context, arg MoveStayParams) (int64, error) {
	result, err := q.db.Exec(ctx, moveStay,
		arg.UnitID,
		arg.RentalType,
		arg.RatePlanSnapshot,
		arg.RatePlanSchema,
		arg.TenantID,
		arg.StayID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseRoom = `-- name: ReleaseRoom :execrows
UPDATE app.units SET status = 'TO_CLEAN'
WHERE tenant_id = $1 AND id = $2 AND status = 'OCCUPIED'
`

type ReleaseRoomParams struct {
	TenantID string
	UnitID   string
}

func (q *Queries) ReleaseRoom(ctx context.Context, arg ReleaseRoomParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseRoom, arg.TenantID, arg.UnitID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStayCheckIn = `-- name: UpdateStayCheckIn :execrows
UPDATE app.stays SET check_in_at = $1
WHERE tenant_id = $2 AND id = $3 AND status = 'ACTIVE'
`

type UpdateStayCheckInParams struct {
	CheckInAt pgtype.Timestamptz
	TenantID  string
	StayID    string
}

func (q *Queries) UpdateStayCheckIn(ctx context.Context, arg UpdateStayCheckInParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStayCheckIn, arg.CheckInAt, arg.TenantID, arg.StayID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
