// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stay_history.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getFrontDeskHistoryDays = `-- name: GetFrontDeskHistoryDays :one
SELECT coalesce(min(front_desk_history_days), 7)::int AS days FROM app.properties WHERE tenant_id = $1
`

func (q *Queries) GetFrontDeskHistoryDays(ctx context.Context, tenantID string) (int32, error) {
	row := q.db.QueryRow(ctx, getFrontDeskHistoryDays, tenantID)
	var days int32
	err := row.Scan(&days)
	return days, err
}

const getReceiptInvoice = `-- name: GetReceiptInvoice :one
SELECT iv.id, iv.stay_id, iv.bill_code, iv.quote, u.building_id, u.code AS room_code, s.check_in_at, s.check_out_at,
       coalesce((SELECT p.name FROM app.properties p WHERE p.tenant_id = iv.tenant_id ORDER BY p.created_at, p.id LIMIT 1), '')::text AS property_name
FROM app.invoices iv
JOIN app.stays s ON s.tenant_id = iv.tenant_id AND s.id = iv.stay_id
JOIN app.units u ON u.tenant_id = s.tenant_id AND u.id = s.unit_id
WHERE iv.tenant_id = $1 AND iv.id = $2 AND s.check_out_at IS NOT NULL
`

type GetReceiptInvoiceParams struct {
	TenantID  string
	InvoiceID string
}

type GetReceiptInvoiceRow struct {
	ID           string
	StayID       string
	BillCode     string
	Quote        []byte
	BuildingID   string
	RoomCode     string
	CheckInAt    pgtype.Timestamptz
	CheckOutAt   pgtype.Timestamptz
	PropertyName string
}

func (q *Queries) GetReceiptInvoice(ctx context.Context, arg GetReceiptInvoiceParams) (GetReceiptInvoiceRow, error) {
	row := q.db.QueryRow(ctx, getReceiptInvoice, arg.TenantID, arg.InvoiceID)
	var i GetReceiptInvoiceRow
	err := row.Scan(
		&i.ID,
		&i.StayID,
		&i.BillCode,
		&i.Quote,
		&i.BuildingID,
		&i.RoomCode,
		&i.CheckInAt,
		&i.CheckOutAt,
		&i.PropertyName,
	)
	return i, err
}

const getStayBuilding = `-- name: GetStayBuilding :one
SELECT u.building_id
FROM app.stays s JOIN app.units u ON u.tenant_id = s.tenant_id AND u.id = s.unit_id
WHERE s.tenant_id = $1 AND s.id = $2
`

type GetStayBuildingParams struct {
	TenantID string
	StayID   string
}

func (q *Queries) GetStayBuilding(ctx context.Context, arg GetStayBuildingParams) (string, error) {
	row := q.db.QueryRow(ctx, getStayBuilding, arg.TenantID, arg.StayID)
	var building_id string
	err := row.Scan(&building_id)
	return building_id, err
}

const listReceiptPayments = `-- name: ListReceiptPayments :many
SELECT p.id, p.method::text AS method, coalesce(p.received_amount, p.amount)::bigint AS amount, p.paid_at::timestamptz AS at
FROM app.payments p
WHERE p.tenant_id = $1 AND p.invoice_id = $2 AND p.status = 'PAID' AND p.paid_at IS NOT NULL
  AND (p.method = 'CASH' OR NOT EXISTS (SELECT 1 FROM app.payment_events pe
        WHERE pe.tenant_id = p.tenant_id AND pe.invoice_id = p.invoice_id AND pe.result IN ('PARTIAL', 'SETTLED')))
UNION ALL
SELECT pe.id, 'TRANSFER', pe.amount::bigint, pe.received_at::timestamptz
FROM app.payment_events pe
JOIN app.invoices iv ON iv.tenant_id = pe.tenant_id AND iv.id = pe.invoice_id AND iv.status = 'PAID'
WHERE pe.tenant_id = $1 AND pe.invoice_id = $2 AND pe.result IN ('PARTIAL', 'SETTLED')
ORDER BY 4, 1
`

type ListReceiptPaymentsParams struct {
	TenantID  string
	InvoiceID string
}

type ListReceiptPaymentsRow struct {
	ID     string
	Method string
	Amount int64
	At     pgtype.Timestamptz
}

// One line per cash payment and one per bank event that settled money on the invoice (each with its own amount and time), so a short
// transfer and its top-up are two lines that add up to the paid total. A transfer paid before bank events were tied to invoices has no
// such events: its payment is the line.
func (q *Queries) ListReceiptPayments(ctx context.Context, arg ListReceiptPaymentsParams) ([]ListReceiptPaymentsRow, error) {
	rows, err := q.db.Query(ctx, listReceiptPayments, arg.TenantID, arg.InvoiceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReceiptPaymentsRow
	for rows.Next() {
		var i ListReceiptPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Method,
			&i.Amount,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStayHistory = `-- name: ListStayHistory :many
WITH base AS (
    SELECT s.id, u.code AS room_code, s.guest_name, s.rental_type, s.check_in_at, s.check_out_at, s.status,
           u.building_id, coalesce(fu.name, '') AS front_desk_name, s.guest_phone,
           iv.total AS total, iv.id AS invoice_id, iv.bill_code AS bill_code, coalesce(pm.method, '')::text AS payment_method,
           CASE
               WHEN iv.status = 'OPEN' AND (EXISTS (SELECT 1 FROM app.payments p
                    WHERE p.tenant_id = s.tenant_id AND p.invoice_id = iv.id AND p.status = 'MISMATCH')
                    OR EXISTS (SELECT 1 FROM app.payment_events pe
                    WHERE pe.tenant_id = s.tenant_id AND pe.invoice_id = iv.id AND pe.result = 'PARTIAL')) THEN 'MISMATCH'
               WHEN iv.status = 'OPEN' THEN 'UNPAID'
               WHEN EXISTS (SELECT 1 FROM app.stay_edits e
                    WHERE e.tenant_id = s.tenant_id AND e.stay_id = s.id AND e.kind = 'CHECK_IN') THEN 'TIME_EDITED'
               WHEN s.status = 'ACTIVE' THEN 'IN_STAY'
               ELSE 'PAID'
           END AS state
    FROM app.stays s
    JOIN app.units u ON u.tenant_id = s.tenant_id AND u.id = s.unit_id
    LEFT JOIN app.users fu ON fu.tenant_id = s.tenant_id AND fu.id = s.created_by
    LEFT JOIN app.invoices iv ON iv.tenant_id = s.tenant_id AND iv.stay_id = s.id
    LEFT JOIN LATERAL (
        SELECT p.method FROM app.payments p
        WHERE p.tenant_id = s.tenant_id AND p.invoice_id = iv.id AND p.status = 'PAID'
        ORDER BY p.paid_at DESC LIMIT 1) pm ON true
    WHERE s.tenant_id = $7
      AND s.check_in_at >= $8 AND s.check_in_at < $9
      AND u.building_id = ANY($10::text[])
)
SELECT id, room_code, guest_name, rental_type, check_in_at, check_out_at, status, front_desk_name, total, invoice_id, bill_code, payment_method, state
FROM base
WHERE ($1::text IS NULL OR building_id = $1::text)
  AND ($2::text IS NULL OR state = $2::text)
  AND ($3::text IS NULL OR room_code ILIKE $3::text ESCAPE '\'
       OR guest_name ILIKE $3::text ESCAPE '\' OR guest_phone ILIKE $3::text ESCAPE '\')
  AND ($4::timestamptz IS NULL OR (check_in_at, id) < ($4::timestamptz, $5::text))
ORDER BY check_in_at DESC, id DESC
LIMIT $6
`

type ListStayHistoryParams struct {
	BuildingID  pgtype.Text
	State       pgtype.Text
	Pattern     pgtype.Text
	CursorAt    pgtype.Timestamptz
	CursorID    pgtype.Text
	RowLimit    int32
	TenantID    string
	FromAt      pgtype.Timestamptz
	ToAt        pgtype.Timestamptz
	BuildingIds []string
}

type ListStayHistoryRow struct {
	ID            string
	RoomCode      string
	GuestName     string
	RentalType    string
	CheckInAt     pgtype.Timestamptz
	CheckOutAt    pgtype.Timestamptz
	Status        string
	FrontDeskName string
	Total         pgtype.Int8
	InvoiceID     pgtype.Text
	BillCode      pgtype.Text
	PaymentMethod string
	State         string
}

// state: MISMATCH and UNPAID (money problems) win over TIME_EDITED, which wins over IN_STAY and PAID.
// The search pattern is escaped by the caller; check_in_at DESC, id DESC is the cursor order.
func (q *Queries) ListStayHistory(ctx context.Context, arg ListStayHistoryParams) ([]ListStayHistoryRow, error) {
	rows, err := q.db.Query(ctx, listStayHistory,
		arg.BuildingID,
		arg.State,
		arg.Pattern,
		arg.CursorAt,
		arg.CursorID,
		arg.RowLimit,
		arg.TenantID,
		arg.FromAt,
		arg.ToAt,
		arg.BuildingIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStayHistoryRow
	for rows.Next() {
		var i ListStayHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomCode,
			&i.GuestName,
			&i.RentalType,
			&i.CheckInAt,
			&i.CheckOutAt,
			&i.Status,
			&i.FrontDeskName,
			&i.Total,
			&i.InvoiceID,
			&i.BillCode,
			&i.PaymentMethod,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStayTimeline = `-- name: ListStayTimeline :many
SELECT at::timestamptz AS at, kind::text AS kind, actor_name::text AS actor_name, details::jsonb AS details FROM (
    SELECT coalesce((SELECT e.old_check_in_at FROM app.stay_edits e
                     WHERE e.tenant_id = s.tenant_id AND e.stay_id = s.id AND e.kind = 'CHECK_IN'
                     ORDER BY e.created_at, e.id LIMIT 1), s.check_in_at) AS at,
           'CHECKED_IN' AS kind, coalesce(u.name, '') AS actor_name,
           jsonb_build_object('room', un.code, 'rentalType', s.rental_type) AS details
    FROM app.stays s
    JOIN app.units un ON un.tenant_id = s.tenant_id AND un.id = s.unit_id
    LEFT JOIN app.users u ON u.tenant_id = s.tenant_id AND u.id = s.created_by
    WHERE s.tenant_id = $1 AND s.id = $2
  UNION ALL
    SELECT e.created_at, 'CHECK_IN_EDITED', coalesce(u.name, ''),
           jsonb_build_object('oldTime', to_char(e.old_check_in_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
                              'newTime', to_char(e.new_check_in_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
                              'reasonCode', e.reason_code, 'note', coalesce(e.note, ''))
    FROM app.stay_edits e LEFT JOIN app.users u ON u.tenant_id = e.tenant_id AND u.id = e.actor_id
    WHERE e.tenant_id = $1 AND e.stay_id = $2 AND e.kind = 'CHECK_IN'
  UNION ALL
    SELECT e.created_at, 'MOVED', coalesce(u.name, ''),
           jsonb_build_object('from', coalesce(e.from_room_code, ''), 'to', coalesce(e.to_room_code, ''))
    FROM app.stay_edits e LEFT JOIN app.users u ON u.tenant_id = e.tenant_id AND u.id = e.actor_id
    WHERE e.tenant_id = $1 AND e.stay_id = $2 AND e.kind = 'MOVE'
  UNION ALL
    SELECT x.created_at, 'EXTRAS_ADDED', coalesce(u.name, ''),
           jsonb_build_object('service', sv.code, 'quantity', x.quantity::text)
    FROM app.stay_extras x
    JOIN app.services sv ON sv.tenant_id = x.tenant_id AND sv.id = x.service_id
    LEFT JOIN app.users u ON u.tenant_id = x.tenant_id AND u.id = x.created_by
    WHERE x.tenant_id = $1 AND x.stay_id = $2
  UNION ALL
    SELECT iv.created_at, 'CHECKED_OUT', coalesce(u.name, ''), jsonb_build_object('billCode', iv.bill_code)
    FROM app.invoices iv
    LEFT JOIN app.audit_logs a ON a.tenant_id = iv.tenant_id AND a.action = 'stay.checked_out' AND a.entity_id = iv.stay_id
    LEFT JOIN app.users u ON u.tenant_id = a.tenant_id AND u.id = a.actor_id
    WHERE iv.tenant_id = $1 AND iv.stay_id = $2
  UNION ALL
    SELECT p.paid_at, 'PAYMENT_RECEIVED', coalesce(u.name, ''),
           jsonb_build_object('method', p.method, 'amount', p.amount::text)
    FROM app.payments p
    JOIN app.invoices iv ON iv.tenant_id = p.tenant_id AND iv.id = p.invoice_id
    LEFT JOIN app.audit_logs a ON a.tenant_id = p.tenant_id AND a.action = 'payment.settled' AND a.entity_id = p.id
    LEFT JOIN app.users u ON u.tenant_id = a.tenant_id AND u.id = a.actor_id
    WHERE p.tenant_id = $1 AND iv.stay_id = $2 AND p.status = 'PAID'
  UNION ALL
    SELECT pe.received_at, 'PAYMENT_MISMATCH', '',
           jsonb_build_object('expected', p.amount::text, 'received', coalesce(p.received_amount, 0)::text)
    FROM app.payments p
    JOIN app.invoices iv ON iv.tenant_id = p.tenant_id AND iv.id = p.invoice_id
    JOIN app.payment_events pe ON pe.tenant_id = p.tenant_id AND pe.external_id = p.transaction_id AND pe.result = 'MISMATCH'
    WHERE p.tenant_id = $1 AND iv.stay_id = $2 AND p.status = 'MISMATCH'
  UNION ALL
    SELECT pe.received_at, 'PAYMENT_MISMATCH', '', jsonb_build_object('received', pe.amount::text)
    FROM app.payment_events pe
    JOIN app.invoices iv ON iv.tenant_id = pe.tenant_id AND iv.id = pe.invoice_id
    WHERE pe.tenant_id = $1 AND iv.stay_id = $2 AND pe.result = 'PARTIAL'
  UNION ALL
    SELECT a.created_at, 'LINKED_BY_OWNER', coalesce(u.name, ''), '{}'::jsonb
    FROM app.invoices iv
    JOIN app.audit_logs a ON a.tenant_id = iv.tenant_id AND a.action = 'payment.linked' AND a.entity_id = iv.id
    LEFT JOIN app.users u ON u.tenant_id = a.tenant_id AND u.id = a.actor_id
    WHERE iv.tenant_id = $1 AND iv.stay_id = $2
  UNION ALL
    SELECT c.created_at, 'CLEANED', coalesce(u.name, ''), '{}'::jsonb
    FROM app.stays s
    JOIN app.invoices iv ON iv.tenant_id = s.tenant_id AND iv.stay_id = s.id AND iv.paid_at IS NOT NULL
    JOIN LATERAL (SELECT a.created_at, a.actor_id, a.tenant_id FROM app.audit_logs a
                  WHERE a.tenant_id = s.tenant_id AND a.action = 'room.cleaned' AND a.entity_id = s.unit_id
                    AND a.created_at >= iv.paid_at
                  ORDER BY a.created_at LIMIT 1) c ON true
    LEFT JOIN app.users u ON u.tenant_id = c.tenant_id AND u.id = c.actor_id
    WHERE s.tenant_id = $1 AND s.id = $2
) ev ORDER BY at, kind
`

type ListStayTimelineParams struct {
	TenantID string
	StayID   string
}

type ListStayTimelineRow struct {
	At        pgtype.Timestamptz
	Kind      string
	ActorName string
	Details   []byte
}

// One row per event; actors are resolved from the recorded user id (empty for the bank and the system).
func (q *Queries) ListStayTimeline(ctx context.Context, arg ListStayTimelineParams) ([]ListStayTimelineRow, error) {
	rows, err := q.db.Query(ctx, listStayTimeline, arg.TenantID, arg.StayID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStayTimelineRow
	for rows.Next() {
		var i ListStayTimelineRow
		if err := rows.Scan(
			&i.At,
			&i.Kind,
			&i.ActorName,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
