// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tickets.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOtherLockingTickets = `-- name: CountOtherLockingTickets :one
SELECT count(*) FROM app.maintenance_tickets
WHERE tenant_id = $1 AND unit_id = $2 AND id <> $3 AND room_locked AND status <> 'DONE'
`

type CountOtherLockingTicketsParams struct {
	TenantID string
	UnitID   string
	TicketID string
}

func (q *Queries) CountOtherLockingTickets(ctx context.Context, arg CountOtherLockingTicketsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countOtherLockingTickets, arg.TenantID, arg.UnitID, arg.TicketID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTicket = `-- name: GetTicket :one
SELECT t.id, t.code, t.unit_id, u.code AS room_code, u.building_id, u.status AS room_status, t.category, t.description, t.status, t.room_locked,
       coalesce(rb.name, '') AS reported_by, t.reported_at, t.expected_done_on, t.parts_cost, t.labour_cost, t.repairer, t.note, t.completed_at
FROM app.maintenance_tickets t
JOIN app.units u ON u.tenant_id = t.tenant_id AND u.id = t.unit_id
LEFT JOIN app.users rb ON rb.tenant_id = t.tenant_id AND rb.id = t.reported_by
WHERE t.tenant_id = $1 AND t.id = $2
`

type GetTicketParams struct {
	TenantID string
	TicketID string
}

type GetTicketRow struct {
	ID             string
	Code           string
	UnitID         string
	RoomCode       string
	BuildingID     string
	RoomStatus     string
	Category       string
	Description    string
	Status         string
	RoomLocked     bool
	ReportedBy     string
	ReportedAt     pgtype.Timestamptz
	ExpectedDoneOn pgtype.Date
	PartsCost      pgtype.Int8
	LabourCost     pgtype.Int8
	Repairer       pgtype.Text
	Note           pgtype.Text
	CompletedAt    pgtype.Timestamptz
}

func (q *Queries) GetTicket(ctx context.Context, arg GetTicketParams) (GetTicketRow, error) {
	row := q.db.QueryRow(ctx, getTicket, arg.TenantID, arg.TicketID)
	var i GetTicketRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.UnitID,
		&i.RoomCode,
		&i.BuildingID,
		&i.RoomStatus,
		&i.Category,
		&i.Description,
		&i.Status,
		&i.RoomLocked,
		&i.ReportedBy,
		&i.ReportedAt,
		&i.ExpectedDoneOn,
		&i.PartsCost,
		&i.LabourCost,
		&i.Repairer,
		&i.Note,
		&i.CompletedAt,
	)
	return i, err
}

const insertTicket = `-- name: InsertTicket :exec
INSERT INTO app.maintenance_tickets (id, tenant_id, code, unit_id, category, description, room_locked, reported_by, reported_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertTicketParams struct {
	ID          string
	TenantID    string
	Code        string
	UnitID      string
	Category    string
	Description string
	RoomLocked  bool
	ReportedBy  pgtype.Text
	ReportedAt  pgtype.Timestamptz
}

func (q *Queries) InsertTicket(ctx context.Context, arg InsertTicketParams) error {
	_, err := q.db.Exec(ctx, insertTicket,
		arg.ID,
		arg.TenantID,
		arg.Code,
		arg.UnitID,
		arg.Category,
		arg.Description,
		arg.RoomLocked,
		arg.ReportedBy,
		arg.ReportedAt,
	)
	return err
}

const listOpenTickets = `-- name: ListOpenTickets :many
SELECT t.id, u.code AS room_code FROM app.maintenance_tickets t
JOIN app.units u ON u.tenant_id = t.tenant_id AND u.id = t.unit_id
WHERE t.tenant_id = $1 AND t.status <> 'DONE'
ORDER BY t.reported_at, t.id
`

type ListOpenTicketsRow struct {
	ID       string
	RoomCode string
}

func (q *Queries) ListOpenTickets(ctx context.Context, tenantID string) ([]ListOpenTicketsRow, error) {
	rows, err := q.db.Query(ctx, listOpenTickets, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenTicketsRow
	for rows.Next() {
		var i ListOpenTicketsRow
		if err := rows.Scan(&i.ID, &i.RoomCode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTickets = `-- name: ListTickets :many
SELECT t.id, t.code, t.unit_id, u.code AS room_code, u.building_id, u.status AS room_status, t.category, t.description, t.status, t.room_locked,
       coalesce(rb.name, '') AS reported_by, t.reported_at, t.expected_done_on, t.parts_cost, t.labour_cost, t.repairer, t.note, t.completed_at
FROM app.maintenance_tickets t
JOIN app.units u ON u.tenant_id = t.tenant_id AND u.id = t.unit_id
LEFT JOIN app.users rb ON rb.tenant_id = t.tenant_id AND rb.id = t.reported_by
WHERE t.tenant_id = $1 AND ($2::text IS NULL OR t.status = $2::text)
ORDER BY t.reported_at DESC, t.id DESC
`

type ListTicketsParams struct {
	TenantID string
	Status   pgtype.Text
}

type ListTicketsRow struct {
	ID             string
	Code           string
	UnitID         string
	RoomCode       string
	BuildingID     string
	RoomStatus     string
	Category       string
	Description    string
	Status         string
	RoomLocked     bool
	ReportedBy     string
	ReportedAt     pgtype.Timestamptz
	ExpectedDoneOn pgtype.Date
	PartsCost      pgtype.Int8
	LabourCost     pgtype.Int8
	Repairer       pgtype.Text
	Note           pgtype.Text
	CompletedAt    pgtype.Timestamptz
}

func (q *Queries) ListTickets(ctx context.Context, arg ListTicketsParams) ([]ListTicketsRow, error) {
	rows, err := q.db.Query(ctx, listTickets, arg.TenantID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTicketsRow
	for rows.Next() {
		var i ListTicketsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.UnitID,
			&i.RoomCode,
			&i.BuildingID,
			&i.RoomStatus,
			&i.Category,
			&i.Description,
			&i.Status,
			&i.RoomLocked,
			&i.ReportedBy,
			&i.ReportedAt,
			&i.ExpectedDoneOn,
			&i.PartsCost,
			&i.LabourCost,
			&i.Repairer,
			&i.Note,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRoomForMaintenance = `-- name: LockRoomForMaintenance :one
SELECT u.id, u.code, u.building_id, u.status FROM app.units u WHERE u.tenant_id = $1 AND u.id = $2 FOR UPDATE OF u
`

type LockRoomForMaintenanceParams struct {
	TenantID string
	UnitID   string
}

type LockRoomForMaintenanceRow struct {
	ID         string
	Code       string
	BuildingID string
	Status     string
}

func (q *Queries) LockRoomForMaintenance(ctx context.Context, arg LockRoomForMaintenanceParams) (LockRoomForMaintenanceRow, error) {
	row := q.db.QueryRow(ctx, lockRoomForMaintenance, arg.TenantID, arg.UnitID)
	var i LockRoomForMaintenanceRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.BuildingID,
		&i.Status,
	)
	return i, err
}

const lockTicket = `-- name: LockTicket :one
SELECT t.id FROM app.maintenance_tickets t WHERE t.tenant_id = $1 AND t.id = $2 FOR UPDATE
`

type LockTicketParams struct {
	TenantID string
	TicketID string
}

func (q *Queries) LockTicket(ctx context.Context, arg LockTicketParams) (string, error) {
	row := q.db.QueryRow(ctx, lockTicket, arg.TenantID, arg.TicketID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const nextTicketSeq = `-- name: NextTicketSeq :one
UPDATE app.tenants SET ticket_seq = ticket_seq + 1 WHERE id = $1 RETURNING ticket_seq
`

// The counter row is locked by the update, so two reports at once get two numbers.
func (q *Queries) NextTicketSeq(ctx context.Context, tenantID string) (int32, error) {
	row := q.db.QueryRow(ctx, nextTicketSeq, tenantID)
	var ticket_seq int32
	err := row.Scan(&ticket_seq)
	return ticket_seq, err
}

const reopenRoom = `-- name: ReopenRoom :execrows
UPDATE app.units SET status = 'VACANT' WHERE tenant_id = $1 AND id = $2 AND status = 'MAINTENANCE'
`

type ReopenRoomParams struct {
	TenantID string
	UnitID   string
}

func (q *Queries) ReopenRoom(ctx context.Context, arg ReopenRoomParams) (int64, error) {
	result, err := q.db.Exec(ctx, reopenRoom, arg.TenantID, arg.UnitID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setRoomMaintenance = `-- name: SetRoomMaintenance :execrows
UPDATE app.units SET status = 'MAINTENANCE' WHERE tenant_id = $1 AND id = $2 AND status IN ('VACANT', 'TO_CLEAN', 'MAINTENANCE')
`

type SetRoomMaintenanceParams struct {
	TenantID string
	UnitID   string
}

func (q *Queries) SetRoomMaintenance(ctx context.Context, arg SetRoomMaintenanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, setRoomMaintenance, arg.TenantID, arg.UnitID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTicket = `-- name: UpdateTicket :exec
UPDATE app.maintenance_tickets SET status = $1, room_locked = $2, expected_done_on = $3,
       parts_cost = $4, labour_cost = $5, repairer = $6, note = $7,
       completed_at = $8, completed_by = coalesce($9, completed_by)
WHERE tenant_id = $10 AND id = $11
`

type UpdateTicketParams struct {
	Status         string
	RoomLocked     bool
	ExpectedDoneOn pgtype.Date
	PartsCost      pgtype.Int8
	LabourCost     pgtype.Int8
	Repairer       pgtype.Text
	Note           pgtype.Text
	CompletedAt    pgtype.Timestamptz
	CompletedBy    pgtype.Text
	TenantID       string
	TicketID       string
}

func (q *Queries) UpdateTicket(ctx context.Context, arg UpdateTicketParams) error {
	_, err := q.db.Exec(ctx, updateTicket,
		arg.Status,
		arg.RoomLocked,
		arg.ExpectedDoneOn,
		arg.PartsCost,
		arg.LabourCost,
		arg.Repairer,
		arg.Note,
		arg.CompletedAt,
		arg.CompletedBy,
		arg.TenantID,
		arg.TicketID,
	)
	return err
}
