#!/usr/bin/env bash
# GenHeader_SG002_AC5: every generated file says it is generated (first 12 lines) and is
# marked linguist-generated in .gitattributes, so reviews and the PR size script skip it.
set -u
cd "$(dirname "$0")/.."
fail=0
bad() { echo "FAIL: $*" >&2; fail=1; }

gen_dirs="api/internal/adapter/http/gen web/src/api/generated web/src/mocks/generated"
for d in $gen_dirs; do
  [ -d "$d" ] || { bad "missing generated directory $d (run make gen)"; continue; }
  while IFS= read -r f; do
    head -n 12 "$f" | grep -qiE 'code generated|auto-generated|generated by' || bad "no generated header: $f"
    head -n 12 "$f" | grep -qiE 'do not edit|do not make direct changes' || bad "no do-not-edit notice: $f"
    [ "$(git check-attr linguist-generated -- "$f" | awk '{print $NF}')" = "true" ] || bad "not marked linguist-generated: $f"
  done < <(find "$d" -type f)
done
for f in web/package-lock.json scripts/package-lock.json api/go.sum; do
  [ "$(git check-attr linguist-generated -- "$f" | awk '{print $NF}')" = "true" ] || bad "not marked linguist-generated: $f"
done

[ "$fail" -eq 0 ] && echo "GenHeader_SG002_AC5 PASS"
exit "$fail"
