#!/usr/bin/env python3
"""Writes docs/rehearsal/coverage.md: every row of docs/rehearsal/checklist.xlsx with its status, whether the latest results CSV has an
automated result for it, and, for rows without one, why (Bỏ qua, manual: real phone / printer / bank / eyes, or not yet automated).
Totals per group. Reads only; rerun it after every `make rehearse-test`.
usage: scripts/rehearsal-coverage.py [--xlsx docs/rehearsal/checklist.xlsx] [--csv results.csv] [--out docs/rehearsal/coverage.md]"""
import argparse, collections, csv, glob, importlib.util, os, re, sys, zipfile


def clone_results(pattern_dir="docs/rehearsal"):
    """The newest results file of THIS clone: results-<date>-<slug>.csv, the slug made from the clone's directory name like scripts/rehearse-env.sh."""
    slug = os.environ.get("REHEARSE_SLUG") or re.sub(r"^-+|-+$", "", re.sub(r"[^a-z0-9]", "-", os.path.basename(os.getcwd()).lower()))
    return max(glob.glob(f"{pattern_dir}/results-*-{slug}.csv"), default=None)

here = os.path.dirname(os.path.abspath(__file__))
spec = importlib.util.spec_from_file_location("rsync", os.path.join(here, "rehearsal-sync.py"))
rs = importlib.util.module_from_spec(spec)
spec.loader.exec_module(rs)

# Why a row cannot be automated: the first matching pattern in the title, the steps or the group wins.
MANUAL = [
    (r"điện thoại thật|điện thoại qua tunnel", "real phone"),
    (r"in phiếu|in khổ|80 mm|máy in", "printer"),
    (r"app ngân hàng|ngân hàng thật|SePay thật|giao dịch thật|2\.000đ|S3 thật|Test mode|Tunnel|Cloudflare|SePay: |SePay, ", "real bank / SePay / tunnel"),
    (r"VPS|tên miền|HTTPS|CI xanh|khóa mã hóa production|nhập nhà nghỉ thật|hướng dẫn lễ tân|thời hạn lưu", "real server or a human decision"),
]
# Rows that stay out of the automated run, with the reason (checked by hand against the sheet).
ROW_NOTES = {
    "DN-04": "manual: unsafe, wrong owner PINs would lock the only owner",
    "BM-05": "covered by make test-api-int (Go), run by make demo-check",
}
GROUP_MANUAL = {"Chuẩn bị": "setup done by hand (Khai)", "Go-live": "go-live, real world"}


def rows(xlsx):
    z = zipfile.ZipFile(xlsx)
    sst = rs.shared_strings(z)
    out = []
    for name, path in rs.sheet_files(z):
        xml = z.read(path).decode("utf-8")
        head = None
        for rm in rs.ROW.finditer(xml):
            cells = {m.group(1): rs.cell_text(m.group(3), m.group(4), sst).strip() for m in rs.CELL.finditer(rm.group(0))}
            if head is None:
                inv = {t.lower(): c for c, t in cells.items()}
                if "mã" in inv and "trạng thái" in inv:
                    head = inv
                continue
            rid = cells.get(head["mã"], "")
            if re.fullmatch(r"[A-Z]{2,3}-\d+", rid):
                g = lambda k: cells.get(head.get(k, ""), "")
                out.append({"id": rid, "group": g("nhóm"), "title": g("test case"), "steps": g("các bước"), "role": g("vai trò"), "status": g("trạng thái")})
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--xlsx", default="docs/rehearsal/checklist.xlsx")
    ap.add_argument("--csv")
    ap.add_argument("--out", default="docs/rehearsal/coverage.md")
    ap.add_argument("--needs-eyes", default="docs/rehearsal/needs-eyes.txt")
    a = ap.parse_args()
    path = a.csv or clone_results()
    if not path or not os.path.exists(a.xlsx):
        sys.exit("need docs/rehearsal/checklist.xlsx and a results CSV")
    results = {r["id"]: r for r in csv.DictReader(open(path, encoding="utf-8")) if re.fullmatch(r"[A-Z]{2,3}-\d+", r.get("id") or "")}
    eyes = rs.read_needs_eyes(a.needs_eyes)
    table, totals = [], collections.defaultdict(collections.Counter)
    for r in rows(a.xlsx):
        res = results.get(r["id"])
        if res and res["status"] in ("pass", "fail"):
            auto, why = res["status"], ""
            if r["id"] in eyes:
                why = "automated, needs eyes"
        elif r["status"].lower() in rs.SKIPPED:
            auto, why = "-", "Bỏ qua"
        else:
            auto = "-"
            text = f'{r["title"]} {r["steps"]}'
            why = ROW_NOTES.get(r["id"]) or GROUP_MANUAL.get(r["group"]) or next((f"manual: {w}" for p, w in MANUAL if re.search(p, text, re.I)), "") or (
                "manual: eyes" if r["id"] in eyes else "not yet automated")
            if res and res["status"] == "skip":
                why = "manual: " + (res["notes"].split(":", 1)[-1].strip()[:60] or "skipped")
        kind = "automated" if auto in ("pass", "fail") else ("skipped" if why == "Bỏ qua" else ("manual" if why.startswith(("manual", "setup", "go-live", "real", "covered")) else "todo"))
        totals[r["group"]][kind] += 1
        table.append((r, auto, why))
    lines = [f"# Rehearsal coverage", "", f"Checklist `{a.xlsx}` against `{path}`. Generated by `scripts/rehearsal-coverage.py`; do not edit.", "",
             "## Totals per group", "", "| Group | Rows | Automated | Manual | Bỏ qua | Not yet automated |", "| --- | ---: | ---: | ---: | ---: | ---: |"]
    all_ = collections.Counter()
    for g, c in totals.items():
        n = sum(c.values())
        lines.append(f"| {g} | {n} | {c['automated']} | {c['manual']} | {c['skipped']} | {c['todo']} |")
        all_.update(c)
    lines.append(f"| **All** | **{sum(all_.values())}** | **{all_['automated']}** | **{all_['manual']}** | **{all_['skipped']}** | **{all_['todo']}** |")
    lines += ["", "## Rows", "", "| Id | Group | Case | Sheet status | Automated | Why not |", "| --- | --- | --- | --- | --- | --- |"]
    for r, auto, why in table:
        lines.append(f"| {r['id']} | {r['group']} | {r['title'][:70].replace('|', '/')} | {r['status']} | {auto} | {why} |")
    open(a.out, "w", encoding="utf-8").write("\n".join(lines) + "\n")
    print(f"{a.out}: {len(table)} rows, automated {all_['automated']}, manual {all_['manual']}, Bỏ qua {all_['skipped']}, not yet automated {all_['todo']}")


main()
